# Generated by Django 5.0.6 on 2026-03-27 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('plano', models.CharField(default='free', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_anonimo', models.CharField(max_length=100)),
                ('febre', models.BooleanField(default=False)),
                ('tosse', models.BooleanField(default=False)),
                ('dor_corpo', models.BooleanField(default=False)),
                ('cansaco', models.BooleanField(default=False)),
                ('falta_ar', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('condado', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
        ),
    ]
