# Generated by Django 5.0.6 on 2026-03-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosintoma',
            name='id_anonimo',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='senha',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registrosintoma',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='registrosintoma',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
