# Generated by Django 5.0.6 on 2026-03-28 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_registrosintoma_id_anonimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosintoma',
            name='id_anonimo',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
