# Generated by Django 5.0.6 on 2026-03-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_registrosintoma_id_anonimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosintoma',
            name='doenca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
