# Generated by Django 5.0.6 on 2026-03-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_registrosintoma_doenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosintoma',
            name='doenca_confirmada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
