# Generated by Django 5.0.6 on 2026-03-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_registrosintoma_doenca_confirmada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosintoma',
            name='classificacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='grupo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
