# Generated by Django 5.0.6 on 2026-04-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_registrosintoma_classificacao_registrosintoma_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosintoma',
            name='confianca',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='suspeito',
            field=models.BooleanField(default=False),
        ),
    ]
