# Generated by Django 5.0.6 on 2026-04-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_registrosintoma_confianca_registrosintoma_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='plano',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
