# Generated by Codex on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_empresa_data_expiracao_alter_empresa_plano"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="acesso_governo",
            field=models.BooleanField(default=False),
        ),
    ]
