# Generated by Codex on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_empresa_acesso_governo"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="tipo_conta",
            field=models.CharField(
                choices=[("empresa", "Empresa"), ("governo", "Governo")],
                default="empresa",
                max_length=20,
            ),
        ),
    ]
