# Generated by Django 5.0.6 on 2026-04-17 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_empresa_tipo_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='max_dispositivos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='device_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='DispositivoAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=120)),
                ('apelido', models.CharField(blank=True, max_length=120, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_acesso', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='api.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'device_id')},
            },
        ),
    ]
