# Generated by Django 5.0.6 on 2026-04-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_empresa_max_dispositivos_registrosintoma_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sessao_ativa_chave',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sessao_ativa_device_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sessao_ativa_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
