# Generated by Django 5.0.6 on 2026-04-18 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_empresa_sessao_ativa_chave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonoSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('sessao_ativa_chave', models.CharField(blank=True, max_length=120, null=True)),
                ('sessao_ativa_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='max_usuarios',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pacote_codigo',
            field=models.CharField(default='starter_5', max_length=40),
        ),
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('sessao_ativa_chave', models.CharField(blank=True, max_length=120, null=True)),
                ('sessao_ativa_device_id', models.CharField(blank=True, max_length=120, null=True)),
                ('sessao_ativa_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='api.empresa')),
            ],
        ),
    ]
