# Generated by Django 5.0.6 on 2026-04-18 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_donosaas_empresa_max_usuarios_empresa_pacote_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceiroEventoSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=40)),
                ('pacote_codigo', models.CharField(blank=True, max_length=40, null=True)),
                ('ciclo', models.CharField(blank=True, max_length=20, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='registrado', max_length=30)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_financeiros', to='api.empresa')),
            ],
        ),
    ]
