# Generated by Django 5.0.6 on 2026-04-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_dispositivopushpublico'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteOficialExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte_id', models.CharField(max_length=80)),
                ('fonte_nome', models.CharField(max_length=160)),
                ('status', models.CharField(default='pendente', max_length=30)),
                ('modo', models.CharField(default='catalogo_seguro', max_length=40)),
                ('periodo_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('periodo_fim', models.CharField(blank=True, max_length=20, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('registros_lidos', models.PositiveIntegerField(default=0)),
                ('agregados_gerados', models.PositiveIntegerField(default=0)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FonteOficialAgregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte_id', models.CharField(max_length=80)),
                ('indicador', models.CharField(max_length=120)),
                ('pais', models.CharField(default='Brasil', max_length=80)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_ibge', models.CharField(blank=True, max_length=20, null=True)),
                ('periodo', models.CharField(max_length=20)),
                ('valor', models.FloatField(default=0)),
                ('unidade', models.CharField(default='casos', max_length=40)),
                ('taxa_100k', models.FloatField(blank=True, null=True)),
                ('fonte_nome', models.CharField(max_length=160)),
                ('versao_fonte', models.CharField(blank=True, max_length=80, null=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['fonte_id', 'indicador', 'periodo'], name='api_fonteof_fonte_i_9ce23e_idx'), models.Index(fields=['estado', 'cidade'], name='api_fonteof_estado_577ae3_idx')],
                'unique_together': {('fonte_id', 'indicador', 'codigo_ibge', 'estado', 'cidade', 'periodo')},
            },
        ),
    ]
