# Generated by Django 5.0.6 on 2026-04-20 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_fonteoficialexecucao_fonteoficialagregado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_tipo', models.CharField(default='sistema', max_length=40)),
                ('principal_id', models.CharField(blank=True, default='', max_length=80)),
                ('principal_nome', models.CharField(blank=True, default='', max_length=160)),
                ('acao', models.CharField(max_length=100)),
                ('objeto_tipo', models.CharField(blank=True, default='', max_length=80)),
                ('objeto_id', models.CharField(blank=True, default='', max_length=80)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='alertagovernamental',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertagovernamental',
            name='aprovado_por',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='alertagovernamental',
            name='criado_por',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='alertagovernamental',
            name='justificativa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alertagovernamental',
            name='protocolo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='alertagovernamental',
            name='publicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertagovernamental',
            name='revisado_por',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='alertagovernamental',
            name='revogado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertagovernamental',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_revisao', 'Em revisao'), ('aprovado', 'Aprovado'), ('publicado', 'Publicado'), ('revogado', 'Revogado')], default='rascunho', max_length=30),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='fonte_referencia',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='origem_dado',
            field=models.CharField(choices=[('cidadao', 'Relato cidadao'), ('oficial', 'Fonte oficial'), ('ia_estimativa', 'Estimativa IA'), ('institucional', 'Registro institucional')], default='cidadao', max_length=30),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='validade_epidemiologica',
            field=models.CharField(default='sinal_colaborativo', max_length=60),
        ),
        migrations.AddIndex(
            model_name='alertagovernamental',
            index=models.Index(fields=['empresa', 'status', 'ativo'], name='api_alertag_empresa_0790a6_idx'),
        ),
        migrations.AddIndex(
            model_name='alertagovernamental',
            index=models.Index(fields=['estado', 'cidade', 'bairro'], name='api_alertag_estado_9caa92_idx'),
        ),
        migrations.AddField(
            model_name='auditoriainstitucional',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_institucionais', to='api.empresa'),
        ),
        migrations.AddIndex(
            model_name='auditoriainstitucional',
            index=models.Index(fields=['empresa', 'acao'], name='api_auditor_empresa_b6a5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriainstitucional',
            index=models.Index(fields=['objeto_tipo', 'objeto_id'], name='api_auditor_objeto__0e6095_idx'),
        ),
    ]
