# Generated by Django 5.0.6 on 2026-04-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auditoriainstitucional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AceiteLegalPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=120)),
                ('versao', models.CharField(max_length=30)),
                ('plataforma', models.CharField(blank=True, default='', max_length=30)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('aceito_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-aceito_em'],
                'indexes': [models.Index(fields=['device_id', 'versao'], name='api_aceitel_device__8566c9_idx'), models.Index(fields=['aceito_em'], name='api_aceitel_aceito__9a480f_idx')],
            },
        ),
    ]
