# Generated by Django 5.0.6 on 2026-05-03 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_corporativo_mvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaCargoCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(blank=True, default='', max_length=40)),
                ('nivel_inicial', models.CharField(blank=True, default='junior', max_length=40)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_corporativos', to='api.empresa')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='api.empresasetor')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('empresa', 'setor', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='colaboradoraliascorporativo',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='api.empresacargocorporativo'),
        ),
        migrations.CreateModel(
            name='EquipamentoCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('codigo', models.CharField(blank=True, default='', max_length=60)),
                ('categoria', models.CharField(blank=True, default='', max_length=80)),
                ('criticidade', models.PositiveSmallIntegerField(default=3)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos_corporativos', to='api.empresa')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='api.empresasetor')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('empresa', 'setor', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='CompetenciaItemCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('conhecimento', 'Conhecimento'), ('pratica', 'Pratica'), ('seguranca', 'Seguranca'), ('equipamento', 'Equipamento')], default='conhecimento', max_length=20)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('peso', models.PositiveSmallIntegerField(default=1)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_competencia_corporativos', to='api.empresa')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_competencia', to='api.equipamentocorporativo')),
            ],
            options={
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaCompetenciaCorporativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=160)),
                ('descricao', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada', 'Enviada'), ('validada', 'Validada'), ('revisar', 'Revisar')], default='enviada', max_length=20)),
                ('pontuacao_autodeclarada', models.PositiveSmallIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_competencia', to='api.colaboradoraliascorporativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_competencia_corporativas', to='api.empresa')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_competencia', to='api.equipamentocorporativo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='api.competenciaitemcorporativo')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_competencia', to='api.empresasetor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_competencia', to='api.empresaunidade')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FuncaoCriticaCorporativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('descricao', models.TextField(blank=True, default='')),
                ('criticidade', models.PositiveSmallIntegerField(default=3)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcoes_criticas', to='api.empresacargocorporativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes_criticas_corporativas', to='api.empresa')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcoes_criticas', to='api.empresasetor')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TrilhaCompetenciaCorporativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True, default='')),
                ('nivel_alvo', models.CharField(blank=True, default='', max_length=40)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trilhas_competencia', to='api.empresacargocorporativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas_competencia_corporativas', to='api.empresa')),
                ('funcao_critica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trilhas_competencia', to='api.funcaocriticacorporativa')),
            ],
            options={
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='competenciaitemcorporativo',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.trilhacompetenciacorporativa'),
        ),
        migrations.CreateModel(
            name='ValidacaoCompetenciaCorporativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada')], default='pendente', max_length=20)),
                ('pontuacao_validador', models.PositiveSmallIntegerField(default=0)),
                ('comentario', models.TextField(blank=True, default='')),
                ('validado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacoes_competencia_corporativas', to='api.empresa')),
                ('evidencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validacao', to='api.evidenciacompetenciacorporativa')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacoes_competencia', to='api.empresausuario')),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='evidenciacompetenciacorporativa',
            index=models.Index(fields=['empresa', 'status'], name='api_evidenc_empresa_013f22_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenciacompetenciacorporativa',
            index=models.Index(fields=['empresa', 'alias'], name='api_evidenc_empresa_1190d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='funcaocriticacorporativa',
            unique_together={('empresa', 'cargo', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='trilhacompetenciacorporativa',
            unique_together={('empresa', 'cargo', 'titulo')},
        ),
        migrations.AlterUniqueTogether(
            name='competenciaitemcorporativo',
            unique_together={('trilha', 'titulo')},
        ),
        migrations.AddIndex(
            model_name='validacaocompetenciacorporativa',
            index=models.Index(fields=['empresa', 'resultado'], name='api_validac_empresa_332d74_idx'),
        ),
    ]
