# Generated by Django 5.0.6 on 2026-05-03 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_empresacargocorporativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoapoiocorporativo',
            name='atendente',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='pedidoapoiocorporativo',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoapoiocorporativo',
            name='resolucao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ProgramaCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('fadiga', 'Fadiga e recuperacao'), ('psicossocial', 'Risco psicossocial'), ('ergonomia', 'Ergonomia e saude fisica'), ('competencia', 'Competencia tecnica'), ('cultura', 'Cultura e comunicacao'), ('livre', 'Programa livre')], default='livre', max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('pausado', 'Pausado'), ('encerrado', 'Encerrado')], default='rascunho', max_length=20)),
                ('owner', models.CharField(max_length=160)),
                ('objetivo', models.TextField(blank=True, default='')),
                ('prazo', models.DateField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, default='')),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_corporativos', to='api.empresa')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to='api.empresasetor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to='api.empresaunidade')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AcaoCorporativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('origem', models.CharField(choices=[('manual', 'Criada manualmente'), ('risco', 'Gerada por risco'), ('apoio', 'Gerada por pedido de apoio'), ('programa', 'Vinculada a programa')], default='manual', max_length=20)),
                ('owner', models.CharField(max_length=160)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('evidencia', models.TextField(blank=True, default='')),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_corporativas', to='api.empresa')),
                ('pedido_apoio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes', to='api.pedidoapoiocorporativo')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes', to='api.empresasetor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes', to='api.empresaunidade')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes', to='api.programacorporativo')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='programacorporativo',
            index=models.Index(fields=['empresa', 'status'], name='api_program_empresa_119b54_idx'),
        ),
        migrations.AddIndex(
            model_name='acaocorporativa',
            index=models.Index(fields=['empresa', 'status'], name='api_acaocor_empresa_9e16f5_idx'),
        ),
        migrations.AddIndex(
            model_name='acaocorporativa',
            index=models.Index(fields=['empresa', 'origem'], name='api_acaocor_empresa_247f60_idx'),
        ),
    ]
