# Generated by Django 5.0.6 on 2026-05-03 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_gestao_corporativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaCorporativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('14x14', '14x14'), ('28x28', '28x28'), ('7x7', '7x7'), ('personalizado', 'Personalizado')], default='14x14', max_length=20)),
                ('dias_embarcado', models.PositiveSmallIntegerField(default=14)),
                ('dias_folga', models.PositiveSmallIntegerField(default=14)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_corporativas', to='api.empresa')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas', to='api.empresaunidade')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ColaboradorEscalaCorporativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_ciclo', models.DateField()),
                ('fase_atual', models.CharField(choices=[('embarcado', 'Embarcado'), ('folga', 'Folga')], default='embarcado', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='api.colaboradoraliascorporativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores_escala', to='api.empresa')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='api.escalacorporativa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='escalacorporativa',
            index=models.Index(fields=['empresa', 'ativo'], name='api_escalac_empresa_c651f9_idx'),
        ),
        migrations.AddIndex(
            model_name='colaboradorescalacorporativa',
            index=models.Index(fields=['empresa', 'escala'], name='api_colabor_empresa_30ca5f_idx'),
        ),
        migrations.AddIndex(
            model_name='colaboradorescalacorporativa',
            index=models.Index(fields=['empresa', 'fase_atual'], name='api_colabor_empresa_49d2b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='colaboradorescalacorporativa',
            unique_together={('alias', 'escala')},
        ),
    ]
