# Generated by Django 5.0.6 on 2026-05-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASOOcupacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('admissional', 'Admissional'), ('periodico', 'Periódico'), ('retorno_trabalho', 'Retorno ao Trabalho'), ('mudanca_risco', 'Mudança de Risco'), ('demissional', 'Demissional')], max_length=30)),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('medico_responsavel', models.CharField(blank=True, max_length=200)),
                ('crm', models.CharField(blank=True, max_length=30)),
                ('resultado', models.CharField(choices=[('apto', 'Apto'), ('inapto', 'Inapto'), ('apto_restricao', 'Apto com Restrição')], default='apto', max_length=20)),
                ('restricoes', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asos', to='api.empresa')),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='FuncionarioSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('matricula', models.CharField(blank=True, max_length=40)),
                ('cargo', models.CharField(max_length=120)),
                ('setor', models.CharField(blank=True, max_length=120)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('classe_risco', models.CharField(choices=[('I', 'Grau I'), ('II', 'Grau II'), ('III', 'Grau III'), ('IV', 'Grau IV')], default='II', max_length=4)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios_sst', to='api.empresa')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios_sst', to='api.empresaunidade')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ExameOcupacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_exame', models.CharField(choices=[('audiometria', 'Audiometria'), ('acuidade_visual', 'Acuidade Visual'), ('espirometria', 'Espirometria'), ('laboratorial', 'Laboratorial'), ('eletrocardiograma', 'Eletrocardiograma'), ('raio_x', 'Raio-X'), ('psicologico', 'Avaliação Psicológica'), ('outro', 'Outro')], max_length=30)),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('realizado', 'Realizado'), ('vencido', 'Vencido')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames', to='api.asoocupacional')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_ocupacionais', to='api.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='api.funcionariosst')),
            ],
            options={
                'ordering': ['data_validade'],
            },
        ),
        migrations.CreateModel(
            name='CATOcupacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tipico', 'Típico'), ('trajeto', 'De Trajeto'), ('doenca', 'Doença Ocupacional')], default='tipico', max_length=20)),
                ('gravidade', models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('grave', 'Grave'), ('fatal', 'Fatal')], default='leve', max_length=20)),
                ('data_acidente', models.DateField()),
                ('hora_acidente', models.TimeField(blank=True, null=True)),
                ('local_acidente', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField()),
                ('parte_corpo', models.CharField(blank=True, max_length=100)),
                ('cid', models.CharField(blank=True, max_length=10)),
                ('numero_cat', models.CharField(blank=True, max_length=30)),
                ('houve_afastamento', models.BooleanField(default=False)),
                ('dias_afastamento', models.IntegerField(default=0)),
                ('status_esocial', models.CharField(choices=[('nao_enviado', 'Não Enviado'), ('pendente', 'Pendente'), ('transmitido', 'Transmitido'), ('erro', 'Erro na Transmissão'), ('retificado', 'Retificado')], default='nao_enviado', max_length=20)),
                ('protocolo_esocial', models.CharField(blank=True, max_length=60)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='api.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='api.funcionariosst')),
            ],
            options={
                'ordering': ['-data_acidente'],
            },
        ),
        migrations.AddField(
            model_name='asoocupacional',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asos', to='api.funcionariosst'),
        ),
        migrations.CreateModel(
            name='AfastamentoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('acidente_trabalho', 'Acidente de Trabalho'), ('doenca_ocupacional', 'Doença Ocupacional'), ('doenca_comum', 'Doença Comum'), ('licenca_maternidade', 'Licença Maternidade'), ('licenca_paternidade', 'Licença Paternidade'), ('outro', 'Outro')], max_length=30)),
                ('cid', models.CharField(blank=True, max_length=10)),
                ('data_inicio', models.DateField()),
                ('data_prevista_retorno', models.DateField(blank=True, null=True)),
                ('data_retorno_real', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado'), ('retorno_programado', 'Retorno Programado')], default='ativo', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos_sst', to='api.empresa')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afastamentos', to='api.catocupacional')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos', to='api.funcionariosst')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PGR', 'Programa de Gerenciamento de Riscos'), ('PCMSO', 'Programa de Controle Médico de Saúde Ocupacional'), ('LTCAT', 'Laudo Técnico das Condições Ambientais'), ('laudo_insalubridade', 'Laudo de Insalubridade'), ('laudo_periculosidade', 'Laudo de Periculosidade'), ('PPP', 'Perfil Profissiográfico Previdenciário'), ('CIPA', 'Comissão Interna de Prevenção de Acidentes'), ('outro', 'Outro Documento SST')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('em_revisao', 'Em Revisão'), ('nao_cadastrado', 'Não Cadastrado')], default='vigente', max_length=20)),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=200)),
                ('registro_profissional', models.CharField(blank=True, max_length=60)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_sst', to='api.empresa')),
            ],
            options={
                'ordering': ['-data_emissao'],
                'indexes': [models.Index(fields=['empresa', 'tipo'], name='api_documen_empresa_c217ae_idx'), models.Index(fields=['empresa', 'status'], name='api_documen_empresa_f40df2_idx')],
            },
        ),
        migrations.CreateModel(
            name='eSocialEventoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('S-2210', 'S-2210 — Comunicação de Acidente do Trabalho'), ('S-2220', 'S-2220 — Monitoramento da Saúde do Trabalhador'), ('S-2240', 'S-2240 — Condições Ambientais do Trabalho')], max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('transmitido', 'Transmitido com Sucesso'), ('erro', 'Erro'), ('retificacao', 'Em Retificação')], default='pendente', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('protocolo', models.CharField(blank=True, max_length=60)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esocial_eventos', to='api.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_esocial_empresa_fbd13a_idx'), models.Index(fields=['empresa', 'tipo_evento'], name='api_esocial_empresa_ad4ff1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='funcionariosst',
            index=models.Index(fields=['empresa', 'ativo'], name='api_funcion_empresa_4de596_idx'),
        ),
        migrations.AddIndex(
            model_name='funcionariosst',
            index=models.Index(fields=['empresa', 'unidade'], name='api_funcion_empresa_2949a6_idx'),
        ),
        migrations.AddIndex(
            model_name='exameocupacional',
            index=models.Index(fields=['empresa', 'status'], name='api_exameoc_empresa_218ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='exameocupacional',
            index=models.Index(fields=['empresa', 'data_validade'], name='api_exameoc_empresa_7eaf69_idx'),
        ),
        migrations.AddIndex(
            model_name='catocupacional',
            index=models.Index(fields=['empresa', 'status_esocial'], name='api_catocup_empresa_f2fc6c_idx'),
        ),
        migrations.AddIndex(
            model_name='catocupacional',
            index=models.Index(fields=['empresa', 'data_acidente'], name='api_catocup_empresa_e756ef_idx'),
        ),
        migrations.AddIndex(
            model_name='asoocupacional',
            index=models.Index(fields=['empresa', 'data_validade'], name='api_asoocup_empresa_47d7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='asoocupacional',
            index=models.Index(fields=['empresa', 'resultado'], name='api_asoocup_empresa_6e275b_idx'),
        ),
        migrations.AddIndex(
            model_name='afastamentosst',
            index=models.Index(fields=['empresa', 'status'], name='api_afastam_empresa_efae5e_idx'),
        ),
        migrations.AddIndex(
            model_name='afastamentosst',
            index=models.Index(fields=['empresa', 'motivo'], name='api_afastam_empresa_cf474f_idx'),
        ),
    ]
