# Generated by Django 5.0.6 on 2026-05-05 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_sst_ocupacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreinamentoNR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(choices=[('NR-5', 'NR-5 · CIPA'), ('NR-6', 'NR-6 · EPI'), ('NR-10', 'NR-10 · Segurança em Eletricidade'), ('NR-11', 'NR-11 · Transporte de Cargas'), ('NR-12', 'NR-12 · Segurança em Máquinas'), ('NR-18', 'NR-18 · Construção Civil'), ('NR-20', 'NR-20 · Inflamáveis e Combustíveis'), ('NR-23', 'NR-23 · Proteção Contra Incêndios'), ('NR-33', 'NR-33 · Espaços Confinados'), ('NR-34', 'NR-34 · Construção Naval'), ('NR-35', 'NR-35 · Trabalho em Altura'), ('outro', 'Outro')], max_length=10)),
                ('titulo', models.CharField(blank=True, default='', max_length=200)),
                ('instrutor', models.CharField(blank=True, default='', max_length=120)),
                ('carga_horaria', models.PositiveSmallIntegerField(default=0, help_text='em horas')),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valido', 'Válido'), ('vencido', 'Vencido'), ('pendente', 'Pendente'), ('agendado', 'Agendado')], default='pendente', max_length=20)),
                ('certificado', models.CharField(blank=True, default='', max_length=200)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos_nr', to='api.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos', to='api.funcionariosst')),
            ],
            options={
                'ordering': ['-data_realizacao'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_treinam_empresa_96b7a4_idx'), models.Index(fields=['empresa', 'funcionario'], name='api_treinam_empresa_5fb8c8_idx'), models.Index(fields=['empresa', 'data_validade'], name='api_treinam_empresa_56eaae_idx')],
            },
        ),
    ]
