# Generated by Django 5.0.6 on 2026-05-05 23:36

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_treinamento_nr'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('direto', 'Direto'), ('grupo', 'Grupo')], default='direto', max_length=10)),
                ('nome', models.CharField(blank=True, default='', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas_diretas', to='api.colaboradoraliascorporativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_chat', to='api.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('empresa', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('empresa', 'Empresa'), ('colaborador', 'Colaborador')], max_length=12)),
                ('texto', models.TextField(max_length=2000)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='api.salachat')),
            ],
            options={
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['sala', 'criado_em'], name='api_mensage_sala_id_6ec85c_idx'), models.Index(fields=['empresa', 'lida'], name='api_mensage_empresa_8d62da_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessaoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala_jitsi', models.CharField(default=api.models._codigo_acesso, max_length=80, unique=True)),
                ('titulo', models.CharField(blank=True, default='Reunião', max_length=120)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada')], default='ativa', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_video', to='api.colaboradoraliascorporativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_video', to='api.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_sessaov_empresa_9e9258_idx')],
            },
        ),
    ]
