# Generated by Django 5.0.6 on 2026-05-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_treinamento_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamentonr',
            name='nr',
            field=models.CharField(choices=[('NR-1', 'NR-1 - GRO / PGR'), ('NR-2', 'NR-2 - Revogada'), ('NR-3', 'NR-3 - Risco grave e iminente'), ('NR-4', 'NR-4 - SESMT'), ('NR-5', 'NR-5 - CIPA'), ('NR-6', 'NR-6 - EPI'), ('NR-7', 'NR-7 - PCMSO'), ('NR-8', 'NR-8 - Ambiente construido'), ('NR-9', 'NR-9 - Exposicoes ocupacionais'), ('NR-10', 'NR-10 - Eletricidade'), ('NR-11', 'NR-11 - Movimentacao de cargas'), ('NR-12', 'NR-12 - Maquinas e equipamentos'), ('NR-13', 'NR-13 - Pressurizados'), ('NR-14', 'NR-14 - Fornos'), ('NR-15', 'NR-15 - Insalubridade'), ('NR-16', 'NR-16 - Periculosidade'), ('NR-17', 'NR-17 - Ergonomia'), ('NR-18', 'NR-18 - Construcao'), ('NR-19', 'NR-19 - Explosivos'), ('NR-20', 'NR-20 - Inflamaveis'), ('NR-21', 'NR-21 - Ceu aberto'), ('NR-22', 'NR-22 - Mineracao'), ('NR-23', 'NR-23 - Incendio'), ('NR-24', 'NR-24 - Conforto e higiene'), ('NR-25', 'NR-25 - Residuos'), ('NR-26', 'NR-26 - Sinalizacao'), ('NR-27', 'NR-27 - Revogada'), ('NR-28', 'NR-28 - Penalidades'), ('NR-29', 'NR-29 - Portuario'), ('NR-30', 'NR-30 - Aquaviario'), ('NR-31', 'NR-31 - Agro'), ('NR-32', 'NR-32 - Servicos de saude'), ('NR-33', 'NR-33 - Espacos confinados'), ('NR-34', 'NR-34 - Naval'), ('NR-35', 'NR-35 - Altura'), ('NR-36', 'NR-36 - Frigorificos'), ('NR-37', 'NR-37 - Petroleo offshore'), ('NR-38', 'NR-38 - Limpeza urbana'), ('outro', 'Outro')], max_length=10),
        ),
    ]
