# Generated by Django 5.0.6 on 2026-05-05 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_comunicacao_chat_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medico_coordenador', models.CharField(blank=True, default='', max_length=120)),
                ('crm_medico', models.CharField(blank=True, default='', max_length=30)),
                ('especialidade_medico', models.CharField(blank=True, default='Medicina do Trabalho', max_length=80)),
                ('nome_engenheiro', models.CharField(blank=True, default='', max_length=120)),
                ('crea_engenheiro', models.CharField(blank=True, default='', max_length=30)),
                ('nome_tecnico', models.CharField(blank=True, default='', max_length=120)),
                ('registro_tecnico', models.CharField(blank=True, default='', max_length=30)),
                ('nome_enfermeiro', models.CharField(blank=True, default='', max_length=120)),
                ('coren_enfermeiro', models.CharField(blank=True, default='', max_length=30)),
                ('alerta_aso_dias', models.PositiveSmallIntegerField(default=30)),
                ('alerta_exame_dias', models.PositiveSmallIntegerField(default=30)),
                ('alerta_treinamento_dias', models.PositiveSmallIntegerField(default=60)),
                ('email_alertas', models.EmailField(blank=True, default='', max_length=254)),
                ('alertas_ativos', models.BooleanField(default=True)),
                ('cnpj', models.CharField(blank=True, default='', max_length=18)),
                ('cnae_principal', models.CharField(blank=True, default='', max_length=100)),
                ('grau_risco', models.CharField(choices=[('1', 'Grau 1'), ('2', 'Grau 2'), ('3', 'Grau 3'), ('4', 'Grau 4')], default='2', max_length=1)),
                ('numero_funcionarios', models.PositiveIntegerField(default=0)),
                ('endereco_completo', models.TextField(blank=True, default='')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_sst', to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EPIItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('auditiva', 'Proteção Auditiva'), ('respiratoria', 'Proteção Respiratória'), ('visual', 'Proteção Visual'), ('maos', 'Proteção de Mãos'), ('pes', 'Proteção de Pés'), ('cabeca', 'Proteção de Cabeça'), ('altura', 'Proteção Contra Quedas'), ('corpo', 'Proteção do Corpo'), ('outro', 'Outro')], max_length=20)),
                ('ca_numero', models.CharField(blank=True, default='', max_length=20)),
                ('validade_ca', models.DateField(blank=True, null=True)),
                ('fornecedor', models.CharField(blank=True, default='', max_length=120)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis', to='api.empresa')),
            ],
            options={
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EntregaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField()),
                ('quantidade', models.PositiveSmallIntegerField(default=1)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_epi', to='api.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_epi', to='api.funcionariosst')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='api.epiitem')),
            ],
            options={
                'ordering': ['-data_entrega'],
            },
        ),
        migrations.CreateModel(
            name='MembroGrupoChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_chat', to='api.colaboradoraliascorporativo')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='api.salachat')),
            ],
        ),
        migrations.AddIndex(
            model_name='epiitem',
            index=models.Index(fields=['empresa', 'tipo'], name='api_epiitem_empresa_f4e5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='entregaepi',
            index=models.Index(fields=['empresa', 'funcionario'], name='api_entrega_empresa_d84861_idx'),
        ),
        migrations.AddIndex(
            model_name='entregaepi',
            index=models.Index(fields=['empresa', 'data_entrega'], name='api_entrega_empresa_a953b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membrogrupochat',
            unique_together={('sala', 'alias')},
        ),
    ]
