from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_comunicacao_chat_video"),
    ]

    operations = [
        # ── Farmácia ─────────────────────────────────────────────────────────
        migrations.CreateModel(
            name="FornecedorFarmacia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200)),
                ("cnpj", models.CharField(blank=True, default="", max_length=18)),
                ("contato", models.CharField(blank=True, default="", max_length=200)),
                ("email", models.EmailField(blank=True, default="")),
                ("telefone", models.CharField(blank=True, default="", max_length=20)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fornecedores_farmacia", to="api.empresa")),
            ],
            options={"ordering": ["nome"]},
        ),
        migrations.CreateModel(
            name="ItemFarmacia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200)),
                ("codigo", models.CharField(blank=True, default="", max_length=50)),
                ("categoria", models.CharField(choices=[("medicamento","Medicamento"),("material","Material"),("insumo","Insumo"),("outro","Outro")], default="medicamento", max_length=20)),
                ("descricao", models.TextField(blank=True, default="")),
                ("unidade_medida", models.CharField(default="unidade", max_length=30)),
                ("estoque_minimo", models.PositiveIntegerField(default=0)),
                ("estoque_atual", models.IntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens_farmacia", to="api.empresa")),
                ("fornecedor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="itens", to="api.fornecedorfarmacia")),
            ],
            options={"ordering": ["nome"]},
        ),
        migrations.CreateModel(
            name="MovimentoEstoque",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("entrada","Entrada"),("saida","Saída"),("ajuste","Ajuste"),("vencimento","Vencimento")], max_length=20)),
                ("quantidade", models.IntegerField()),
                ("estoque_anterior", models.IntegerField()),
                ("estoque_posterior", models.IntegerField()),
                ("motivo", models.TextField(blank=True, default="")),
                ("responsavel", models.CharField(blank=True, default="", max_length=200)),
                ("data_movimento", models.DateTimeField(auto_now_add=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="movimentos_estoque", to="api.empresa")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="movimentos", to="api.itemfarmacia")),
            ],
            options={"ordering": ["-data_movimento"]},
        ),
        migrations.CreateModel(
            name="PedidoCompraFarmacia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("rascunho","Rascunho"),("enviado","Enviado"),("aprovado","Aprovado"),("recebido","Recebido"),("cancelado","Cancelado")], default="rascunho", max_length=20)),
                ("observacoes", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pedidos_compra_farmacia", to="api.empresa")),
                ("fornecedor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pedidos", to="api.fornecedorfarmacia")),
            ],
            options={"ordering": ["-criado_em"]},
        ),
        migrations.CreateModel(
            name="ItemPedidoCompra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantidade_solicitada", models.PositiveIntegerField()),
                ("quantidade_recebida", models.PositiveIntegerField(default=0)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.itemfarmacia")),
                ("pedido", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="api.pedidocomprafarmacia")),
            ],
            options={"ordering": ["item__nome"]},
        ),
        migrations.CreateModel(
            name="DispensacaoMedicamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("paciente_nome", models.CharField(max_length=200)),
                ("paciente_cpf", models.CharField(blank=True, default="", max_length=14)),
                ("quantidade", models.PositiveIntegerField()),
                ("responsavel", models.CharField(blank=True, default="", max_length=200)),
                ("observacoes", models.TextField(blank=True, default="")),
                ("dispensado_em", models.DateTimeField(auto_now_add=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dispensacoes", to="api.empresa")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dispensacoes", to="api.itemfarmacia")),
            ],
            options={"ordering": ["-dispensado_em"]},
        ),
        # ── Hospital ─────────────────────────────────────────────────────────
        migrations.CreateModel(
            name="DepartamentoHospital",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200)),
                ("tipo", models.CharField(blank=True, default="", max_length=50)),
                ("capacidade_leitos", models.PositiveIntegerField(default=0)),
                ("responsavel", models.CharField(blank=True, default="", max_length=200)),
                ("ativo", models.BooleanField(default=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="departamentos_hospital", to="api.empresa")),
            ],
            options={"ordering": ["nome"]},
        ),
        migrations.CreateModel(
            name="LeitoHospital",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.CharField(max_length=20)),
                ("tipo", models.CharField(blank=True, default="", max_length=50)),
                ("status", models.CharField(choices=[("disponivel","Disponível"),("ocupado","Ocupado"),("manutencao","Manutenção"),("reservado","Reservado")], default="disponivel", max_length=20)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leitos_hospital", to="api.empresa")),
                ("departamento", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leitos", to="api.departamentohospital")),
            ],
            options={"ordering": ["departamento__nome","numero"], "unique_together": {("empresa","numero")}},
        ),
        migrations.CreateModel(
            name="PacienteHospital",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200)),
                ("cpf", models.CharField(blank=True, default="", max_length=14)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("sexo", models.CharField(blank=True, choices=[("M","Masculino"),("F","Feminino"),("O","Outro")], default="", max_length=1)),
                ("telefone", models.CharField(blank=True, default="", max_length=20)),
                ("endereco", models.TextField(blank=True, default="")),
                ("tipo_sanguineo", models.CharField(blank=True, default="", max_length=5)),
                ("alergias", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pacientes_hospital", to="api.empresa")),
            ],
            options={"ordering": ["nome"]},
        ),
        migrations.CreateModel(
            name="TriagemHospital",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prioridade", models.CharField(choices=[("vermelho","Vermelho - Emergência"),("laranja","Laranja - Muito Urgente"),("amarelo","Amarelo - Urgente"),("verde","Verde - Pouco Urgente"),("azul","Azul - Não Urgente")], max_length=20)),
                ("queixa_principal", models.TextField()),
                ("pressao_arterial", models.CharField(blank=True, default="", max_length=20)),
                ("temperatura", models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ("saturacao", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("frequencia_cardiaca", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("responsavel", models.CharField(blank=True, default="", max_length=200)),
                ("triado_em", models.DateTimeField(auto_now_add=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="triagens_hospital", to="api.empresa")),
                ("paciente", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="triagens", to="api.pacientehospital")),
            ],
            options={"ordering": ["-triado_em"]},
        ),
        migrations.CreateModel(
            name="InternacaoHospital",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("diagnostico", models.TextField()),
                ("medico_responsavel", models.CharField(blank=True, default="", max_length=200)),
                ("status", models.CharField(choices=[("ativa","Ativa"),("alta","Alta"),("transferido","Transferido"),("obito","Óbito")], default="ativa", max_length=20)),
                ("data_entrada", models.DateTimeField(auto_now_add=True)),
                ("data_saida", models.DateTimeField(blank=True, null=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="internacoes_hospital", to="api.empresa")),
                ("leito", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="internacoes", to="api.leitohospital")),
                ("paciente", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="internacoes", to="api.pacientehospital")),
            ],
            options={"ordering": ["-data_entrada"]},
        ),
        migrations.CreateModel(
            name="EvolucaoClinica",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.TextField()),
                ("responsavel", models.CharField(blank=True, default="", max_length=200)),
                ("registrado_em", models.DateTimeField(auto_now_add=True)),
                ("internacao", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evolucoes", to="api.internacaohospital")),
            ],
            options={"ordering": ["-registrado_em"]},
        ),
        # ── Governo ──────────────────────────────────────────────────────────
        migrations.CreateModel(
            name="ProgramaSaudeGov",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("planejamento","Planejamento"),("ativo","Ativo"),("suspenso","Suspenso"),("concluido","Concluído")], default="planejamento", max_length=20)),
                ("populacao_alvo", models.TextField(blank=True, default="")),
                ("orcamento_previsto", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("orcamento_executado", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim_prevista", models.DateField(blank=True, null=True)),
                ("responsavel", models.CharField(blank=True, default="", max_length=200)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="programas_saude_gov", to="api.empresa")),
            ],
            options={"ordering": ["-criado_em"]},
        ),
        migrations.CreateModel(
            name="IndicadorSaudeGov",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, default="")),
                ("tipo", models.CharField(choices=[("quantitativo","Quantitativo"),("percentual","Percentual"),("indice","Índice")], default="quantitativo", max_length=20)),
                ("meta", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("valor_atual", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("unidade", models.CharField(blank=True, default="", max_length=50)),
                ("periodo_referencia", models.CharField(blank=True, default="", max_length=50)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="indicadores_saude_gov", to="api.empresa")),
                ("programa", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="indicadores", to="api.programasaudegov")),
            ],
            options={"ordering": ["nome"]},
        ),
        migrations.CreateModel(
            name="OrcamentoSaudeGov",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ano", models.PositiveSmallIntegerField()),
                ("total_previsto", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("total_executado", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("fonte_recurso", models.CharField(blank=True, default="", max_length=200)),
                ("observacoes", models.TextField(blank=True, default="")),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="orcamentos_saude_gov", to="api.empresa")),
            ],
            options={"ordering": ["-ano"], "unique_together": {("empresa","ano")}},
        ),
        migrations.CreateModel(
            name="PlanoAcaoGov",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=300)),
                ("descricao", models.TextField(blank=True, default="")),
                ("responsavel", models.CharField(blank=True, default="", max_length=200)),
                ("prioridade", models.CharField(choices=[("alta","Alta"),("media","Média"),("baixa","Baixa")], default="media", max_length=10)),
                ("status", models.CharField(choices=[("pendente","Pendente"),("em_andamento","Em Andamento"),("concluido","Concluído"),("cancelado","Cancelado")], default="pendente", max_length=20)),
                ("prazo", models.DateField(blank=True, null=True)),
                ("progresso", models.PositiveSmallIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="planos_acao_gov", to="api.empresa")),
                ("programa", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="planos_acao", to="api.programasaudegov")),
            ],
            options={"ordering": ["-criado_em"]},
        ),
    ]
