# Generated by Django 5.0.6 on 2026-05-06 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_agendamento_sst'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtoNormativoGov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('portaria', 'Portaria'), ('resolucao', 'Resolução'), ('decreto', 'Decreto'), ('lei', 'Lei'), ('instrucao', 'Instrução Normativa'), ('nota_tecnica', 'Nota Técnica'), ('outro', 'Outro')], default='portaria', max_length=20)),
                ('numero', models.CharField(blank=True, default='', max_length=50)),
                ('titulo', models.CharField(max_length=400)),
                ('ementa', models.TextField(blank=True, default='')),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('data_vigencia', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('revogado', 'Revogado'), ('suspenso', 'Suspenso'), ('em_consulta', 'Em Consulta Pública')], default='vigente', max_length=20)),
                ('orgao_emissor', models.CharField(blank=True, default='', max_length=200)),
                ('url_documento', models.URLField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atos_normativos', to='api.empresa')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atos', to='api.programasaudegov')),
            ],
            options={
                'ordering': ['-data_publicacao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PrescricaoMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=300)),
                ('dose', models.CharField(blank=True, default='', max_length=100)),
                ('via', models.CharField(choices=[('oral', 'Oral'), ('ev', 'Endovenosa'), ('im', 'Intramuscular'), ('sc', 'Subcutânea'), ('inalatoria', 'Inalatória'), ('topica', 'Tópica'), ('sublingual', 'Sublingual'), ('outra', 'Outra')], default='oral', max_length=20)),
                ('frequencia', models.CharField(blank=True, default='', help_text='Ex: 8/8h, 1x ao dia, SN', max_length=100)),
                ('duracao_dias', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('medico', models.CharField(blank=True, default='', max_length=200)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('internacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes', to='api.internacaohospital')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LoteMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('fabricante', models.CharField(blank=True, default='', max_length=200)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField()),
                ('quantidade_inicial', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('nota_fiscal', models.CharField(blank=True, default='', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_medicamento', to='api.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fornecedorfarmacia')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='api.itemfarmacia')),
            ],
            options={
                'ordering': ['data_validade'],
                'unique_together': {('empresa', 'item', 'numero_lote')},
            },
        ),
    ]
