# Generated by Django 5.0.6 on 2026-05-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_agendamento_sst'),
        ('api', '0032_merge_operational_sst_branches'),
    ]

    operations = [
    ]
