# Generated by Django 5.0.6 on 2026-05-06 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_merge_lotes_prescricao_operational'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaVacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('vacina', models.CharField(help_text='Ex: Influenza, Hepatite B, COVID-19', max_length=150)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('meta_doses', models.PositiveIntegerField(default=0)),
                ('doses_aplicadas', models.PositiveIntegerField(default=0)),
                ('local', models.CharField(blank=True, default='', max_length=200)),
                ('responsavel', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejada', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas_vacinacao', to='api.empresa')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RiscoOcupacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=150)),
                ('tipo_risco', models.CharField(choices=[('fisico', 'Físico'), ('quimico', 'Químico'), ('biologico', 'Biológico'), ('ergonomico', 'Ergonômico'), ('acidente', 'Acidente / Mecânico'), ('psicossocial', 'Psicossocial')], max_length=20)),
                ('agente', models.CharField(help_text='Ex: ruido, poeira, virus, postura inadequada', max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('nivel', models.CharField(choices=[('I', 'I - Muito Baixo'), ('II', 'II - Baixo'), ('III', 'III - Médio'), ('IV', 'IV - Alto'), ('V', 'V - Muito Alto / Crítico')], default='III', max_length=5)),
                ('probabilidade', models.PositiveSmallIntegerField(default=3, help_text='1=Raro  2=Improvavel  3=Possivel  4=Provavel  5=Quase certo')),
                ('severidade', models.PositiveSmallIntegerField(default=3, help_text='1=Insignificante  2=Leve  3=Moderado  4=Grave  5=Catastrofico')),
                ('nr_referencia', models.CharField(blank=True, default='', help_text='Ex: NR-15, NR-17, NR-36', max_length=50)),
                ('medida_controle_existente', models.TextField(blank=True, default='')),
                ('medida_controle_proposta', models.TextField(blank=True, default='')),
                ('prazo', models.DateField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('identificado', 'Identificado'), ('em_controle', 'Em Controle'), ('controlado', 'Controlado'), ('residual', 'Risco Residual')], default='identificado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riscos_ocupacionais', to='api.empresa')),
            ],
            options={
                'ordering': ['-probabilidade', '-severidade'],
            },
        ),
        migrations.CreateModel(
            name='PlanoAcaoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField(blank=True, default='')),
                ('origem', models.CharField(choices=[('risco', 'Risco Ocupacional'), ('cat', 'CAT / Acidente'), ('afastamento', 'Afastamento'), ('auditoria', 'Auditoria Interna'), ('conformidade', 'Não-Conformidade'), ('outro', 'Outro')], default='risco', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('responsavel', models.CharField(blank=True, default='', max_length=150)),
                ('setor', models.CharField(blank=True, default='', max_length=150)),
                ('data_prazo', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado')], default='aberto', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_acao_sst', to='api.empresa')),
                ('risco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_acao', to='api.riscoocupacional')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroVacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField()),
                ('dose', models.CharField(choices=[('1a_dose', '1ª Dose'), ('2a_dose', '2ª Dose'), ('3a_dose', '3ª Dose'), ('reforco', 'Reforço'), ('dose_unica', 'Dose Única')], default='dose_unica', max_length=15)),
                ('lote_vacina', models.CharField(blank=True, default='', max_length=80)),
                ('aplicador', models.CharField(blank=True, default='', max_length=150)),
                ('observacoes', models.CharField(blank=True, default='', max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='api.campanhavacinacao')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinacoes', to='api.funcionariosst')),
            ],
            options={
                'ordering': ['-data_aplicacao'],
                'unique_together': {('campanha', 'funcionario', 'dose')},
            },
        ),
    ]
