# Generated by Django 5.0.6 on 2026-05-06 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_riscos_vacinacao_planos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plano_saude', 'Plano de Saúde'), ('convenio_medico', 'Convênio Médico'), ('seguro_saude', 'Seguro Saúde'), ('convenio_odontologico', 'Convênio Odontológico'), ('medicina_trabalho', 'Medicina do Trabalho'), ('outro', 'Outro')], max_length=30)),
                ('operadora', models.CharField(max_length=300)),
                ('numero_contrato', models.CharField(blank=True, default='', max_length=100)),
                ('registro_ans', models.CharField(blank=True, default='', help_text='Registro na ANS', max_length=50)),
                ('descricao', models.CharField(blank=True, default='', max_length=500)),
                ('abrangencia', models.CharField(choices=[('municipal', 'Municipal'), ('estadual', 'Estadual'), ('nacional', 'Nacional'), ('internacional', 'Internacional')], default='nacional', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_per_capita', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_beneficiarios', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('vencido', 'Vencido'), ('suspenso', 'Suspenso'), ('em_renovacao', 'Em Renovação'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('cobertura_detalhes', models.TextField(blank=True, default='')),
                ('carencias', models.TextField(blank=True, default='')),
                ('contato_operadora', models.CharField(blank=True, default='', max_length=200)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_saude', to='api.empresa')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SerieEpidemiologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('unidade', models.CharField(default='casos', help_text='Ex: casos, óbitos, internações', max_length=50)),
                ('granularidade', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensal', max_length=15)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_epidemiologicas', to='api.empresa')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='BeneficiarioContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carteirinha', models.CharField(blank=True, default='', max_length=100)),
                ('data_inclusao', models.DateField(blank=True, null=True)),
                ('data_exclusao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('dependentes', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_saude', to='api.funcionariosst')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='api.contratosaude')),
            ],
            options={
                'ordering': ['funcionario__nome'],
                'unique_together': {('contrato', 'funcionario')},
            },
        ),
        migrations.CreateModel(
            name='PontoSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fonte', models.CharField(blank=True, default='', max_length=200)),
                ('observacoes', models.CharField(blank=True, default='', max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='api.serieepidemiologica')),
            ],
            options={
                'ordering': ['data_referencia'],
                'unique_together': {('serie', 'data_referencia')},
            },
        ),
    ]
