from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_esocial_aso_sharing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rede",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200)),
                ("tipo", models.CharField(choices=[("farmacia","Rede de Farmácias"),("hospital","Rede Hospitalar"),("misto","Rede Mista")], default="farmacia", max_length=20)),
                ("cnpj_raiz", models.CharField(blank=True, default="", max_length=18)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("descricao", models.TextField(blank=True, default="")),
                ("ativa", models.BooleanField(default=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["nome"]},
        ),
        migrations.CreateModel(
            name="UnidadeRede",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("farmacia","Farmácia"),("hospital","Hospital")], default="farmacia", max_length=20)),
                ("nome_unidade", models.CharField(blank=True, default="", max_length=200)),
                ("codigo_unidade", models.CharField(blank=True, default="", max_length=20)),
                ("endereco", models.TextField(blank=True, default="")),
                ("cidade", models.CharField(blank=True, default="", max_length=100)),
                ("estado", models.CharField(blank=True, default="", max_length=2)),
                ("responsavel", models.CharField(blank=True, default="", max_length=150)),
                ("telefone", models.CharField(blank=True, default="", max_length=20)),
                ("ativa", models.BooleanField(default=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("empresa", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="unidade_rede", to="api.empresa")),
                ("rede", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="unidades", to="api.rede")),
            ],
            options={"ordering": ["nome_unidade"]},
        ),
        migrations.CreateModel(
            name="TransferenciaEstoque",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_item", models.CharField(blank=True, default="", max_length=200)),
                ("quantidade_solicitada", models.DecimalField(decimal_places=3, max_digits=10)),
                ("quantidade_aprovada", models.DecimalField(decimal_places=3, max_digits=10, null=True, blank=True)),
                ("status", models.CharField(choices=[("pendente","Pendente"),("aprovada","Aprovada"),("enviada","Enviada"),("recebida","Recebida"),("cancelada","Cancelada")], default="pendente", max_length=20)),
                ("motivo", models.TextField(blank=True, default="")),
                ("observacoes", models.TextField(blank=True, default="")),
                ("urgente", models.BooleanField(default=False)),
                ("solicitado_por", models.CharField(blank=True, default="", max_length=150)),
                ("aprovado_por", models.CharField(blank=True, default="", max_length=150)),
                ("solicitado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("rede", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transferencias", to="api.rede")),
                ("unidade_solicitante", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transferencias_solicitadas", to="api.unidaderede")),
                ("unidade_fornecedora", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transferencias_fornecidas", to="api.unidaderede")),
                ("item_farmacia", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transferencias", to="api.itemfarmacia")),
            ],
            options={"ordering": ["-solicitado_em"]},
        ),
        migrations.CreateModel(
            name="MensagemRede",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("geral","Mensagem Geral"),("transferencia","Sobre Transferência"),("alerta","Alerta")], default="geral", max_length=20)),
                ("assunto", models.CharField(blank=True, default="", max_length=200)),
                ("corpo", models.TextField()),
                ("lida", models.BooleanField(default=False)),
                ("enviada_em", models.DateTimeField(auto_now_add=True)),
                ("rede", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mensagens", to="api.rede")),
                ("remetente", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mensagens_enviadas", to="api.unidaderede")),
                ("destinatario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="mensagens_recebidas", to="api.unidaderede")),
                ("transferencia", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mensagens", to="api.transferenciaestoque")),
            ],
            options={"ordering": ["-enviada_em"]},
        ),
        migrations.CreateModel(
            name="PlanoSaude",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200)),
                ("registro_ans", models.CharField(blank=True, default="", max_length=20)),
                ("cnpj", models.CharField(blank=True, default="", max_length=18)),
                ("modalidade", models.CharField(blank=True, default="", max_length=20)),
                ("telefone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="")),
                ("site", models.URLField(blank=True, default="")),
                ("abrangencia", models.CharField(blank=True, default="nacional", max_length=50)),
                ("status", models.CharField(choices=[("ativo","Ativo"),("inativo","Inativo")], default="ativo", max_length=10)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("empresa", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="planos_saude", to="api.empresa")),
            ],
            options={"ordering": ["nome"]},
        ),
        migrations.CreateModel(
            name="BeneficiarioPlano",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200)),
                ("cpf", models.CharField(blank=True, default="", max_length=14)),
                ("numero_carteirinha", models.CharField(blank=True, default="", max_length=50)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("sexo", models.CharField(blank=True, default="", max_length=1)),
                ("telefone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="")),
                ("data_inicio_vigencia", models.DateField(blank=True, null=True)),
                ("data_fim_vigencia", models.DateField(blank=True, null=True)),
                ("situacao", models.CharField(choices=[("ativo","Ativo"),("suspenso","Suspenso"),("cancelado","Cancelado")], default="ativo", max_length=15)),
                ("plano_tipo", models.CharField(blank=True, default="", max_length=100)),
                ("acomodacao", models.CharField(blank=True, default="enfermaria", max_length=50)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("plano", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="beneficiarios", to="api.planosaude")),
            ],
            options={"ordering": ["nome"]},
        ),
        migrations.CreateModel(
            name="GuiaAutorizacao",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("consulta","Consulta"),("exame","Exame"),("internacao","Internação"),("medicamento","Medicamento de Alto Custo"),("procedimento","Procedimento Cirúrgico")], max_length=20)),
                ("numero_guia", models.CharField(blank=True, default="", max_length=50)),
                ("codigo_procedimento", models.CharField(blank=True, default="", max_length=20)),
                ("descricao_procedimento", models.TextField()),
                ("cid", models.CharField(blank=True, default="", max_length=10)),
                ("medico_solicitante", models.CharField(blank=True, default="", max_length=150)),
                ("crm_medico", models.CharField(blank=True, default="", max_length=30)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("valor_estimado", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("status", models.CharField(choices=[("solicitada","Solicitada"),("em_analise","Em Análise"),("autorizada","Autorizada"),("negada","Negada"),("cancelada","Cancelada")], default="solicitada", max_length=20)),
                ("justificativa_negativa", models.TextField(blank=True, default="")),
                ("numero_autorizacao", models.CharField(blank=True, default="", max_length=50)),
                ("validade_autorizacao", models.DateField(blank=True, null=True)),
                ("solicitada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                ("plano", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="guias", to="api.planosaude")),
                ("beneficiario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="guias", to="api.beneficiarioplano")),
                ("unidade", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="guias", to="api.unidaderede")),
            ],
            options={"ordering": ["-solicitada_em"]},
        ),
    ]
