# Generated by Django 5.0.6 on 2026-05-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_configuracaosst_esocial_certificado'),
    ]

    operations = [
    ]
