# Generated by Django 5.0.6 on 2026-05-17 04:40

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_merge_20260515_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('chave', models.CharField(default=api.models._codigo_acesso, max_length=64, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('total_chamadas', models.PositiveBigIntegerField(default=0)),
                ('ultimo_uso_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('revogada_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='IntegracaoRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(choices=[('totvs', 'TOTVS Protheus / RM'), ('adp', 'ADP Workforce'), ('senior', 'Senior Sistemas'), ('sap', 'SAP HCM'), ('esocial', 'eSocial Gov (direto)'), ('outro', 'Outro / Custom')], max_length=20)),
                ('nome', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('erro', 'Erro na última sync')], default='inativo', max_length=10)),
                ('webhook_secret', models.CharField(default=api.models._codigo_acesso, max_length=64)),
                ('endpoint_destino', models.URLField(blank=True, default='')),
                ('funcionarios_importados', models.PositiveIntegerField(default=0)),
                ('ultimo_sync_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_erro', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingPasso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passo', models.CharField(choices=[('primeiro_funcionario', 'Primeiro funcionário cadastrado'), ('primeiro_aso', 'Primeiro ASO emitido'), ('primeiro_epi', 'Primeira ficha de EPI registrada'), ('esocial_config', 'eSocial configurado'), ('usuario_adicional', 'Usuário adicional criado'), ('relatorio_gerado', 'Relatório gerado'), ('assinatura_digital', 'Primeira assinatura digital enviada')], max_length=40)),
                ('concluido_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['concluido_em'],
            },
        ),
        migrations.CreateModel(
            name='TrialEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('convertido', models.BooleanField(default=False)),
                ('convertido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='UsoApiEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(max_length=7)),
                ('endpoint', models.CharField(max_length=120)),
                ('chamadas', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-ano_mes'],
            },
        ),
        migrations.RenameIndex(
            model_name='outboxevento',
            new_name='api_outboxe_status_464606_idx',
            old_name='outbox_status_prox_idx',
        ),
        migrations.RenameIndex(
            model_name='outboxevento',
            new_name='api_outboxe_tipo_ev_8d9f51_idx',
            old_name='outbox_tipo_status_idx',
        ),
        migrations.RenameIndex(
            model_name='runmodelo',
            new_name='api_runmode_modelo__67a8c4_idx',
            old_name='run_modelo_criado_idx',
        ),
        migrations.AlterField(
            model_name='asocompartilhamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='beneficiarioplano',
            name='acomodacao',
            field=models.CharField(blank=True, choices=[('enfermaria', 'Enfermaria'), ('apartamento', 'Apartamento'), ('uti', 'UTI')], default='enfermaria', max_length=50),
        ),
        migrations.AlterField(
            model_name='beneficiarioplano',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cohortretencao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='descarteitemfarmacia',
            name='empresa_descarte',
            field=models.CharField(blank=True, default='', help_text='Empresa responsável pelo descarte', max_length=200),
        ),
        migrations.AlterField(
            model_name='descarteitemfarmacia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dispensacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dispensacao',
            name='medicamentos',
            field=models.JSONField(default=list, help_text='Lista de itens: [{medicamento_id, nome, quantidade, ...}]'),
        ),
        migrations.AlterField(
            model_name='estoquemovimento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evidenciacontrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expansaocontrato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='featureregistro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fornecedorfarmaciagestao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fornecedorfarmaciagestao',
            name='prazo_entrega_dias',
            field=models.PositiveSmallIntegerField(default=7, help_text='Prazo médio de entrega em dias'),
        ),
        migrations.AlterField(
            model_name='guiaautorizacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventariofarmacia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lancamentodespesa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leadcomercial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leitohospitalar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicamentofarmacia',
            name='concentracao',
            field=models.CharField(blank=True, default='', help_text='Ex: 500mg, 10mg/mL', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicamentofarmacia',
            name='controlado',
            field=models.BooleanField(default=False, help_text='Medicamento sujeito a controle especial (Portaria 344)'),
        ),
        migrations.AlterField(
            model_name='medicamentofarmacia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicamentofarmacia',
            name='refrigerado',
            field=models.BooleanField(default=False, help_text='Requer armazenamento refrigerado'),
        ),
        migrations.AlterField(
            model_name='medicamentofarmacia',
            name='validade_media_dias',
            field=models.PositiveIntegerField(default=365, help_text='Validade média em dias após fabricação'),
        ),
        migrations.AlterField(
            model_name='mensagemrede',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modeloml',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monitoramentomodelo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pacientefarmacia',
            name='alergias',
            field=models.TextField(blank=True, default='', help_text='Alergias e contraindicações conhecidas'),
        ),
        migrations.AlterField(
            model_name='pacientefarmacia',
            name='condicoes_cronicas',
            field=models.TextField(blank=True, default='', help_text='CIDs ou condições crônicas em acompanhamento'),
        ),
        migrations.AlterField(
            model_name='pacientefarmacia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pacientefarmacia',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='pacienteinternado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedidofarmacia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedidofarmacia',
            name='itens',
            field=models.JSONField(default=list, help_text='[{medicamento_id, quantidade, preco_unitario}]'),
        ),
        migrations.AlterField(
            model_name='planosaude',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planosaude',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('cooperativa', 'Cooperativa Médica'), ('autogestao', 'Autogestão'), ('seguradora', 'Seguradora'), ('filantropico', 'Filantrópico'), ('outro', 'Outro')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescricaohospitalar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rbacatribuicao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rbacpermissao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receitamedica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rede',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runmodelo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schemacontrato',
            name='compatibilidade',
            field=models.CharField(choices=[('full', 'Full (retrocompatível e forward)'), ('backward', 'Backward (novos leitores leem old)'), ('forward', 'Forward (old leitores leem new)'), ('none', 'Nenhuma (breaking changes permitidas)')], default='backward', max_length=20),
        ),
        migrations.AlterField(
            model_name='schemacontrato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soc2controle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscricaoevento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testecontrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='triagemmanchester',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unidaderede',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='versaoschema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='apikeyempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='integracaorh',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integracoes_rh', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='onboardingpasso',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_passos', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='trialempresa',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='usoapiempresa',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uso', to='api.apikeyempresa'),
        ),
        migrations.AddField(
            model_name='usoapiempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uso_api', to='api.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='integracaorh',
            unique_together={('empresa', 'sistema')},
        ),
        migrations.AlterUniqueTogether(
            name='onboardingpasso',
            unique_together={('empresa', 'passo')},
        ),
        migrations.AddIndex(
            model_name='usoapiempresa',
            index=models.Index(fields=['empresa', 'ano_mes'], name='api_usoapie_empresa_a1d8c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usoapiempresa',
            unique_together={('empresa', 'api_key', 'ano_mes', 'endpoint')},
        ),
    ]
