# Generated by Django 5.0.6 on 2026-05-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_gestao_crescimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='asoocupacional',
            name='cid_inapto',
            field=models.CharField(blank=True, max_length=10, verbose_name='CID (quando inapto/restrito)'),
        ),
        migrations.AddField(
            model_name='asoocupacional',
            name='riscos_ocupacionais',
            field=models.TextField(blank=True, verbose_name='Riscos ocupacionais do cargo (NR-7)'),
        ),
    ]
