# Generated by Django 5.0.6 on 2026-05-17 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_vinculo_clinica_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteNocivoPostoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_agente', models.CharField(choices=[('fisico', 'Físico'), ('quimico', 'Químico'), ('biologico', 'Biológico')], max_length=15)),
                ('cod_agente', models.CharField(choices=[('01.01.001', 'Ruído contínuo / intermitente'), ('01.01.002', 'Ruído de impacto'), ('01.02.001', 'Vibração em membros superiores'), ('01.02.002', 'Vibração em corpo inteiro'), ('01.03.001', 'Calor (IBUTG)'), ('01.04.001', 'Radiação ionizante'), ('01.05.001', 'Pressão hiperbárica'), ('01.06.001', 'Frio'), ('01.07.001', 'Umidade'), ('02.01.001', 'Arsênio e compostos'), ('02.01.002', 'Benzeno'), ('02.01.003', 'Chumbo e compostos'), ('02.01.004', 'Mercúrio e compostos'), ('02.01.005', 'Sílica livre cristalizada'), ('02.01.006', 'Asbestos / Amianto'), ('02.01.007', 'Manganês e compostos'), ('02.01.008', 'Cromo hexavalente'), ('02.01.009', 'Poeiras minerais em geral'), ('02.01.010', 'Poeiras orgânicas (madeira, couro, etc.)'), ('02.01.011', 'Fumos metálicos'), ('02.01.012', 'Névoas e neblinas'), ('02.01.013', 'Gases e vapores químicos em geral'), ('03.01.001', 'Vírus — Hepatite B (HBV)'), ('03.01.002', 'Vírus — HIV'), ('03.01.003', 'Vírus — outros'), ('03.02.001', 'Bactérias — tuberculose (Mycobacterium)'), ('03.02.002', 'Bactérias — outras'), ('03.03.001', 'Protozoários'), ('03.04.001', 'Fungos'), ('03.05.001', 'Parasitas / helmintos')], max_length=20, verbose_name='Código eSocial (Tabela 24)')),
                ('dsc_agente', models.CharField(blank=True, default='', max_length=300, verbose_name='Descrição complementar do agente')),
                ('tec_medicao', models.CharField(blank=True, default='', max_length=200, verbose_name='Técnica de medição utilizada')),
                ('intensidade', models.CharField(blank=True, default='', max_length=50, verbose_name='Intensidade / concentração medida')),
                ('limite_tolerancia', models.CharField(blank=True, default='', max_length=50, verbose_name='Limite de tolerância (NR/ACGIH)')),
                ('epc_descricao', models.CharField(blank=True, default='', max_length=300, verbose_name='EPC instalado (proteção coletiva)')),
                ('epc_eficaz', models.BooleanField(default=False, verbose_name='EPC é eficaz na neutralização')),
                ('epi_descricao', models.CharField(blank=True, default='', max_length=300, verbose_name='EPI fornecido (proteção individual)')),
                ('epi_ca', models.CharField(blank=True, default='', max_length=20, verbose_name='Número CA do EPI')),
                ('epi_eficaz', models.BooleanField(default=False, verbose_name='EPI é eficaz na neutralização')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tipo_agente', 'cod_agente'],
            },
        ),
        migrations.CreateModel(
            name='FuncionarioPostoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PostoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do posto / função')),
                ('setor', models.CharField(blank=True, default='', max_length=150)),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição das atividades')),
                ('responsavel_tecnico', models.CharField(blank=True, default='', max_length=180, verbose_name='Responsável técnico (Eng. Segurança / Médico)')),
                ('responsavel_registro', models.CharField(blank=True, default='', max_length=30, verbose_name='CRM ou CREA do responsável')),
                ('data_laudo', models.DateField(blank=True, null=True, verbose_name='Data do laudo (LTCAT/PPRA/PGR)')),
                ('vigencia_inicio', models.CharField(blank=True, default='', max_length=7, verbose_name='Início de vigência (AAAA-MM)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['setor', 'nome'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='vinculoclinicaempresa',
            name='unique_vinculo_clinica_empresa',
        ),
        migrations.RenameIndex(
            model_name='asoenviadoclinica',
            new_name='api_asoenvi_vinculo_d351ae_idx',
            old_name='api_aso_enviado_vinculo_idx',
        ),
        migrations.RenameIndex(
            model_name='vinculoclinicaempresa',
            new_name='api_vinculo_clinica_d6b389_idx',
            old_name='api_vinculo_clinica_status_idx',
        ),
        migrations.RenameIndex(
            model_name='vinculoclinicaempresa',
            new_name='api_vinculo_empresa_51f751_idx',
            old_name='api_vinculo_empresa_status_idx',
        ),
        migrations.RenameIndex(
            model_name='vinculoclinicaempresa',
            new_name='api_vinculo_token_c_9bdae7_idx',
            old_name='api_vinculo_token_idx',
        ),
        migrations.AlterField(
            model_name='asoocupacional',
            name='cid_inapto',
            field=models.CharField(blank=True, max_length=10, verbose_name='CID (quando inapto/restrito)'),
        ),
        migrations.AlterField(
            model_name='asoocupacional',
            name='riscos_ocupacionais',
            field=models.TextField(blank=True, verbose_name='Riscos ocupacionais do cargo (NR-7)'),
        ),
        migrations.AlterField(
            model_name='catocupacional',
            name='cod_agente_causador',
            field=models.CharField(choices=[('0001', 'Animais e insetos'), ('0002', 'Choque elétrico'), ('0003', 'Esforço excessivo / movimento repetitivo'), ('0004', 'Explosão / implosão'), ('0005', 'Incêndio'), ('0006', 'Queda'), ('0007', 'Substâncias químicas / gases / fumaças'), ('0008', 'Temperatura extrema (calor ou frio)'), ('0009', 'Máquinas e equipamentos'), ('0010', 'Material cortante / perfurante'), ('0011', 'Impacto por objeto / equipamento'), ('0012', 'Acidente de trânsito'), ('0099', 'Outros agentes')], default='0099', max_length=4, verbose_name='Agente causador (eSocial)'),
        ),
        migrations.AlterField(
            model_name='catocupacional',
            name='parte_corpo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Parte do corpo (descrição livre)'),
        ),
        migrations.AlterField(
            model_name='catocupacional',
            name='testemunha_nome',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nome da testemunha'),
        ),
        migrations.AlterField(
            model_name='catocupacional',
            name='testemunha_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone da testemunha'),
        ),
        migrations.AlterUniqueTogether(
            name='vinculoclinicaempresa',
            unique_together={('clinica', 'empresa_contratante')},
        ),
        migrations.AddField(
            model_name='funcionariopostotrabalho',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postos_vinculados', to='api.funcionariosst'),
        ),
        migrations.AddField(
            model_name='postotrabalho',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postos_trabalho', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='funcionariopostotrabalho',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios_vinculados', to='api.postotrabalho'),
        ),
        migrations.AddField(
            model_name='agentenocivopostotrabalho',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes_nocivos', to='api.postotrabalho'),
        ),
        migrations.AddIndex(
            model_name='postotrabalho',
            index=models.Index(fields=['empresa', 'ativo'], name='api_postotr_empresa_a53036_idx'),
        ),
        migrations.AddIndex(
            model_name='funcionariopostotrabalho',
            index=models.Index(fields=['posto', 'data_fim'], name='api_funcion_posto_i_a5bf8b_idx'),
        ),
    ]
