# Generated by Django 5.0.6 on 2026-05-17 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_postos_trabalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aso', models.CharField(choices=[('admissional', 'Admissional'), ('periodico', 'Periódico'), ('retorno_trabalho', 'Retorno ao Trabalho'), ('mudanca_risco', 'Mudança de Risco'), ('demissional', 'Demissional')], max_length=30)),
                ('exames', models.TextField(blank=True, default='', verbose_name='Exames solicitados (JSON)')),
                ('urgente', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_agendamento', models.DateField(blank=True, null=True)),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('resposta_clinica', models.TextField(blank=True, default='')),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_recebidas', to='api.empresa', verbose_name='Clínica destinatária')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_exame', to='api.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_exame', to='api.funcionariosst')),
                ('vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='api.vinculoclinicaempresa')),
            ],
            options={
                'ordering': ['-data_solicitacao'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_solicit_empresa_03021d_idx'), models.Index(fields=['clinica', 'status'], name='api_solicit_clinica_87cf06_idx')],
            },
        ),
    ]
