# Generated by Django 5.0.6 on 2026-05-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_solicitacao_exame'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoexame',
            name='clinica_email_externo',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='solicitacaoexame',
            name='clinica_nome_externo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='solicitacaoexame',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacaoexame',
            name='email_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
