# Moved to the end of the migration chain because production already applied 0046.

import api.models
import django.db.models.deletion
from django.db import migrations, models


def criar_tabela_assinatura_se_ausente(apps, schema_editor):
    table_name = 'api_assinaturadocumentosst'
    existing_tables = schema_editor.connection.introspection.table_names()
    if table_name in existing_tables:
        return

    vendor = schema_editor.connection.vendor
    if vendor == "sqlite":
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS api_assinaturadocumentosst (
                id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                tipo_documento varchar(30) NOT NULL,
                objeto_id integer NOT NULL CHECK (objeto_id >= 0),
                titulo varchar(240) NOT NULL,
                token varchar(64) NOT NULL UNIQUE,
                status varchar(20) NOT NULL,
                hash_documento varchar(64) NOT NULL,
                hash_assinatura varchar(64) NOT NULL,
                signatario_nome varchar(180) NOT NULL,
                signatario_email varchar(254) NOT NULL,
                signatario_cpf varchar(20) NOT NULL,
                solicitado_por varchar(180) NOT NULL,
                ip_solicitacao char(39) NULL,
                ip_assinatura char(39) NULL,
                user_agent_assinatura varchar(300) NOT NULL,
                assinado_em datetime NULL,
                expiracao_em datetime NULL,
                criado_em datetime NOT NULL,
                atualizado_em datetime NOT NULL,
                empresa_id bigint NOT NULL REFERENCES api_empresa(id),
                funcionario_id bigint NULL REFERENCES api_funcionariosst(id)
            )
        """)
    else:
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS api_assinaturadocumentosst (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tipo_documento varchar(30) NOT NULL,
                objeto_id integer NOT NULL CHECK (objeto_id >= 0),
                titulo varchar(240) NOT NULL,
                token varchar(64) NOT NULL UNIQUE,
                status varchar(20) NOT NULL,
                hash_documento varchar(64) NOT NULL,
                hash_assinatura varchar(64) NOT NULL,
                signatario_nome varchar(180) NOT NULL,
                signatario_email varchar(254) NOT NULL,
                signatario_cpf varchar(20) NOT NULL,
                solicitado_por varchar(180) NOT NULL,
                ip_solicitacao inet NULL,
                ip_assinatura inet NULL,
                user_agent_assinatura varchar(300) NOT NULL,
                assinado_em timestamp with time zone NULL,
                expiracao_em timestamp with time zone NULL,
                criado_em timestamp with time zone NOT NULL,
                atualizado_em timestamp with time zone NOT NULL,
                empresa_id bigint NOT NULL REFERENCES api_empresa(id) DEFERRABLE INITIALLY DEFERRED,
                funcionario_id bigint NULL REFERENCES api_funcionariosst(id) DEFERRABLE INITIALLY DEFERRED
            )
        """)
    schema_editor.execute("CREATE INDEX IF NOT EXISTS api_assinat_empresa_2ca5c2_idx ON api_assinaturadocumentosst (empresa_id, status)")
    schema_editor.execute("CREATE INDEX IF NOT EXISTS api_assinat_empresa_71725c_idx ON api_assinaturadocumentosst (empresa_id, tipo_documento, objeto_id)")
    schema_editor.execute("CREATE INDEX IF NOT EXISTS api_assinat_token_2d276c_idx ON api_assinaturadocumentosst (token)")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_solicitacao_exame_email'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(criar_tabela_assinatura_se_ausente, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='AssinaturaDocumentoSST',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('tipo_documento', models.CharField(choices=[('aso', 'ASO'), ('cat', 'CAT'), ('prontuario', 'Prontuário SST'), ('documento_sst', 'Documento SST')], max_length=30)),
                        ('objeto_id', models.PositiveIntegerField()),
                        ('titulo', models.CharField(max_length=240)),
                        ('token', models.CharField(default=api.models._codigo_acesso, max_length=64, unique=True)),
                        ('status', models.CharField(choices=[('pendente', 'Pendente'), ('assinado', 'Assinado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                        ('hash_documento', models.CharField(max_length=64)),
                        ('hash_assinatura', models.CharField(blank=True, default='', max_length=64)),
                        ('signatario_nome', models.CharField(blank=True, default='', max_length=180)),
                        ('signatario_email', models.EmailField(blank=True, default='', max_length=254)),
                        ('signatario_cpf', models.CharField(blank=True, default='', max_length=20)),
                        ('solicitado_por', models.CharField(blank=True, default='', max_length=180)),
                        ('ip_solicitacao', models.GenericIPAddressField(blank=True, null=True)),
                        ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True)),
                        ('user_agent_assinatura', models.CharField(blank=True, default='', max_length=300)),
                        ('assinado_em', models.DateTimeField(blank=True, null=True)),
                        ('expiracao_em', models.DateTimeField(blank=True, null=True)),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('atualizado_em', models.DateTimeField(auto_now=True)),
                        ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_sst', to='api.empresa')),
                        ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_sst', to='api.funcionariosst')),
                    ],
                    options={
                        'ordering': ['-criado_em'],
                        'indexes': [models.Index(fields=['empresa', 'status'], name='api_assinat_empresa_2ca5c2_idx'), models.Index(fields=['empresa', 'tipo_documento', 'objeto_id'], name='api_assinat_empresa_71725c_idx'), models.Index(fields=['token'], name='api_assinat_token_2d276c_idx')],
                    },
                ),
            ],
        ),
    ]
