# Generated by Django 5.0.6 on 2026-05-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_governo_fase2'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='atendimentourgencia',
            name='api_atend_unique',
        ),
        migrations.RemoveConstraint(
            model_name='metaprevine',
            name='api_previne_unique',
        ),
        migrations.RemoveConstraint(
            model_name='producaoambulatorial',
            name='api_producao_unique',
        ),
        migrations.RenameIndex(
            model_name='contratogestao',
            new_name='api_contrat_empresa_92d457_idx',
            old_name='api_cgestao_empresa_status_idx',
        ),
        migrations.RenameIndex(
            model_name='contratogestao',
            new_name='api_contrat_empresa_73310f_idx',
            old_name='api_cgestao_empresa_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacaocompulsoria',
            new_name='api_notific_empresa_b768fb_idx',
            old_name='api_notif_empresa_doenca_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacaocompulsoria',
            new_name='api_notific_empresa_e9d418_idx',
            old_name='api_notif_empresa_data_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacaocompulsoria',
            new_name='api_notific_empresa_57e118_idx',
            old_name='api_notif_empresa_mun_idx',
        ),
        migrations.RenameIndex(
            model_name='regulacaoleito',
            new_name='api_regulac_empresa_f97f82_idx',
            old_name='api_reg_empresa_status_idx',
        ),
        migrations.RenameIndex(
            model_name='regulacaoleito',
            new_name='api_regulac_empresa_a273e5_idx',
            old_name='api_reg_empresa_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='unidadesaude',
            new_name='api_unidade_empresa_6c6fae_idx',
            old_name='api_unid_empresa_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='unidadesaude',
            new_name='api_unidade_empresa_6d042a_idx',
            old_name='api_unid_empresa_mun_idx',
        ),
        migrations.AlterField(
            model_name='atendimentourgencia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contratogestao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipesaude',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metaprevine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificacaocompulsoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producaoambulatorial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='regulacaoleito',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='surtoepidemiologico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unidadesaude',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unidadesaude',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='atendimentourgencia',
            unique_together={('empresa', 'unidade', 'data_atendimento')},
        ),
        migrations.AlterUniqueTogether(
            name='metaprevine',
            unique_together={('empresa', 'indicador', 'competencia', 'municipio')},
        ),
        migrations.AlterUniqueTogether(
            name='producaoambulatorial',
            unique_together={('empresa', 'unidade', 'competencia')},
        ),
    ]
