# Generated by Django 5.0.6 on 2026-05-18 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_remove_atendimentourgencia_api_atend_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoSSTPublicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('video', 'Vídeo'), ('treinamento', 'Treinamento'), ('reuniao', 'Reunião de Vídeo'), ('comunicado', 'Comunicado')], default='comunicado', max_length=20)),
                ('descricao', models.TextField(blank=True, default='')),
                ('url_conteudo', models.URLField(blank=True, default='')),
                ('ambiente', models.CharField(choices=[('onshore', 'Onshore'), ('offshore', 'Offshore'), ('ambos', 'Todos')], default='ambos', max_length=10)),
                ('publicado_por', models.CharField(blank=True, default='', max_length=160)),
                ('ativo', models.BooleanField(default=True)),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos_sst', to='api.empresa')),
                ('setor_alvo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudos_sst', to='api.empresasetor')),
            ],
            options={
                'ordering': ['-publicado_em'],
                'indexes': [models.Index(fields=['empresa', 'tipo', 'ativo'], name='api_conteud_empresa_27710e_idx'), models.Index(fields=['empresa', 'ambiente'], name='api_conteud_empresa_ae5a97_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistroConflitoCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comunicacao', 'Barreira de comunicação'), ('discriminacao', 'Discriminação / preconceito'), ('idioma', 'Diferença de idioma'), ('religiao', 'Diferença religiosa / cultural'), ('comportamento', 'Comportamento inadequado'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('ambiente', models.CharField(choices=[('onshore', 'Onshore'), ('offshore', 'Offshore')], default='onshore', max_length=10)),
                ('descricao', models.CharField(blank=True, default='', max_length=500)),
                ('paises_envolvidos', models.CharField(blank=True, default='', max_length=200)),
                ('anonimo', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_analise', 'Em análise'), ('resolvido', 'Resolvido'), ('arquivado', 'Arquivado')], default='novo', max_length=20)),
                ('observacao_gestor', models.CharField(blank=True, default='', max_length=280)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflitos_culturais', to='api.colaboradoraliascorporativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflitos_culturais', to='api.empresa')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflitos_culturais', to='api.empresasetor')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_registr_empresa_64af30_idx'), models.Index(fields=['empresa', 'tipo'], name='api_registr_empresa_4c0334_idx')],
            },
        ),
    ]
