# Generated by Django 5.0.6 on 2026-05-19 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_saude_ocupacional_comunicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialAppFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credencial_app', to='api.funcionariosst')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aso', 'ASO'), ('exame', 'Exame'), ('treinamento', 'Treinamento'), ('geral', 'Geral')], default='geral', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField(blank=True)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_app', to='api.funcionariosst')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['funcionario', 'lida'], name='api_notific_funcion_13a76e_idx')],
            },
        ),
    ]
