# Generated by Django 5.0.6 on 2026-05-19 11:02

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_extend_subscription_and_aso_notify'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReuniaoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('descricao', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('funcionarios', 'Com Funcionários'), ('gerencial', 'Gerencial'), ('clinica_empresa', 'Clínica & Empresa'), ('todos', 'Todos')], default='funcionarios', max_length=20)),
                ('data_hora', models.DateTimeField()),
                ('duracao_minutos', models.PositiveSmallIntegerField(default=60)),
                ('sala_jitsi', models.CharField(default=api.models._codigo_acesso, max_length=80, unique=True)),
                ('link_externo', models.URLField(blank=True, default='', help_text='Link externo (Meet, Teams, Zoom). Se vazio usa Jitsi.')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em andamento'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
                ('notificar_funcionarios', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(blank=True, help_text='Clínica convidada (para reuniões Clínica & Empresa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunioes_clinica_sst', to='api.empresa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes_sst', to='api.empresa')),
                ('participantes', models.ManyToManyField(blank=True, help_text='Funcionários convidados. Vazio = todos.', related_name='reunioes_sst', to='api.funcionariosst')),
            ],
            options={
                'ordering': ['data_hora'],
                'indexes': [models.Index(fields=['empresa', 'status', 'data_hora'], name='api_reuniao_empresa_1c3f21_idx')],
            },
        ),
    ]
