# Generated by Django 5.0.6 on 2026-05-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_checkin_bem_estar'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='checkinbemestar',
            new_name='api_checkin_empresa_6af115_idx',
            old_name='api_checkin_empresa_criado_idx',
        ),
    ]
