# Generated by Django 5.0.6 on 2026-05-20 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_rename_api_checkin_empresa_criado_idx_api_checkin_empresa_6af115_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sinistro', models.CharField(blank=True, default='', max_length=60)),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('internacao', 'Internação'), ('exame', 'Exame / Diagnóstico'), ('procedimento', 'Procedimento Cirúrgico'), ('urgencia', 'Urgência / Emergência'), ('medicamento', 'Medicamento de Alto Custo'), ('outro', 'Outro')], default='consulta', max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('negado', 'Negado'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('cid', models.CharField(blank=True, default='', max_length=10)),
                ('descricao_procedimento', models.TextField(blank=True, default='')),
                ('prestador', models.CharField(blank=True, default='', max_length=200)),
                ('medico', models.CharField(blank=True, default='', max_length=150)),
                ('data_atendimento', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistros', to='api.beneficiarioplano')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistros', to='api.empresa')),
                ('guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinistros', to='api.guiaautorizacao')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistros', to='api.planosaude')),
            ],
            options={
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reembolso', models.CharField(blank=True, default='', max_length=60)),
                ('tipo_despesa', models.CharField(choices=[('consulta', 'Consulta Médica'), ('exame', 'Exame / Diagnóstico'), ('internacao', 'Internação'), ('medicamento', 'Medicamento'), ('terapia', 'Terapia / Reabilitação'), ('odonto', 'Odontologia'), ('outro', 'Outro')], default='consulta', max_length=20)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('pago', 'Pago'), ('negado', 'Negado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('valor_solicitado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_aprovado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('banco', models.CharField(blank=True, default='', max_length=100)),
                ('agencia', models.CharField(blank=True, default='', max_length=20)),
                ('conta', models.CharField(blank=True, default='', max_length=30)),
                ('descricao', models.TextField(blank=True, default='')),
                ('observacao', models.TextField(blank=True, default='')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='api.beneficiarioplano')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='api.empresa')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='api.planosaude')),
                ('sinistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos', to='api.sinistro')),
            ],
            options={
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
