# Generated by Django 5.0.6 on 2026-05-20 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_plano_saude_sinistro_reembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaautorizacao',
            name='auditor_responsavel',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='guiaautorizacao',
            name='documentos_pendentes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='guiaautorizacao',
            name='fila_status',
            field=models.CharField(choices=[('triagem', 'Triagem'), ('auditoria_clinica', 'Auditoria clínica'), ('auditoria_medica', 'Auditoria médica'), ('pendencia_documental', 'Pendência documental'), ('devolvida_prestador', 'Devolvida ao prestador'), ('autorizada', 'Autorizada'), ('negada', 'Negada')], default='triagem', max_length=30),
        ),
        migrations.AddField(
            model_name='guiaautorizacao',
            name='observacao_auditoria',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='guiaautorizacao',
            name='prazo_sla_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guiaautorizacao',
            name='prioridade_clinica',
            field=models.CharField(choices=[('eletiva', 'Eletiva'), ('urgente', 'Urgente'), ('alta_complexidade', 'Alta complexidade'), ('internacao', 'Internação')], default='eletiva', max_length=30),
        ),
        migrations.CreateModel(
            name='PrestadorPlanoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rede', models.CharField(blank=True, default='', max_length=30)),
                ('nome_fantasia', models.CharField(max_length=200)),
                ('razao_social', models.CharField(blank=True, default='', max_length=200)),
                ('cnpj', models.CharField(blank=True, default='', max_length=18)),
                ('tipo', models.CharField(choices=[('hospital', 'Hospital'), ('clinica', 'Clínica / AMB'), ('laboratorio', 'Laboratório'), ('imagem', 'Imagem / Diagnóstico'), ('pronto_atendimento', 'Pronto Atendimento'), ('homecare', 'Home Care')], default='clinica', max_length=30)),
                ('registro_cnes', models.CharField(blank=True, default='', max_length=30)),
                ('especialidades', models.TextField(blank=True, default='')),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(blank=True, default='', max_length=2)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('contato_responsavel', models.CharField(blank=True, default='', max_length=150)),
                ('sla_autorizacao_horas', models.PositiveSmallIntegerField(default=72)),
                ('portal_ativo', models.BooleanField(default=True)),
                ('score_qualidade', models.PositiveSmallIntegerField(default=85)),
                ('status', models.CharField(choices=[('credenciado', 'Credenciado'), ('implantacao', 'Em implantação'), ('suspenso', 'Suspenso'), ('descredenciado', 'Descredenciado')], default='credenciado', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestadores_plano', to='api.empresa')),
            ],
            options={
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.AddField(
            model_name='guiaautorizacao',
            name='prestador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias', to='api.prestadorplanosaude'),
        ),
    ]
