# Generated by Django 5.0.6 on 2026-05-20 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_guiaautorizacao_auditor_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlosaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_procedimento', models.CharField(blank=True, default='', max_length=20)),
                ('descricao', models.TextField()),
                ('valor_original', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_glosado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motivo', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('glosado', 'Glosado'), ('recurso_enviado', 'Recurso Enviado'), ('recurso_aceito', 'Recurso Aceito'), ('mantida', 'Glosa Mantida')], default='glosado', max_length=20)),
                ('data_glosa', models.DateField(blank=True, null=True)),
                ('data_recurso', models.DateField(blank=True, null=True)),
                ('resposta_recurso', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('sinistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosas', to='api.sinistro')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('cronico', 'Doença Crônica'), ('preventivo', 'Preventivo / Wellness'), ('oncologia', 'Oncologia'), ('maternidade', 'Maternidade / Pré-natal'), ('saude_mental', 'Saúde Mental'), ('reabilitacao', 'Reabilitação')], default='cronico', max_length=20)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_saude', to='api.empresa')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CoparticipacaoRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atendimento', models.CharField(choices=[('consulta', 'Consulta'), ('exame', 'Exame / Diagnóstico'), ('internacao', 'Internação'), ('cirurgia', 'Cirurgia'), ('terapia', 'Terapia / Reabilitação'), ('urgencia', 'Urgência / Emergência')], max_length=20)),
                ('percentual', models.DecimalField(decimal_places=2, default=0, help_text='% cobrado do beneficiário (0 a 100)', max_digits=5)),
                ('valor_fixo', models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo por evento (R$)', max_digits=10)),
                ('teto_mensal', models.DecimalField(blank=True, decimal_places=2, help_text='Teto mensal de coparticipação (R$), se houver', max_digits=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_coparticipacao', to='api.planosaude')),
            ],
            options={
                'ordering': ['plano', 'tipo_atendimento'],
                'unique_together': {('plano', 'tipo_atendimento')},
            },
        ),
        migrations.CreateModel(
            name='FaturamentoBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_coparticipacao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendente', max_length=15)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('pago_em', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='api.beneficiarioplano')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas_beneficiarios', to='api.empresa')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='api.planosaude')),
            ],
            options={
                'ordering': ['-competencia', 'beneficiario__nome'],
                'unique_together': {('empresa', 'beneficiario', 'competencia')},
            },
        ),
        migrations.CreateModel(
            name='InscricaoPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('concluido', 'Concluído'), ('abandonou', 'Abandonou')], default='ativo', max_length=15)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_programa', to='api.beneficiarioplano')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='api.programasaude')),
            ],
            options={
                'ordering': ['-data_inscricao'],
                'unique_together': {('programa', 'beneficiario')},
            },
        ),
    ]
