# Generated by Django 5.0.6 on 2026-05-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_plano_saude_expansao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosintoma',
            name='calafrios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='conjuntivite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='coriza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='diarreia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='dor_abdominal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='dor_articular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='dor_cabeca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='dor_garganta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='exantema',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='ictericia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='intensidade_articular',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('leve', 'Leve'), ('moderada', 'Moderada'), ('intensa', 'Intensa — incapacitante')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='intensidade_febre',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('baixa', 'Baixa'), ('moderada', 'Moderada'), ('alta', 'Alta')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='manchas_hemorragicas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='perda_olfato_paladar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='rigidez_nuca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='vomito_nausea',
            field=models.BooleanField(default=False),
        ),
    ]
