# Generated by Django 5.0.6 on 2026-05-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_sintomas_ia_expandidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosintoma',
            name='classificacao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
