# Generated by Django 5.0.6 on 2026-05-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_classificacao_max_length_300'),
    ]

    operations = [
        migrations.AddField(
            model_name='rede',
            name='codigo_convite',
            field=models.CharField(blank=True, default='', max_length=24, null=True, unique=True),
        ),
    ]
