# Generated by Django 5.0.6 on 2026-05-20 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_rede_codigo_convite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarenciaBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_procedimento', models.CharField(choices=[('consulta', 'Consultas'), ('exame', 'Exames e Procedimentos'), ('internacao', 'Internações'), ('parto', 'Parto'), ('urgencia', 'Urgência e Emergência'), ('odontologico', 'Odontológico')], max_length=30)),
                ('data_inicio', models.DateField()),
                ('dias_carencia', models.PositiveIntegerField(default=0, help_text='Período de carência em dias')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carencias', to='api.beneficiarioplano')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carencias', to='api.empresa')),
            ],
            options={
                'ordering': ['data_inicio'],
                'unique_together': {('beneficiario', 'tipo_procedimento')},
            },
        ),
    ]
