# Generated by Django 5.0.6 on 2026-05-20 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_carencia_beneficiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiarioOdonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, default='', max_length=14)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('plano_odonto', models.CharField(blank=True, default='Odonto Básico', max_length=100)),
                ('numero_carteirinha', models.CharField(blank=True, default='', max_length=50)),
                ('data_inicio_vigencia', models.DateField(blank=True, null=True)),
                ('data_fim_vigencia', models.DateField(blank=True, null=True)),
                ('data_ultimo_uso', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('carencia', 'Em Carência'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='ativo', max_length=15)),
                ('dentista_responsavel', models.CharField(blank=True, default='', max_length=150)),
                ('cro_dentista', models.CharField(blank=True, default='', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios_odonto', to='api.empresa')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContratoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=200)),
                ('cnpj', models.CharField(blank=True, default='', max_length=18)),
                ('contato_nome', models.CharField(blank=True, default='', max_length=100)),
                ('contato_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contato_telefone', models.CharField(blank=True, default='', max_length=20)),
                ('total_vidas', models.IntegerField(default=0)),
                ('mensalidade_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_inicio', models.DateField()),
                ('data_renovacao', models.DateField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado')], default='ativo', max_length=15)),
                ('logo_emoji', models.CharField(blank=True, default='🏢', max_length=10)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa_operadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_grupo_operados', to='api.empresa')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_grupo', to='api.planosaude')),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='GuiaOdonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tuss', models.CharField(blank=True, default='', max_length=20)),
                ('procedimento', models.CharField(max_length=200)),
                ('dentista', models.CharField(blank=True, default='', max_length=150)),
                ('clinica', models.CharField(blank=True, default='', max_length=200)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_execucao', models.DateField(blank=True, null=True)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('autorizado', 'Autorizado'), ('negado', 'Negado'), ('executado', 'Executado')], default='pendente', max_length=15)),
                ('justificativa_negacao', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='api.beneficiarioodonto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_odonto', to='api.empresa')),
            ],
            options={
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='MensagemPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_destinatario', models.CharField(choices=[('beneficiario', 'Beneficiário'), ('prestador', 'Prestador')], max_length=15)),
                ('canal', models.CharField(choices=[('plataforma', 'Plataforma'), ('email', 'E-mail'), ('sms', 'SMS')], default='plataforma', max_length=15)),
                ('direcao', models.CharField(choices=[('saida', 'Operadora → Destinatário'), ('entrada', 'Destinatário → Operadora')], default='saida', max_length=10)),
                ('assunto', models.CharField(blank=True, default='', max_length=200)),
                ('conteudo', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('enviado_por', models.CharField(blank=True, default='Operadora', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='api.beneficiarioplano')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_plano', to='api.empresa')),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='api.prestadorplanosaude')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TeleconsultaAutorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=100)),
                ('medico_solicitante', models.CharField(blank=True, default='', max_length=150)),
                ('plataforma', models.CharField(choices=[('conexa', 'Conexa Saúde'), ('iclinic', 'iClinic'), ('drconsulta', 'Dr. Consulta'), ('outro', 'Outro')], default='conexa', max_length=50)),
                ('link_consulta', models.URLField(blank=True, default='')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_agendada', models.DateTimeField(blank=True, null=True)),
                ('data_realizada', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('autorizado', 'Autorizado'), ('negado', 'Negado'), ('realizado', 'Realizado')], default='pendente', max_length=15)),
                ('nota_satisfacao', models.IntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('autorizado_por', models.CharField(blank=True, default='', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultas', to='api.beneficiarioplano')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultas', to='api.empresa')),
            ],
            options={
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
