# Generated by Django 5.0.6 on 2026-05-25 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_fap_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='biometria_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entregaepi',
            name='foto_entrega_base64',
            field=models.TextField(blank=True, default='', help_text='Foto capturada no momento da entrega'),
        ),
        migrations.CreateModel(
            name='AvaliacaoPsicossocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('setor_alvo', models.CharField(blank=True, help_text='Setor/departamento alvo', max_length=200)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativa', 'Ativa'), ('encerrada', 'Encerrada'), ('processada', 'Processada')], default='rascunho', max_length=15)),
                ('anonima', models.BooleanField(default=True)),
                ('link_token', models.CharField(help_text='Token para acesso do colaborador', max_length=64, unique=True)),
                ('total_enviados', models.PositiveIntegerField(default=0)),
                ('total_respondidos', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_psicossociais', to='api.empresa')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BiometriaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_base64', models.TextField(help_text='Foto de referência em base64 (JPEG/PNG, max 500KB)')),
                ('hash_foto', models.CharField(help_text='SHA-256 da foto original', max_length=64)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometria', to='api.funcionariosst')),
            ],
            options={
                'ordering': ['-cadastrado_em'],
            },
        ),
        migrations.CreateModel(
            name='ComissaoCIPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandato_inicio', models.DateField()),
                ('mandato_fim', models.DateField()),
                ('numero_membros_eleitos', models.PositiveSmallIntegerField(default=0)),
                ('numero_membros_indicados', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada'), ('em_formacao', 'Em Formação')], default='em_formacao', max_length=20)),
                ('designacao_nr5', models.BooleanField(default=False, help_text='Empresa com até 19 funcionários — designação em vez de eleição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_cipa', to='api.empresa')),
            ],
            options={
                'ordering': ['-mandato_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MembroCIPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('presidente', 'Presidente'), ('vice_presidente', 'Vice-Presidente'), ('secretario', 'Secretário'), ('membro_eleito', 'Membro Eleito'), ('membro_indicado', 'Membro Indicado')], max_length=30)),
                ('tipo', models.CharField(choices=[('eleito', 'Eleito'), ('indicado', 'Indicado')], max_length=15)),
                ('data_posse', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='api.comissaocipa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatos_cipa', to='api.funcionariosst')),
            ],
            options={
                'ordering': ['cargo'],
            },
        ),
        migrations.CreateModel(
            name='QuestaoAvaliacaoPsicossocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('categoria', models.CharField(choices=[('carga_trabalho', 'Carga de Trabalho'), ('autonomia', 'Autonomia e Controle'), ('relacionamento', 'Relacionamento Interpessoal'), ('reconhecimento', 'Reconhecimento e Recompensa'), ('seguranca', 'Segurança no Emprego'), ('equilibrio', 'Equilíbrio Trabalho-Vida'), ('violencia', 'Violência e Assédio')], max_length=30)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('escala', models.CharField(choices=[('likert5', 'Likert 1-5'), ('sim_nao', 'Sim/Não')], default='likert5', max_length=15)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='api.avaliacaopsicossocial')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RespostaPsicossocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_num', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resposta_bool', models.BooleanField(blank=True, null=True)),
                ('respondido_em', models.DateTimeField(auto_now_add=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='api.avaliacaopsicossocial')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_psicossociais', to='api.funcionariosst')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='api.questaoavaliacaopsicossocial')),
            ],
            options={
                'ordering': ['-respondido_em'],
            },
        ),
        migrations.CreateModel(
            name='ReuniaoCIPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ordinaria', 'Ordinária'), ('extraordinaria', 'Extraordinária')], default='ordinaria', max_length=20)),
                ('data_reuniao', models.DateTimeField()),
                ('pauta', models.TextField(blank=True)),
                ('ata', models.TextField(blank=True)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes', to='api.comissaocipa')),
            ],
            options={
                'ordering': ['-data_reuniao'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteReuniaoCIPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('assinatura_token', models.CharField(blank=True, max_length=64)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes_cipa', to='api.funcionariosst')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='api.reuniaocipa')),
            ],
        ),
        migrations.AddIndex(
            model_name='avaliacaopsicossocial',
            index=models.Index(fields=['empresa', 'status'], name='api_avaliac_empresa_934c36_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacaopsicossocial',
            index=models.Index(fields=['link_token'], name='api_avaliac_link_to_cc4f94_idx'),
        ),
        migrations.AddIndex(
            model_name='comissaocipa',
            index=models.Index(fields=['empresa', 'status'], name='api_comissa_empresa_55b159_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participantereuniaocipa',
            unique_together={('reuniao', 'funcionario')},
        ),
    ]
