from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0079_white_label_whatsapp"),
    ]

    operations = [
        # ── FARMÁCIA ─────────────────────────────────────────────────────────
        migrations.CreateModel(name="PDVSessao", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pdv_sessoes", to="api.empresa")),
            ("operador", models.CharField(max_length=120)),
            ("caixa_numero", models.PositiveSmallIntegerField(default=1)),
            ("abertura", models.DateTimeField(auto_now_add=True)),
            ("fechamento", models.DateTimeField(blank=True, null=True)),
            ("fundo_caixa", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ("total_vendas", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("total_dinheiro", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("total_pix", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("total_cartao_debito", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("total_cartao_credito", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("total_convenio", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("ativa", models.BooleanField(default=True)),
        ], options={"ordering": ["-abertura"]}),

        migrations.CreateModel(name="PDVVenda", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("sessao", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="vendas", to="api.pdvsessao")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pdv_vendas", to="api.empresa")),
            ("numero_cupom", models.CharField(blank=True, max_length=40)),
            ("forma_pagamento", models.CharField(choices=[("dinheiro","Dinheiro"),("pix","Pix"),("debito","Débito"),("credito","Crédito"),("convenio","Convênio/PBM")], default="dinheiro", max_length=20)),
            ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("desconto", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("troco", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ("cpf_cliente", models.CharField(blank=True, max_length=14)),
            ("cancelada", models.BooleanField(default=False)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["-criado_em"]}),

        migrations.CreateModel(name="PDVItemVenda", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("venda", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="api.pdvvenda")),
            ("codigo_barras", models.CharField(blank=True, max_length=40)),
            ("descricao", models.CharField(max_length=200)),
            ("lote", models.CharField(blank=True, max_length=40)),
            ("quantidade", models.DecimalField(decimal_places=3, default=1, max_digits=10)),
            ("preco_unitario", models.DecimalField(decimal_places=2, max_digits=10)),
            ("desconto_item", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ("total_item", models.DecimalField(decimal_places=2, max_digits=14)),
            ("controlado", models.BooleanField(default=False)),
            ("receita_numero", models.CharField(blank=True, max_length=60)),
        ]),

        migrations.CreateModel(name="PBMConvenio", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pbm_convenios", to="api.empresa")),
            ("nome", models.CharField(max_length=120)),
            ("codigo_credenciado", models.CharField(blank=True, max_length=60)),
            ("percentual_desconto_padrao", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ("ativo", models.BooleanField(default=True)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
        ]),

        migrations.CreateModel(name="FarmaciaPopularRegistro", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="farmacia_popular", to="api.empresa")),
            ("mes_referencia", models.DateField()),
            ("medicamentos_dispensados", models.PositiveIntegerField(default=0)),
            ("valor_subsidiado", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("valor_copagamento", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("arquivos_transmitidos", models.BooleanField(default=False)),
            ("enviado_em", models.DateTimeField(blank=True, null=True)),
        ], options={"ordering": ["-mes_referencia"]}),

        migrations.CreateModel(name="DREFarmacia", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dre_farmacia", to="api.empresa")),
            ("mes_referencia", models.DateField()),
            ("receita_bruta", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ("devolucoes", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ("impostos", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ("cmv", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ("despesas_operacionais", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ("despesas_pessoal", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ("despesas_aluguel", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ("outras_despesas", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ("observacoes", models.TextField(blank=True)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
            ("atualizado_em", models.DateTimeField(auto_now=True)),
        ], options={"ordering": ["-mes_referencia"], "unique_together": {("empresa", "mes_referencia")}}),

        migrations.CreateModel(name="PedidoDelivery", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pedidos_delivery", to="api.empresa")),
            ("numero_pedido", models.CharField(max_length=40)),
            ("cliente_nome", models.CharField(max_length=120)),
            ("cliente_telefone", models.CharField(max_length=20)),
            ("cliente_endereco", models.TextField()),
            ("status", models.CharField(choices=[("aguardando","Aguardando"),("confirmado","Confirmado"),("em_preparo","Em Preparo"),("saiu","Saiu para Entrega"),("entregue","Entregue"),("cancelado","Cancelado")], default="aguardando", max_length=20)),
            ("origem", models.CharField(default="whatsapp", max_length=40)),
            ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("observacoes", models.TextField(blank=True)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
            ("atualizado_em", models.DateTimeField(auto_now=True)),
        ], options={"ordering": ["-criado_em"]}),

        # ── HOSPITAL ─────────────────────────────────────────────────────────
        migrations.CreateModel(name="ProntuarioHospitalar", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prontuarios_hospitalares", to="api.empresa")),
            ("numero_prontuario", models.CharField(blank=True, max_length=40)),
            ("paciente_nome", models.CharField(max_length=160)),
            ("paciente_cpf", models.CharField(blank=True, max_length=14)),
            ("paciente_nascimento", models.DateField(blank=True, null=True)),
            ("paciente_sexo", models.CharField(choices=[("M","M"),("F","F"),("O","O")], default="M", max_length=1)),
            ("paciente_telefone", models.CharField(blank=True, max_length=20)),
            ("alergias", models.TextField(blank=True)),
            ("comorbidades", models.TextField(blank=True)),
            ("observacoes", models.TextField(blank=True)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
            ("atualizado_em", models.DateTimeField(auto_now=True)),
        ], options={"ordering": ["-criado_em"]}),

        migrations.CreateModel(name="EvolucaoProntuario", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("prontuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evolucoes", to="api.prontuariohospitalar")),
            ("profissional", models.CharField(max_length=120)),
            ("crm_coren", models.CharField(blank=True, max_length=40)),
            ("tipo", models.CharField(default="medica", max_length=30)),
            ("texto", models.TextField()),
            ("cid10", models.CharField(blank=True, max_length=10)),
            ("assinado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["-assinado_em"]}),

        migrations.CreateModel(name="PrescricaoProntuario", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("prontuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prescricoes", to="api.prontuariohospitalar")),
            ("profissional", models.CharField(max_length=120)),
            ("medicamento", models.CharField(max_length=200)),
            ("dose", models.CharField(max_length=60)),
            ("via", models.CharField(max_length=40)),
            ("frequencia", models.CharField(max_length=60)),
            ("duracao", models.CharField(blank=True, max_length=40)),
            ("dispensado", models.BooleanField(default=False)),
            ("prescrito_em", models.DateTimeField(auto_now_add=True)),
            ("ia_aprovada", models.BooleanField(blank=True, null=True)),
            ("ia_observacao", models.CharField(blank=True, max_length=300)),
        ], options={"ordering": ["-prescrito_em"]}),

        migrations.CreateModel(name="BlocoCirurgico", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bloco_cirurgico_agendas", to="api.empresa")),
            ("prontuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.prontuariohospitalar")),
            ("paciente_nome", models.CharField(max_length=160)),
            ("tipo_cirurgia", models.CharField(max_length=200)),
            ("cid10", models.CharField(blank=True, max_length=10)),
            ("cbhpm", models.CharField(blank=True, max_length=20)),
            ("cirurgiao", models.CharField(max_length=120)),
            ("anestesista", models.CharField(blank=True, max_length=120)),
            ("sala", models.CharField(blank=True, max_length=40)),
            ("data_hora", models.DateTimeField()),
            ("duracao_prevista_min", models.PositiveSmallIntegerField(default=60)),
            ("situacao", models.CharField(choices=[("agendada","Agendada"),("em_andamento","Em andamento"),("concluida","Concluída"),("cancelada","Cancelada"),("suspensa","Suspensa")], default="agendada", max_length=20)),
            ("relatorio_cirurgico", models.TextField(blank=True)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["-data_hora"]}),

        migrations.CreateModel(name="FarmaciaHospitalarItem", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="farmacia_hospitalar", to="api.empresa")),
            ("descricao", models.CharField(max_length=200)),
            ("codigo_interno", models.CharField(blank=True, max_length=60)),
            ("apresentacao", models.CharField(blank=True, max_length=80)),
            ("principio_ativo", models.CharField(blank=True, max_length=120)),
            ("classe_terapeutica", models.CharField(blank=True, max_length=80)),
            ("controlado", models.BooleanField(default=False)),
            ("estoque_atual", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ("estoque_minimo", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ("unidade", models.CharField(default="un", max_length=20)),
            ("atualizado_em", models.DateTimeField(auto_now=True)),
        ], options={"ordering": ["descricao"]}),

        migrations.CreateModel(name="ExameLIS", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="exames_lis", to="api.empresa")),
            ("prontuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.prontuariohospitalar")),
            ("paciente_nome", models.CharField(max_length=160)),
            ("tipo_exame", models.CharField(max_length=120)),
            ("codigo_tuss", models.CharField(blank=True, max_length=20)),
            ("solicitante", models.CharField(max_length=120)),
            ("status", models.CharField(choices=[("solicitado","Solicitado"),("coletado","Coletado"),("em_analise","Em análise"),("resultado","Resultado disponível"),("entregue","Entregue")], default="solicitado", max_length=20)),
            ("resultado", models.TextField(blank=True)),
            ("valores_referencia", models.TextField(blank=True)),
            ("solicitado_em", models.DateTimeField(auto_now_add=True)),
            ("resultado_em", models.DateTimeField(blank=True, null=True)),
        ], options={"ordering": ["-solicitado_em"]}),

        migrations.CreateModel(name="ExameRIS", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="exames_ris", to="api.empresa")),
            ("prontuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.prontuariohospitalar")),
            ("paciente_nome", models.CharField(max_length=160)),
            ("modalidade", models.CharField(choices=[("rx","Raio-X"),("us","Ultrassom"),("tc","Tomografia"),("rm","Ressonância"),("mg","Mamografia"),("ec","Ecocardiograma"),("out","Outro")], default="rx", max_length=10)),
            ("regiao_anatomica", models.CharField(max_length=100)),
            ("solicitante", models.CharField(max_length=120)),
            ("laudo", models.TextField(blank=True)),
            ("imagem_url", models.URLField(blank=True)),
            ("laudado_em", models.DateTimeField(blank=True, null=True)),
            ("solicitado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["-solicitado_em"]}),

        migrations.CreateModel(name="GuiaTISS", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="guias_tiss", to="api.empresa")),
            ("numero_guia", models.CharField(blank=True, max_length=60)),
            ("tipo", models.CharField(choices=[("consulta","Consulta"),("sadt","SADT"),("internacao","Internação"),("sp_sadt","SP/SADT"),("resumo","Resumo de Internação")], default="consulta", max_length=20)),
            ("operadora_codigo", models.CharField(blank=True, max_length=30)),
            ("operadora_nome", models.CharField(blank=True, max_length=120)),
            ("beneficiario_nome", models.CharField(max_length=160)),
            ("beneficiario_carteirinha", models.CharField(blank=True, max_length=40)),
            ("cid10", models.CharField(blank=True, max_length=10)),
            ("procedimentos", models.JSONField(default=list)),
            ("valor_apresentado", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("valor_aprovado", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("status", models.CharField(choices=[("elaborada","Elaborada"),("enviada","Enviada"),("glosada","Glosada"),("paga","Paga"),("recurso","Em Recurso")], default="elaborada", max_length=20)),
            ("data_autorizacao", models.DateTimeField(blank=True, null=True)),
            ("xml_tiss", models.TextField(blank=True)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["-criado_em"]}),

        # ── GOVERNO ──────────────────────────────────────────────────────────
        migrations.CreateModel(name="ProntuarioCidadao", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prontuarios_cidadao", to="api.empresa")),
            ("cns", models.CharField(blank=True, max_length=18)),
            ("cpf", models.CharField(blank=True, max_length=14)),
            ("nome_completo", models.CharField(max_length=160)),
            ("data_nascimento", models.DateField(blank=True, null=True)),
            ("sexo", models.CharField(choices=[("M","M"),("F","F"),("O","O")], default="M", max_length=1)),
            ("telefone", models.CharField(blank=True, max_length=20)),
            ("unidade_saude", models.CharField(blank=True, max_length=120)),
            ("microarea", models.CharField(blank=True, max_length=20)),
            ("acs_responsavel", models.CharField(blank=True, max_length=120)),
            ("alergias", models.TextField(blank=True)),
            ("condicoes_cronicas", models.TextField(blank=True)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
            ("atualizado_em", models.DateTimeField(auto_now=True)),
        ], options={"ordering": ["nome_completo"]}),

        migrations.CreateModel(name="AtendimentoUBS", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="atendimentos_ubs", to="api.empresa")),
            ("prontuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.prontuariocidadao")),
            ("paciente_nome", models.CharField(max_length=160)),
            ("cns", models.CharField(blank=True, max_length=18)),
            ("profissional", models.CharField(max_length=120)),
            ("cbo", models.CharField(blank=True, max_length=10)),
            ("procedimento_ab", models.CharField(blank=True, max_length=20)),
            ("cid10", models.CharField(blank=True, max_length=10)),
            ("unidade_saude", models.CharField(blank=True, max_length=120)),
            ("turno", models.CharField(choices=[("M","Manhã"),("T","Tarde"),("N","Noite")], default="M", max_length=1)),
            ("data_atendimento", models.DateField()),
            ("texto_evolucao", models.TextField(blank=True)),
            ("enviado_esus", models.BooleanField(default=False)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["-data_atendimento"]}),

        migrations.CreateModel(name="FarmaciaBasicaItem", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="farmacia_basica", to="api.empresa")),
            ("rename_codigo", models.CharField(blank=True, max_length=20)),
            ("descricao", models.CharField(max_length=200)),
            ("apresentacao", models.CharField(blank=True, max_length=80)),
            ("estoque_atual", models.PositiveIntegerField(default=0)),
            ("estoque_minimo", models.PositiveIntegerField(default=0)),
            ("unidade_saude", models.CharField(blank=True, max_length=120)),
            ("atualizado_em", models.DateTimeField(auto_now=True)),
        ], options={"ordering": ["descricao"]}),

        migrations.CreateModel(name="DispensacaoFarmaciaBasica", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dispensacoes_basica", to="api.empresa")),
            ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.farmaciabasicaitem")),
            ("cns_cidadao", models.CharField(blank=True, max_length=18)),
            ("paciente_nome", models.CharField(max_length=160)),
            ("quantidade", models.PositiveIntegerField(default=1)),
            ("profissional", models.CharField(max_length=120)),
            ("receita_numero", models.CharField(blank=True, max_length=40)),
            ("dispensado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["-dispensado_em"]}),

        migrations.CreateModel(name="RegulacaoAssistencial", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="regulacoes", to="api.empresa")),
            ("paciente_nome", models.CharField(max_length=160)),
            ("cns", models.CharField(blank=True, max_length=18)),
            ("tipo", models.CharField(choices=[("consulta_esp","Consulta Especializada"),("exame","Exame"),("internacao","Internação"),("cirurgia","Cirurgia Eletiva")], default="consulta_esp", max_length=20)),
            ("especialidade", models.CharField(blank=True, max_length=120)),
            ("procedimento", models.CharField(blank=True, max_length=200)),
            ("cid10", models.CharField(blank=True, max_length=10)),
            ("unidade_origem", models.CharField(max_length=120)),
            ("unidade_destino", models.CharField(blank=True, max_length=120)),
            ("status", models.CharField(choices=[("aguardando","Aguardando"),("agendado","Agendado"),("realizado","Realizado"),("cancelado","Cancelado")], default="aguardando", max_length=20)),
            ("data_solicitacao", models.DateField(auto_now_add=True)),
            ("data_agendamento", models.DateField(blank=True, null=True)),
            ("prioridade", models.CharField(choices=[("normal","Normal"),("urgente","Urgente"),("emergen","Emergência")], default="normal", max_length=10)),
        ], options={"ordering": ["-data_solicitacao"]}),

        migrations.CreateModel(name="FaturamentoSUSLote", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="faturamentos_sus", to="api.empresa")),
            ("competencia", models.CharField(max_length=6)),
            ("tipo", models.CharField(choices=[("bpa","BPA-C / BPA-I"),("apac","APAC"),("aih","AIH")], default="bpa", max_length=10)),
            ("estabelecimento_cnes", models.CharField(blank=True, max_length=10)),
            ("total_registros", models.PositiveIntegerField(default=0)),
            ("total_aprovado", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ("enviado_cnes", models.BooleanField(default=False)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["-competencia"]}),

        migrations.CreateModel(name="TeleconsultaGoverno", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="teleconsultas_gov", to="api.empresa")),
            ("paciente_nome", models.CharField(max_length=160)),
            ("cns", models.CharField(blank=True, max_length=18)),
            ("profissional", models.CharField(max_length=120)),
            ("especialidade", models.CharField(blank=True, max_length=80)),
            ("data_hora", models.DateTimeField()),
            ("status", models.CharField(choices=[("agendada","Agendada"),("em_curso","Em curso"),("concluida","Concluída"),("cancelada","Cancelada")], default="agendada", max_length=20)),
            ("link_sala", models.URLField(blank=True)),
            ("resumo", models.TextField(blank=True)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["-data_hora"]}),

        migrations.CreateModel(name="RelatorioRAG", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="relatorios_rag", to="api.empresa")),
            ("tipo", models.CharField(choices=[("pas","PAS — Programação Anual"),("rdqa","RDQA — Relatório Quadrimestral"),("rag","RAG — Relatório Anual de Gestão")], default="rag", max_length=10)),
            ("exercicio", models.PositiveSmallIntegerField()),
            ("quadrimestre", models.PositiveSmallIntegerField(blank=True, null=True)),
            ("conteudo", models.JSONField(default=dict)),
            ("enviado_digisus", models.BooleanField(default=False)),
            ("enviado_em", models.DateTimeField(blank=True, null=True)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
            ("atualizado_em", models.DateTimeField(auto_now=True)),
        ], options={"ordering": ["-exercicio", "-quadrimestre"]}),

        migrations.CreateModel(name="LogESUS", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="logs_esus", to="api.empresa")),
            ("ficha_tipo", models.CharField(max_length=60)),
            ("registros_enviados", models.PositiveIntegerField(default=0)),
            ("status", models.CharField(default="pendente", max_length=20)),
            ("resposta_rnds", models.JSONField(blank=True, default=dict)),
            ("enviado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["-enviado_em"]}),

        # ── PLANO DE SAÚDE ───────────────────────────────────────────────────
        migrations.CreateModel(name="CorretoraPlano", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="corretoras", to="api.empresa")),
            ("razao_social", models.CharField(max_length=160)),
            ("cnpj", models.CharField(blank=True, max_length=18)),
            ("susep", models.CharField(blank=True, max_length=20)),
            ("telefone", models.CharField(blank=True, max_length=20)),
            ("email", models.EmailField(blank=True)),
            ("ativa", models.BooleanField(default=True)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["razao_social"]}),

        migrations.CreateModel(name="CorretoraComissao", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("corretora", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comissoes", to="api.corretoraplano")),
            ("competencia", models.CharField(max_length=6)),
            ("vidas_vendidas", models.PositiveIntegerField(default=0)),
            ("receita_base", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ("percentual_comissao", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ("valor_comissao", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ("pago", models.BooleanField(default=False)),
            ("pago_em", models.DateTimeField(blank=True, null=True)),
        ], options={"ordering": ["-competencia"]}),

        migrations.CreateModel(name="RedeCredenciadaPlano", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rede_credenciada_plano", to="api.empresa")),
            ("nome", models.CharField(max_length=160)),
            ("tipo", models.CharField(choices=[("hospital","Hospital"),("clinica","Clínica"),("laboratorio","Laboratório"),("imagem","Centro de Imagem"),("odonto","Odontologia"),("outro","Outro")], default="clinica", max_length=20)),
            ("cnpj", models.CharField(blank=True, max_length=18)),
            ("cnes", models.CharField(blank=True, max_length=10)),
            ("cidade", models.CharField(blank=True, max_length=80)),
            ("uf", models.CharField(blank=True, max_length=2)),
            ("especialidades", models.JSONField(default=list)),
            ("tabela_preco", models.CharField(blank=True, max_length=40)),
            ("ativo", models.BooleanField(default=True)),
            ("contrato_vigente_ate", models.DateField(blank=True, null=True)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["nome"]}),

        migrations.CreateModel(name="DIOPSDeclaracao", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="diops_declaracoes", to="api.empresa")),
            ("trimestre", models.CharField(max_length=6)),
            ("registro_ans", models.CharField(blank=True, max_length=10)),
            ("receita_operacional", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ("despesa_assistencial", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ("despesa_administrativa", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ("resultado_periodo", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ("vidas_ativas", models.PositiveIntegerField(default=0)),
            ("status", models.CharField(choices=[("em_elaboracao","Em elaboração"),("validada","Validada"),("enviada","Enviada ANS"),("retificada","Retificada")], default="em_elaboracao", max_length=20)),
            ("xml_gerado", models.TextField(blank=True)),
            ("enviado_em", models.DateTimeField(blank=True, null=True)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["-trimestre"]}),

        migrations.CreateModel(name="SIBRegistro", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sib_registros", to="api.empresa")),
            ("competencia", models.CharField(max_length=6)),
            ("registro_ans", models.CharField(blank=True, max_length=10)),
            ("vidas_incluidas", models.PositiveIntegerField(default=0)),
            ("vidas_excluidas", models.PositiveIntegerField(default=0)),
            ("vidas_alteradas", models.PositiveIntegerField(default=0)),
            ("total_vidas", models.PositiveIntegerField(default=0)),
            ("enviado", models.BooleanField(default=False)),
            ("enviado_em", models.DateTimeField(blank=True, null=True)),
            ("retorno_ans", models.JSONField(blank=True, default=dict)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["-competencia"]}),

        migrations.CreateModel(name="IAAutorizacaoGuia", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ia_autorizacoes", to="api.empresa")),
            ("numero_guia", models.CharField(max_length=60)),
            ("beneficiario", models.CharField(max_length=160)),
            ("procedimento", models.CharField(max_length=200)),
            ("codigo_tuss", models.CharField(blank=True, max_length=20)),
            ("cid10", models.CharField(blank=True, max_length=10)),
            ("decisao", models.CharField(choices=[("aprovada","Aprovada"),("negada","Negada"),("revisao","Revisão humana")], default="revisao", max_length=20)),
            ("score_confianca", models.FloatField(default=0.0)),
            ("justificativa_ia", models.TextField(blank=True)),
            ("revisada_por", models.CharField(blank=True, max_length=120)),
            ("decisao_final", models.CharField(blank=True, choices=[("aprovada","Aprovada"),("negada","Negada"),("revisao","Revisão humana")], max_length=20, null=True)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
        ], options={"ordering": ["-criado_em"], "verbose_name_plural": "Autorizações IA de guias"}),

        migrations.CreateModel(name="PortalBeneficiarioToken", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("beneficiario", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="portal_token", to="api.beneficiarioplano")),
            ("token", models.CharField(db_index=True, max_length=64, unique=True)),
            ("ativo", models.BooleanField(default=True)),
            ("criado_em", models.DateTimeField(auto_now_add=True)),
            ("expira_em", models.DateField(blank=True, null=True)),
        ], options={"ordering": ["-criado_em"]}),
    ]
