# Generated by Django 5.0.6 on 2026-05-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_missing_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='iaautorizacaoguia',
            name='features_utilizadas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='iaautorizacaoguia',
            name='modelo_versao',
            field=models.CharField(blank=True, default='Ensemble RF+GB SolusCRT v2', max_length=80),
        ),
        migrations.AddField(
            model_name='iaautorizacaoguia',
            name='scores_por_classe',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='esocialeventosst',
            name='tipo_evento',
            field=models.CharField(choices=[('S-2210', 'S-2210 — Comunicação de Acidente do Trabalho'), ('S-2220', 'S-2220 — Monitoramento da Saúde do Trabalhador'), ('S-2230', 'S-2230 — Afastamento Temporário'), ('S-2240', 'S-2240 — Condições Ambientais do Trabalho'), ('S-2245', 'S-2245 — Treinamentos, Capacitações e Exercícios Simulados')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='iaautorizacaoguia',
            index=models.Index(fields=['empresa', 'decisao'], name='api_iaautor_empresa_733844_idx'),
        ),
        migrations.AddIndex(
            model_name='iaautorizacaoguia',
            index=models.Index(fields=['empresa', 'decisao_final'], name='api_iaautor_empresa_582f36_idx'),
        ),
    ]
