# Generated by Django 5.0.6 on 2026-05-31 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_add_s2245_ml_autorizacao_biometria_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredenciaisIntegracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sngpc_usuario', models.CharField(blank=True, default='', help_text='Usuário cadastrado no portal SNGPC ANVISA', max_length=120)),
                ('sngpc_senha_cripto', models.TextField(blank=True, default='', help_text='Senha SNGPC criptografada (Fernet)')),
                ('sngpc_ambiente', models.CharField(choices=[('homologacao', 'Homologação ANVISA'), ('producao', 'Produção ANVISA')], default='homologacao', max_length=20)),
                ('sngpc_ativo', models.BooleanField(default=False)),
                ('sngpc_ultima_transmissao', models.DateTimeField(blank=True, null=True)),
                ('sngpc_ultimo_protocolo', models.CharField(blank=True, default='', max_length=100)),
                ('ans_usuario', models.CharField(blank=True, default='', help_text='Usuário do SIPWeb ANS', max_length=120)),
                ('ans_senha_cripto', models.TextField(blank=True, default='', help_text='Senha SIPWeb ANS criptografada (Fernet)')),
                ('ans_registro', models.CharField(blank=True, default='', help_text='Número de registro da operadora na ANS', max_length=10)),
                ('ans_ambiente', models.CharField(choices=[('homologacao', 'Homologação ANS'), ('producao', 'Produção ANS')], default='homologacao', max_length=20)),
                ('ans_ativo', models.BooleanField(default=False)),
                ('ans_ultima_transmissao', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.CharField(blank=True, default='', max_length=120)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credenciais_integracoes', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Credenciais de Integrações',
                'verbose_name_plural': 'Credenciais de Integrações',
            },
        ),
    ]
