# Generated by Django 5.0.6 on 2026-05-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_add_credenciais_integracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosst',
            name='certificado_senha_cripto',
            field=models.TextField(blank=True, default='', help_text='Senha do certificado A1/A3 (Fernet-encrypted)'),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='rnds_ambiente',
            field=models.CharField(choices=[('homologacao', 'Homologação RNDS'), ('producao', 'Produção RNDS')], default='homologacao', max_length=20),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='rnds_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='rnds_certificado_pfx_b64',
            field=models.TextField(blank=True, default='', help_text='Certificado ICP-Brasil A1/A3 (PKCS#12 base64)'),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='rnds_certificado_senha_cripto',
            field=models.TextField(blank=True, default='', help_text='Senha do certificado RNDS (Fernet)'),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='rnds_cnes',
            field=models.CharField(blank=True, default='', help_text='CNES da unidade de saúde emissora', max_length=7),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='rnds_cpf_gestor',
            field=models.CharField(blank=True, default='', help_text='CPF do gestor municipal habilitado no RNDS', max_length=14),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='rnds_ibge',
            field=models.CharField(blank=True, default='', help_text='Código IBGE do município', max_length=7),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='rnds_ultima_transmissao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='sus_ambiente',
            field=models.CharField(choices=[('homologacao', 'Homologação DATASUS'), ('producao', 'Produção DATASUS')], default='homologacao', max_length=20),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='sus_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='sus_cnes',
            field=models.CharField(blank=True, default='', help_text='CNES do estabelecimento prestador SUS', max_length=7),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='sus_ibge',
            field=models.CharField(blank=True, default='', help_text='Código IBGE do município', max_length=7),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='sus_login_scnes',
            field=models.CharField(blank=True, default='', help_text='Login SCNES/DATASUS do prestador', max_length=120),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='sus_senha_cripto',
            field=models.TextField(blank=True, default='', help_text='Senha SCNES criptografada (Fernet)'),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='sus_uf',
            field=models.CharField(blank=True, default='', help_text='UF do estabelecimento (para rotear endpoint estadual)', max_length=2),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='sus_ultima_transmissao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='sus_ultimo_protocolo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='diopsdeclaracao',
            name='abrangencia_geografica',
            field=models.CharField(choices=[('1', 'Municipal'), ('2', 'Grupo de Municípios'), ('3', 'Estadual'), ('4', 'Grupo de Estados'), ('5', 'Nacional'), ('6', 'Internacional')], default='5', help_text='Abrangência geográfica de comercialização', max_length=1),
        ),
        migrations.AddField(
            model_name='diopsdeclaracao',
            name='codigo_produto_ans',
            field=models.CharField(blank=True, default='', help_text='Código do produto registrado na ANS (FIP5)', max_length=20),
        ),
        migrations.AddField(
            model_name='diopsdeclaracao',
            name='modalidade_assistencial',
            field=models.CharField(choices=[('01', 'Ambulatorial'), ('02', 'Hospitalar com Obstetrícia'), ('03', 'Hospitalar sem Obstetrícia'), ('04', 'Odontológico'), ('05', 'Referência — Ambulatorial + Hospitalar'), ('06', 'Referência — Ambulatorial + Hospitalar + Odontológico')], default='02', help_text='Modalidade assistencial principal do plano', max_length=2),
        ),
        migrations.AddField(
            model_name='diopsdeclaracao',
            name='tipo_operadora',
            field=models.CharField(choices=[('1', 'Medicina de Grupo'), ('2', 'Cooperativa Médica'), ('3', 'Autogestão'), ('4', 'Filantrópica'), ('5', 'Seguradora Especializada'), ('6', 'Administradora de Benefícios')], default='1', help_text='Tipo de operadora conforme ANS — IN 77/2022 FIP1', max_length=1),
        ),
        migrations.AlterField(
            model_name='configuracaosst',
            name='certificado_senha',
            field=models.CharField(blank=True, default='', help_text='Legado — use certificado_senha_cripto', max_length=255),
        ),
    ]
