# Generated by Django 5.0.6 on 2026-05-31 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_diops_real_cert_fernet_sus_rnds'),
    ]

    operations = [
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='nfe_ambiente',
            field=models.CharField(blank=True, choices=[('1', 'Produção'), ('2', 'Homologação')], default='2', max_length=1),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='nfe_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='nfe_certificado_pfx_b64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='nfe_certificado_senha_cripto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='nfe_cnpj_emitente',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='nfe_crt',
            field=models.CharField(blank=True, default='3', help_text='1=Simples Nacional, 3=Regime Normal', max_length=1, verbose_name='Código Regime Tributário'),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='nfe_ie',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='nfe_municipio_ibge',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Código IBGE do município'),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='nfe_serie',
            field=models.CharField(blank=True, default='001', max_length=3),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='nfe_uf',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='nfe_ultima_transmissao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotaFiscalEletronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('serie', models.CharField(default='001', max_length=3)),
                ('modelo', models.CharField(choices=[('55', 'NF-e (Nota Fiscal Eletrônica)'), ('65', 'NFC-e (Nota Fiscal Consumidor)')], default='55', max_length=2)),
                ('chave_acesso', models.CharField(blank=True, max_length=44, unique=True)),
                ('protocolo', models.CharField(blank=True, max_length=20)),
                ('cnpj_emitente', models.CharField(max_length=14)),
                ('nome_emitente', models.CharField(blank=True, max_length=60)),
                ('ie_emitente', models.CharField(blank=True, max_length=20)),
                ('uf_emitente', models.CharField(blank=True, max_length=2)),
                ('cpf_cnpj_destinatario', models.CharField(blank=True, max_length=14)),
                ('nome_destinatario', models.CharField(blank=True, max_length=60)),
                ('email_destinatario', models.CharField(blank=True, max_length=60)),
                ('natureza_operacao', models.CharField(default='VENDA DE PRODUTO', max_length=60)),
                ('cfop', models.CharField(default='5102', max_length=4)),
                ('forma_pagamento', models.CharField(choices=[('01', 'Dinheiro'), ('02', 'Cheque'), ('03', 'Cartão de Crédito'), ('04', 'Cartão de Débito'), ('05', 'Crédito Loja'), ('10', 'Vale Alimentação'), ('11', 'Vale Refeição'), ('12', 'Vale Presente'), ('13', 'Vale Combustível'), ('15', 'Boleto Bancário'), ('90', 'Sem Pagamento'), ('99', 'Outros')], default='99', max_length=2)),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('itens', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('assinada', 'Assinada — aguardando envio'), ('autorizada', 'Autorizada pela SEFAZ'), ('cancelada', 'Cancelada'), ('denegada', 'Denegada pela SEFAZ'), ('erro', 'Erro de transmissão')], default='rascunho', max_length=20)),
                ('ambiente', models.CharField(choices=[('1', 'Produção'), ('2', 'Homologação')], default='2', max_length=1)),
                ('mensagem_sefaz', models.TextField(blank=True)),
                ('xml_assinado', models.TextField(blank=True)),
                ('xml_autorizado', models.TextField(blank=True)),
                ('data_emissao', models.DateTimeField(blank=True, default=None, null=True)),
                ('autorizada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='api.empresa')),
            ],
            options={
                'ordering': ['-data_emissao'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_notafis_empresa_7d5729_idx'), models.Index(fields=['empresa', 'data_emissao'], name='api_notafis_empresa_9e17cb_idx')],
                'unique_together': {('empresa', 'serie', 'numero')},
            },
        ),
    ]
