# Generated by Django 5.0.6 on 2026-06-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_sigtap_caps_sipni_magistral_rnds_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucaoprontuario',
            name='assinado_digitalmente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evolucaoprontuario',
            name='assinado_digitalmente_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evolucaoprontuario',
            name='assinatura_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 do texto assinado (hex)', max_length=128),
        ),
        migrations.AddField(
            model_name='evolucaoprontuario',
            name='assinatura_icp',
            field=models.TextField(blank=True, default='', help_text='Assinatura PKCS#7 / CAdES em base64'),
        ),
        migrations.AddIndex(
            model_name='evolucaoprontuario',
            index=models.Index(fields=['prontuario', 'assinado_digitalmente'], name='api_evoluca_prontua_196594_idx'),
        ),
    ]
