# Generated by Django 5.0.6 on 2026-06-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_hemoterapia_oncologia_tuss_nip_acs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaPlataformaSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, help_text='Saldo total em caixa (R$)', max_digits=14)),
                ('data_referencia', models.DateField(help_text='Data a que se refere o saldo informado')),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caixa da Plataforma SaaS',
                'verbose_name_plural': 'Registros de Caixa da Plataforma SaaS',
                'ordering': ['-data_referencia'],
            },
        ),
    ]
