# Generated by Django 5.0.6 on 2026-06-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_caixa_plataforma'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registrosintoma',
            index=models.Index(fields=['empresa', 'data_registro'], name='regsintoma_emp_data_idx'),
        ),
        migrations.AddIndex(
            model_name='registrosintoma',
            index=models.Index(fields=['empresa', 'estado', 'cidade'], name='regsintoma_emp_geo_idx'),
        ),
        migrations.AddIndex(
            model_name='registrosintoma',
            index=models.Index(fields=['data_registro'], name='regsintoma_data_idx'),
        ),
    ]
