# Generated by Django 5.0.6 on 2026-06-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_escalada_temporal_epidemica'),
    ]

    operations = [
        migrations.AddField(
            model_name='donosaas',
            name='papel',
            field=models.CharField(choices=[('admin', 'Administrador'), ('financeiro', 'Financeiro'), ('suporte', 'Suporte'), ('leitura', 'Leitura')], default='admin', max_length=20),
        ),
    ]
