# Generated by Django 5.0.6 on 2026-06-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_donosaas_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturadocumentosst',
            name='finalidade_assinatura',
            field=models.CharField(blank=True, choices=[('ciencia_trabalhador', 'Ciência do trabalhador'), ('validacao_tecnica', 'Validação técnica'), ('validacao_empresa', 'Validação da empresa'), ('aceite_documento', 'Aceite eletrônico do documento')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='assinaturadocumentosst',
            name='papel_signatario',
            field=models.CharField(blank=True, choices=[('funcionario', 'Funcionário / Trabalhador'), ('responsavel_tecnico', 'Responsável técnico'), ('representante_empresa', 'Representante legal da empresa'), ('sesmt_rh', 'SESMT / RH'), ('outro', 'Outro signatário')], default='', max_length=40),
        ),
    ]
