# Generated by Django 5.0.6 on 2026-06-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_assinaturadocumentosst_finalidade_assinatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaofuncionario',
            name='tipo',
            field=models.CharField(choices=[('aso', 'ASO'), ('exame', 'Exame'), ('treinamento', 'Treinamento'), ('assinatura_sst', 'Assinatura SST'), ('geral', 'Geral')], default='geral', max_length=20),
        ),
    ]
