# Generated by Django 5.0.6 on 2026-06-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_registrosintoma_sudorese'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresausuario',
            name='perfil',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador'), ('gestor', 'Gestor / Diretor'), ('medico', 'Médico do Trabalho'), ('tecnico_sesmt', 'Técnico de Segurança (SESMT)'), ('rh', 'RH / Departamento Pessoal'), ('ti', 'TI / Administrador de Sistemas'), ('auxiliar', 'Auxiliar Administrativo')], max_length=20, null=True),
        ),
    ]
