# Generated by Django 5.0.6 on 2026-06-20 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_empresa_cortesia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixaplataformasaas',
            options={'ordering': ['-data_referencia'], 'verbose_name': 'Caixa da Plataforma Healthtech', 'verbose_name_plural': 'Registros de Caixa da Plataforma Healthtech'},
        ),
        migrations.CreateModel(
            name='InstanciaDicom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='dicom/%Y/%m/')),
                ('sop_instance_uid', models.CharField(blank=True, max_length=128)),
                ('series_instance_uid', models.CharField(blank=True, max_length=128)),
                ('study_instance_uid', models.CharField(blank=True, max_length=128)),
                ('modalidade_dicom', models.CharField(blank=True, max_length=16)),
                ('numero_instancia', models.PositiveIntegerField(default=1)),
                ('tamanho_bytes', models.PositiveIntegerField(default=0)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias_dicom', to='api.exameris')),
            ],
            options={
                'ordering': ['numero_instancia', 'enviado_em'],
            },
        ),
    ]
