# Generated by Django 5.0.6 on 2026-06-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_instancia_dicom'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoexame',
            name='arquivo_laudo',
            field=models.FileField(blank=True, help_text='PDF ou imagem do laudo, armazenado no sistema', null=True, upload_to='laudos_lis/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='resultadoexame',
            name='url_imagem',
            field=models.URLField(blank=True, default='', help_text='Link externo do laudo (legado/PACS de terceiros)'),
        ),
    ]
