# Generated by Django 5.0.6 on 2026-06-21 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_resultado_exame_arquivo_laudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoEnfermagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico_enfermagem', models.TextField(blank=True, default='', help_text='Coleta de dados / anamnese de enfermagem')),
                ('exame_fisico', models.JSONField(default=dict, help_text='{"neurologico":"...","respiratorio":"...","cardiovascular":"...","pele_mucosas":"...","eliminacoes":"..."}')),
                ('escala_braden', models.PositiveSmallIntegerField(blank=True, help_text='Risco de lesão por pressão: 6-23 (quanto menor, maior risco)', null=True)),
                ('escala_morse', models.PositiveSmallIntegerField(blank=True, help_text='Risco de queda: 0-125 (quanto maior, maior risco)', null=True)),
                ('diagnosticos_enfermagem', models.JSONField(default=list, help_text='[{"diagnostico":"Risco de queda","dominio":"Segurança/Proteção"}]')),
                ('plano_cuidados', models.JSONField(default=list, help_text='[{"intervencao":"Grades elevadas","meta":"Sem episódios de queda","prazo":"Durante internação"}]')),
                ('responsavel', models.CharField(blank=True, default='', max_length=200)),
                ('coren', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('reavaliada', 'Reavaliada'), ('encerrada', 'Encerrada')], default='ativa', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_enfermagem', to='api.pacienteinternado')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['paciente', 'status'], name='avalenferm_pac_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoFisioterapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixa_principal', models.TextField(blank=True, default='')),
                ('amplitude_movimento', models.JSONField(default=dict, help_text='{"ombro_d":"180°","joelho_e":"90°"}')),
                ('forca_muscular', models.JSONField(default=dict, help_text='Escala MRC 0-5 por grupo muscular: {"MSD":4,"MSE":4,"MID":3,"MIE":3}')),
                ('escala_dor_eva', models.PositiveSmallIntegerField(blank=True, help_text='Escala visual analógica de dor: 0-10', null=True)),
                ('capacidade_funcional', models.CharField(blank=True, default='', help_text='Ex: dependente total, deambula com auxílio, independente', max_length=200)),
                ('diagnostico_fisioterapeutico', models.TextField(blank=True, default='')),
                ('plano_terapeutico', models.JSONField(default=list, help_text='[{"conduta":"Cinesioterapia respiratória","frequencia":"2x/dia"}]')),
                ('objetivos', models.TextField(blank=True, default='')),
                ('responsavel', models.CharField(blank=True, default='', max_length=200)),
                ('crefito', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('reavaliada', 'Reavaliada'), ('encerrada', 'Encerrada')], default='ativa', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_fisioterapia', to='api.pacienteinternado')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['paciente', 'status'], name='avalfisio_pac_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('altura_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado: peso / (altura_m²)', max_digits=5, null=True)),
                ('circunferencias', models.JSONField(default=dict, help_text='{"braquial_cm":28,"panturrilha_cm":32}')),
                ('diagnostico_nutricional', models.CharField(blank=True, default='', help_text='Ex: desnutrição moderada, eutrofia, obesidade grau I', max_length=200)),
                ('via_alimentacao', models.CharField(choices=[('oral', 'Via oral'), ('enteral', 'Via enteral (sonda)'), ('parenteral', 'Via parenteral'), ('oral_enteral', 'Oral + enteral')], default='oral', max_length=20)),
                ('necessidade_calorica_kcal', models.PositiveIntegerField(blank=True, null=True)),
                ('necessidade_proteica_g', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('restricoes_alergias', models.TextField(blank=True, default='')),
                ('plano_dietetico', models.JSONField(default=list, help_text='[{"tipo_dieta":"Branda hipossódica","horario":"6 refeições/dia"}]')),
                ('responsavel', models.CharField(blank=True, default='', max_length=200)),
                ('crn', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('reavaliada', 'Reavaliada'), ('encerrada', 'Encerrada')], default='ativa', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_nutricionais', to='api.pacienteinternado')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['paciente', 'status'], name='avalnutri_pac_status_idx')],
            },
        ),
    ]
