# Generated by Django 5.0.6 on 2026-06-21 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_equipe_multiprofissional'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitanteHospitalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('documento', models.CharField(blank=True, default='', help_text='RG ou CPF', max_length=30)),
                ('parentesco', models.CharField(blank=True, default='', help_text='Ex: filho(a), cônjuge, amigo(a)', max_length=100)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('dentro', 'Dentro do hospital'), ('saiu', 'Saiu')], default='dentro', max_length=10)),
                ('registrado_por', models.CharField(blank=True, default='', help_text='Funcionário da portaria/recepção que registrou', max_length=200)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitantes', to='api.pacienteinternado')),
            ],
            options={
                'ordering': ['-entrada'],
                'indexes': [models.Index(fields=['paciente', 'status'], name='visitante_pac_status_idx')],
            },
        ),
    ]
