# Generated by Django 5.0.6 on 2026-06-21 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_controle_visitantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracaoObito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_do', models.CharField(blank=True, default='', help_text='Numeração oficial da DO, se já emitida em papel/sistema do cartório', max_length=30)),
                ('data_obito', models.DateTimeField()),
                ('local_obito', models.CharField(blank=True, default='', help_text='Ex: Hospital X, leito 12', max_length=200)),
                ('tipo_morte', models.CharField(choices=[('natural', 'Morte natural'), ('nao_natural', 'Morte não natural (causas externas)')], default='natural', max_length=20)),
                ('causa_imediata_cid', models.CharField(blank=True, default='', max_length=10)),
                ('causa_imediata_descricao', models.TextField(blank=True, default='')),
                ('causa_intermediaria_cid', models.CharField(blank=True, default='', max_length=10)),
                ('causa_intermediaria_descricao', models.TextField(blank=True, default='')),
                ('causa_basica_cid', models.CharField(blank=True, default='', max_length=10)),
                ('causa_basica_descricao', models.TextField(blank=True, default='')),
                ('causas_contribuintes', models.TextField(blank=True, default='', help_text='Causas que contribuíram mas não entraram na cadeia causal direta')),
                ('necropsia_realizada', models.BooleanField(default=False)),
                ('removido_svo_iml', models.BooleanField(default=False, help_text='Removido para Serviço de Verificação de Óbito / Instituto Médico Legal')),
                ('medico_atestante', models.CharField(blank=True, default='', max_length=200)),
                ('medico_crm', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('emitida', 'Emitida'), ('retificada', 'Retificada')], default='emitida', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('emitida_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaracoes_obito', to='api.pacienteinternado')),
            ],
            options={
                'ordering': ['-emitida_em'],
                'indexes': [models.Index(fields=['paciente'], name='declobito_paciente_idx')],
            },
        ),
    ]
