# Generated by Django 5.0.6 on 2026-06-21 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_declaracao_obito'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, default='', help_text='Ex: monitor multiparamétrico, respirador, bomba de infusão', max_length=100)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=100)),
                ('fabricante', models.CharField(blank=True, default='', max_length=120)),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('setor_localizacao', models.CharField(blank=True, default='', help_text='Ex: UTI, Centro Cirúrgico, Enfermaria 2', max_length=120)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('criticidade', models.PositiveSmallIntegerField(default=3, help_text='1=baixa, 5=crítica (suporte à vida)')),
                ('status', models.CharField(choices=[('operacional', 'Operacional'), ('manutencao', 'Em manutenção'), ('inativo', 'Inativo/baixado')], default='operacional', max_length=20)),
                ('ultima_calibracao_em', models.DateField(blank=True, null=True)),
                ('proxima_calibracao_em', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos_medicos', to='api.empresa')),
                ('leito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_medicos', to='api.leitohospitalar')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ManutencaoEquipamentoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('calibracao', 'Calibração')], default='preventiva', max_length=20)),
                ('descricao_problema', models.TextField(blank=True, default='')),
                ('descricao_servico', models.TextField(blank=True, default='', help_text='O que foi feito/constatado')),
                ('responsavel_tecnico', models.CharField(blank=True, default='', max_length=200)),
                ('empresa_terceirizada', models.CharField(blank=True, default='', help_text='Se a manutenção foi feita por empresa externa', max_length=200)),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_manutencao', to='api.equipamentomedico')),
            ],
            options={
                'ordering': ['-aberta_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroLimpezaLeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sujo', 'Sujo / aguardando limpeza'), ('em_limpeza', 'Em limpeza'), ('limpo', 'Limpo / liberado'), ('interditado', 'Interditado')], default='sujo', max_length=20)),
                ('tipo_limpeza', models.CharField(choices=[('concorrente', 'Concorrente (rotina diária)'), ('terminal', 'Terminal (após alta/óbito/transferência)'), ('interdicao', 'Interdição (surto/contaminação)')], default='concorrente', max_length=20)),
                ('responsavel', models.CharField(blank=True, default='', max_length=200)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('leito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_limpeza', to='api.leitohospitalar')),
            ],
            options={
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroRouparia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(blank=True, default='', help_text='Usado quando não é por leito específico, ex: Centro Cirúrgico', max_length=120)),
                ('tipo', models.CharField(choices=[('entrega_limpa', 'Entrega de roupa limpa'), ('coleta_sujo', 'Coleta de roupa suja')], default='entrega_limpa', max_length=20)),
                ('quantidade_pecas', models.PositiveIntegerField(default=0)),
                ('responsavel', models.CharField(blank=True, default='', max_length=200)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_rouparia', to='api.empresa')),
                ('leito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_rouparia', to='api.leitohospitalar')),
            ],
            options={
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='DispensacaoDoseUnitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medicamento', models.CharField(max_length=200)),
                ('dose', models.CharField(blank=True, default='', max_length=100)),
                ('leito_numero', models.CharField(blank=True, default='', help_text='Denormalizado no momento da dispensação, para rastreio mesmo após troca de leito', max_length=20)),
                ('horario_previsto', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aguardando_preparo', 'Aguardando preparo'), ('preparada', 'Preparada/conferida'), ('dispensada_leito', 'Dispensada para o leito'), ('devolvida', 'Devolvida à farmácia')], default='aguardando_preparo', max_length=20)),
                ('farmaceutico_responsavel', models.CharField(blank=True, default='', max_length=200)),
                ('crf', models.CharField(blank=True, default='', help_text='Conselho Regional de Farmácia', max_length=30)),
                ('preparada_em', models.DateTimeField(blank=True, null=True)),
                ('dispensada_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensacoes_dose_unitaria', to='api.pacienteinternado')),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensacoes_dose_unitaria', to='api.prescricaohospitalar')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['paciente', 'status'], name='doseunit_pac_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='equipamentomedico',
            index=models.Index(fields=['empresa', 'status'], name='equipmed_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='manutencaoequipamentomedico',
            index=models.Index(fields=['equipamento', 'status'], name='manutencaoeq_eq_status_idx'),
        ),
        migrations.AddIndex(
            model_name='registrolimpezaleito',
            index=models.Index(fields=['leito', 'status'], name='limpleito_leito_status_idx'),
        ),
    ]
