# Generated by Django 5.0.6 on 2026-06-21 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_manutencao_dose_unitaria_limpeza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodelivery',
            name='id_externo',
            field=models.CharField(blank=True, default='', help_text='ID do pedido na plataforma de origem (ex: orderId do iFood)', max_length=80),
        ),
        migrations.CreateModel(
            name='IntegracaoIfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(blank=True, default='', help_text='ID do estabelecimento no iFood', max_length=80)),
                ('client_id', models.CharField(blank=True, default='', max_length=120)),
                ('client_secret', models.CharField(blank=True, default='', max_length=200)),
                ('webhook_signature_key', models.CharField(blank=True, default='', help_text='Usado para validar a assinatura dos webhooks recebidos do iFood', max_length=200)),
                ('ativo', models.BooleanField(default=False)),
                ('conectado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integracao_ifood', to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='VisitaCombateEndemias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_nome', models.CharField(help_text='Agente de Combate a Endemias (ACE)', max_length=160)),
                ('data_visita', models.DateField()),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('bairro', models.CharField(blank=True, default='', max_length=120)),
                ('municipio_ibge', models.CharField(blank=True, default='', max_length=7)),
                ('tipo_imovel', models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('terreno_baldio', 'Terreno Baldio'), ('ponto_estrategico', 'Ponto Estratégico (PE)'), ('outro', 'Outro')], default='residencial', max_length=20)),
                ('status_visita', models.CharField(choices=[('realizada', 'Realizada'), ('imovel_fechado', 'Imóvel fechado'), ('imovel_recusado', 'Morador recusou'), ('imovel_ausente', 'Morador ausente')], default='realizada', max_length=20)),
                ('depositos_inspecionados', models.PositiveSmallIntegerField(default=0)),
                ('foco_encontrado', models.BooleanField(default=False)),
                ('tipo_criadouro', models.CharField(blank=True, choices=[('a1', "A1 — Caixa d'água/depósito elevado"), ('a2', 'A2 — Tanque/depósito de reservação'), ('b', 'B — Reservatório ao nível do solo'), ('c', 'C — Recipientes móveis (vasos, pratos, garrafas)'), ('d1', 'D1 — Pneus e sucatas'), ('d2', 'D2 — Depósitos naturais (bromélias, troncos, axilas de folha)'), ('e', 'E — Outros depósitos')], default='', max_length=10)),
                ('acao_realizada', models.CharField(blank=True, choices=[('tratamento_focal', 'Tratamento focal (larvicida)'), ('tratamento_perifocal', 'Tratamento perifocal (adulticida)'), ('eliminacao_mecanica', 'Eliminação mecânica do depósito'), ('orientacao', 'Orientação ao morador'), ('nenhuma', 'Nenhuma ação necessária')], default='', max_length=30)),
                ('larvas_coletadas', models.BooleanField(default=False, help_text='Amostra coletada para identificação em laboratório')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_endemias', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Visita de Combate a Endemias',
                'verbose_name_plural': 'Visitas de Combate a Endemias',
                'ordering': ['-data_visita'],
                'indexes': [models.Index(fields=['empresa', 'data_visita'], name='api_visitac_empresa_3c5167_idx'), models.Index(fields=['empresa', 'foco_encontrado'], name='api_visitac_empresa_c1a901_idx'), models.Index(fields=['empresa', 'bairro'], name='api_visitac_empresa_6975e3_idx')],
            },
        ),
    ]
