# Generated by Django 5.0.6 on 2026-06-21 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_endemias_e_ifood'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstabelecimentoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=200)),
                ('cnpj_cpf', models.CharField(blank=True, default='', max_length=18)),
                ('tipo', models.CharField(choices=[('alimentos', 'Estabelecimento de Alimentos (restaurante, lanchonete, padaria)'), ('estetica', 'Estética/Salão de Beleza'), ('saude', 'Serviço de Saúde (clínica, consultório, laboratório)'), ('farmacia', 'Farmácia/Drogaria'), ('industria', 'Indústria/Manipulação'), ('outro', 'Outro')], default='alimentos', max_length=20)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('bairro', models.CharField(blank=True, default='', max_length=120)),
                ('responsavel_tecnico', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('regular', 'Regular'), ('pendente', 'Pendente de regularização'), ('interditado', 'Interditado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentos_sanitarios', to='api.empresa')),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='AlvaraSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('vencido', 'Vencido'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('responsavel_emissao', models.CharField(blank=True, default='', max_length=200)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alvaras', to='api.estabelecimentosanitario')),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='InspecaoSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_nome', models.CharField(max_length=200)),
                ('fiscal_matricula', models.CharField(blank=True, default='', max_length=40)),
                ('data_inspecao', models.DateField()),
                ('itens_verificados', models.JSONField(default=list, help_text='[{"item":"Higiene da cozinha","conforme":true}]')),
                ('resultado', models.CharField(choices=[('conforme', 'Conforme'), ('nao_conforme', 'Não Conforme — notificado'), ('auto_infracao', 'Auto de Infração'), ('interdicao', 'Interdição')], default='conforme', max_length=20)),
                ('numero_auto_infracao', models.CharField(blank=True, default='', max_length=40)),
                ('valor_multa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prazo_regularizacao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes', to='api.estabelecimentosanitario')),
            ],
            options={
                'ordering': ['-data_inspecao'],
            },
        ),
        migrations.AddIndex(
            model_name='estabelecimentosanitario',
            index=models.Index(fields=['empresa', 'status'], name='estabsan_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inspecaosanitaria',
            index=models.Index(fields=['estabelecimento', 'resultado'], name='inspsan_estab_result_idx'),
        ),
    ]
