# Generated by Django 5.0.6 on 2026-06-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_vigilancia_sanitaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='esocialeventosst',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esocialeventosst',
            name='aprovado_por',
            field=models.CharField(blank=True, default='', help_text='Responsável que validou o evento antes da transmissão ao eSocial', max_length=200),
        ),
        migrations.AlterField(
            model_name='esocialeventosst',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('aprovado', 'Aprovado — pronto para envio'), ('enviado', 'Enviado'), ('transmitido', 'Transmitido com Sucesso'), ('erro', 'Erro'), ('retificacao', 'Em Retificação')], default='pendente', max_length=20),
        ),
    ]
