# Generated by Django 5.0.6 on 2026-06-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_esocial_aprovacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='internacaohospital',
            name='paciente_interno_sync',
            field=models.ForeignKey(blank=True, help_text='Sincronização interna com o cadastro moderno de paciente — não exposta na UI', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pacienteinternado'),
        ),
        migrations.AlterField(
            model_name='pacienteinternado',
            name='status',
            field=models.CharField(choices=[('cadastrado', 'Cadastrado — ainda não internado'), ('internado', 'Internado'), ('alta', 'Alta'), ('transferido', 'Transferido'), ('obito', 'Óbito')], default='internado', max_length=20),
        ),
    ]
