# Generated by Django 5.0.6 on 2026-06-22 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_fix_paciente_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfarmacia',
            name='unidade_fisica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_farmacia', to='api.empresaunidade'),
        ),
    ]
