# Generated by Django 5.0.6 on 2026-06-23 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_farmacia_unidade_fisica'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenhaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('prefixo', models.CharField(default='N', max_length=2)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('prioritario', 'Prioritário')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('chamado', 'Chamado'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('guiche', models.CharField(blank=True, default='', max_length=40)),
                ('paciente_nome', models.CharField(blank=True, default='', max_length=160)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado_em', models.DateTimeField(blank=True, null=True)),
                ('atendido_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senhas_atendimento', to='api.empresa')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senhas_atendimento', to='api.empresaunidade')),
            ],
            options={
                'verbose_name': 'Senha de Atendimento',
                'verbose_name_plural': 'Senhas de Atendimento',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_senhaat_empresa_fbbb45_idx'), models.Index(fields=['empresa', 'unidade', 'criado_em'], name='api_senhaat_empresa_dd9c37_idx')],
            },
        ),
    ]
