# Generated by Django 5.0.6 on 2026-06-23 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_senha_atendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoGED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('prontuario', 'Prontuário'), ('administrativo', 'Administrativo'), ('contrato', 'Contrato'), ('oficio', 'Ofício'), ('laudo', 'Laudo'), ('licitacao', 'Licitação'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('arquivo', models.FileField(upload_to='ged/%Y/%m/')),
                ('nome_arquivo_original', models.CharField(blank=True, default='', max_length=255)),
                ('tamanho_bytes', models.PositiveIntegerField(default=0)),
                ('paciente_nome', models.CharField(blank=True, default='', max_length=160)),
                ('paciente_cpf', models.CharField(blank=True, default='', max_length=11)),
                ('numero_processo', models.CharField(blank=True, default='', max_length=60)),
                ('tags', models.CharField(blank=True, default='', help_text='Palavras-chave separadas por vírgula', max_length=255)),
                ('confidencial', models.BooleanField(default=False)),
                ('criado_por', models.CharField(blank=True, default='', max_length=160)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_ged', to='api.empresa')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_ged', to='api.empresaunidade')),
            ],
            options={
                'verbose_name': 'Documento GED',
                'verbose_name_plural': 'Documentos GED',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'categoria'], name='api_documen_empresa_a03384_idx'), models.Index(fields=['empresa', 'numero_processo'], name='api_documen_empresa_cd300f_idx'), models.Index(fields=['paciente_cpf'], name='api_documen_pacient_0cbcdb_idx')],
            },
        ),
    ]
