# Generated by Django 5.0.6 on 2026-06-23 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_documento_ged'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoTFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('tipo', models.CharField(choices=[('ambulancia', 'Ambulância'), ('van', 'Van'), ('carro', 'Carro'), ('micro_onibus', 'Micro-ônibus')], default='van', max_length=20)),
                ('capacidade', models.PositiveIntegerField(default=1)),
                ('motorista_nome', models.CharField(blank=True, default='', max_length=160)),
                ('motorista_cnh', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_viagem', 'Em Viagem'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20)),
                ('km_atual', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos_tfd', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Veículo TFD',
                'verbose_name_plural': 'Veículos TFD',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='ViagemTFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(max_length=160)),
                ('paciente_cpf', models.CharField(blank=True, default='', max_length=11)),
                ('paciente_cns', models.CharField(blank=True, default='', max_length=18)),
                ('acompanhante_nome', models.CharField(blank=True, default='', max_length=160)),
                ('destino_cidade', models.CharField(max_length=120)),
                ('destino_estabelecimento', models.CharField(blank=True, default='', max_length=200)),
                ('motivo', models.TextField(blank=True, default='')),
                ('data_viagem', models.DateTimeField()),
                ('data_retorno_prevista', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
                ('km_percorrido', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_tfd', to='api.empresa')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens', to='api.veiculotfd')),
            ],
            options={
                'verbose_name': 'Viagem TFD',
                'verbose_name_plural': 'Viagens TFD',
                'ordering': ['data_viagem'],
            },
        ),
        migrations.AddIndex(
            model_name='veiculotfd',
            index=models.Index(fields=['empresa', 'status'], name='api_veiculo_empresa_8f8e63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='veiculotfd',
            unique_together={('empresa', 'placa')},
        ),
        migrations.AddIndex(
            model_name='viagemtfd',
            index=models.Index(fields=['empresa', 'status'], name='api_viagemt_empresa_172614_idx'),
        ),
        migrations.AddIndex(
            model_name='viagemtfd',
            index=models.Index(fields=['empresa', 'data_viagem'], name='api_viagemt_empresa_11ac0c_idx'),
        ),
        migrations.AddIndex(
            model_name='viagemtfd',
            index=models.Index(fields=['paciente_cpf'], name='api_viagemt_pacient_ac6adb_idx'),
        ),
    ]
