# Generated by Django 5.0.6 on 2026-06-23 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_veiculo_viagem_tfd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('principio_ativo', models.CharField(blank=True, default='', max_length=200)),
                ('grupo', models.CharField(blank=True, default='', max_length=100)),
                ('subgrupo', models.CharField(blank=True, default='', max_length=100)),
                ('forma_apresentacao', models.CharField(blank=True, default='', max_length=100)),
                ('unidade_medida', models.CharField(default='unidade', max_length=40)),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=60)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_almoxarifado', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Produto de Almoxarifado',
                'verbose_name_plural': 'Produtos de Almoxarifado',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LoteAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('data_validade', models.DateField()),
                ('quantidade_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fornecedor', models.CharField(blank=True, default='', max_length=200)),
                ('bloqueado', models.BooleanField(default=False, help_text='recall, suspeita de desvio')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_almoxarifado', to='api.empresa')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_almoxarifado', to='api.empresaunidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='api.produtoalmoxarifado')),
            ],
            options={
                'verbose_name': 'Lote de Almoxarifado',
                'verbose_name_plural': 'Lotes de Almoxarifado',
                'ordering': ['data_validade'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída / Dispensação'), ('ajuste', 'Ajuste de Saldo'), ('transferencia_saida', 'Transferência — Saída'), ('transferencia_entrada', 'Transferência — Entrada')], max_length=24)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('concluida', 'Concluída'), ('pendente', 'Pendente de Aceite'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada / Devolvida')], default='concluida', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_almoxarifado', to='api.empresa')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='api.lotealmoxarifado')),
                ('unidade_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recebidas', to='api.empresaunidade')),
            ],
            options={
                'verbose_name': 'Movimentação de Almoxarifado',
                'verbose_name_plural': 'Movimentações de Almoxarifado',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'tipo'], name='api_movimen_empresa_f70188_idx'), models.Index(fields=['empresa', 'status'], name='api_movimen_empresa_d5fa30_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='produtoalmoxarifado',
            index=models.Index(fields=['empresa', 'grupo'], name='api_produto_empresa_4029a4_idx'),
        ),
        migrations.AddIndex(
            model_name='lotealmoxarifado',
            index=models.Index(fields=['empresa', 'produto'], name='api_lotealm_empresa_1b8a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='lotealmoxarifado',
            index=models.Index(fields=['unidade', 'produto', 'data_validade'], name='api_lotealm_unidade_6eb9bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lotealmoxarifado',
            unique_together={('unidade', 'produto', 'numero_lote')},
        ),
    ]
