# Generated by Django 5.0.6 on 2026-06-23 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_almoxarifado_governo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameLaboratorialCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('sigla', models.CharField(blank=True, default='', max_length=20)),
                ('metodo_analise', models.CharField(blank=True, default='', max_length=120)),
                ('tipo_amostra', models.CharField(blank=True, default='', max_length=60)),
                ('valor_referencia_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_referencia_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_referencia_texto', models.CharField(blank=True, default='', help_text='Para exames não numéricos (ex.: Negativo/Positivo)', max_length=200)),
                ('unidade_medida', models.CharField(blank=True, default='', max_length=30)),
                ('prazo_entrega_dias', models.PositiveIntegerField(default=2)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_exames_lab', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Exame de Laboratório (Catálogo)',
                'verbose_name_plural': 'Exames de Laboratório (Catálogo)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoExameLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=20, unique=True)),
                ('paciente_nome', models.CharField(max_length=160)),
                ('paciente_cpf', models.CharField(blank=True, default='', max_length=11)),
                ('paciente_cns', models.CharField(blank=True, default='', max_length=18)),
                ('profissional_solicitante', models.CharField(blank=True, default='', max_length=160)),
                ('urgente', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('aguardando_coleta', 'Aguardando Coleta'), ('coletado', 'Coletado'), ('em_analise', 'Em Análise'), ('liberado', 'Liberado'), ('cancelado', 'Cancelado')], default='aguardando_coleta', max_length=20)),
                ('data_agendamento', models.DateTimeField(blank=True, null=True)),
                ('data_coleta', models.DateTimeField(blank=True, null=True)),
                ('data_entrega_prevista', models.DateField(blank=True, null=True)),
                ('valor_resultado', models.CharField(blank=True, default='', max_length=200)),
                ('fora_referencia', models.BooleanField(default=False)),
                ('liberado_por', models.CharField(blank=True, default='', max_length=160)),
                ('liberado_em', models.DateTimeField(blank=True, null=True)),
                ('retificado_por', models.CharField(blank=True, default='', max_length=160)),
                ('retificado_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_exame_lab', to='api.empresa')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='api.examelaboratorialcatalogo')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_exame_lab', to='api.empresaunidade')),
            ],
            options={
                'verbose_name': 'Solicitação de Exame Laboratorial',
                'verbose_name_plural': 'Solicitações de Exame Laboratorial',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='examelaboratorialcatalogo',
            index=models.Index(fields=['empresa', 'ativo'], name='api_examela_empresa_f7cbda_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaoexamelab',
            index=models.Index(fields=['empresa', 'status'], name='api_solicit_empresa_620a28_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaoexamelab',
            index=models.Index(fields=['paciente_cpf'], name='api_solicit_pacient_3059fc_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaoexamelab',
            index=models.Index(fields=['protocolo'], name='api_solicit_protoco_89eba2_idx'),
        ),
    ]
