# Generated by Django 5.0.6 on 2026-06-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_laboratorio_governo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaunidade',
            name='estado',
            field=models.CharField(blank=True, default='', help_text='UF — usado no rollup regional/multi-estado', max_length=2),
        ),
    ]
