# Generated by Django 5.0.6 on 2026-06-23 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_empresa_unidade_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAAutorizacaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(max_length=160)),
                ('tipo_solicitacao', models.CharField(choices=[('internacao', 'Internação'), ('cirurgia', 'Cirurgia'), ('exame_alta_complexidade', 'Exame de Alta Complexidade'), ('procedimento', 'Procedimento')], default='procedimento', max_length=30)),
                ('procedimento', models.CharField(max_length=200)),
                ('cid10', models.CharField(blank=True, max_length=10)),
                ('justificativa_clinica', models.TextField(blank=True)),
                ('urgente', models.BooleanField(default=False)),
                ('decisao', models.CharField(choices=[('aprovada', 'Aprovada'), ('negada', 'Negada'), ('revisao', 'Revisão humana')], default='revisao', max_length=20)),
                ('score_confianca', models.FloatField(default=0.0)),
                ('justificativa_ia', models.TextField(blank=True)),
                ('modelo_versao', models.CharField(blank=True, default='Ensemble RF+GB SolusCRT v2', max_length=80)),
                ('revisada_por', models.CharField(blank=True, max_length=120)),
                ('decisao_final', models.CharField(blank=True, choices=[('aprovada', 'Aprovada'), ('negada', 'Negada'), ('revisao', 'Revisão humana')], max_length=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_autorizacoes_clinicas', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Autorização IA Clínica (Hospital)',
                'verbose_name_plural': 'Autorizações IA Clínicas (Hospital)',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'decisao'], name='api_iaautor_empresa_9fa0ce_idx'), models.Index(fields=['empresa', 'decisao_final'], name='api_iaautor_empresa_c59d7b_idx')],
            },
        ),
    ]
