# Generated by Django 5.0.6 on 2026-06-23 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_ia_autorizacao_clinica_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaCidadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('informativo', 'Informativo'), ('campanha_vacinacao', 'Campanha de Vacinação'), ('alerta_sanitario', 'Alerta Sanitário'), ('epidemiologico', 'Alerta Epidemiológico'), ('convocacao', 'Convocação')], default='informativo', max_length=30)),
                ('publico_alvo', models.CharField(choices=[('todos', 'Todos os cidadãos cadastrados'), ('por_microarea', 'Por microárea (ACS)'), ('por_unidade', 'Por unidade de saúde')], default='todos', max_length=20)),
                ('microarea_filtro', models.CharField(blank=True, default='', max_length=20)),
                ('unidade_filtro', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado')], default='rascunho', max_length=20)),
                ('total_destinatarios_estimado', models.PositiveIntegerField(default=0)),
                ('enviado_por', models.CharField(blank=True, default='', max_length=160)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_cidadao', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Alerta Cidadão',
                'verbose_name_plural': 'Alertas Cidadão',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_alertac_empresa_38e68a_idx')],
            },
        ),
    ]
