# Generated by Django 5.0.6 on 2026-06-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_alerta_cidadao_governo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamentonr',
            name='nr',
            field=models.CharField(choices=[('NR-1', 'NR-1 · Riscos do PGR (inclui psicossociais)'), ('NR-5', 'NR-5 · CIPA'), ('NR-6', 'NR-6 · EPI'), ('NR-10', 'NR-10 · Segurança em Eletricidade'), ('NR-11', 'NR-11 · Transporte de Cargas'), ('NR-12', 'NR-12 · Segurança em Máquinas'), ('NR-18', 'NR-18 · Construção Civil'), ('NR-20', 'NR-20 · Inflamáveis e Combustíveis'), ('NR-23', 'NR-23 · Proteção Contra Incêndios'), ('NR-33', 'NR-33 · Espaços Confinados'), ('NR-34', 'NR-34 · Construção Naval'), ('NR-35', 'NR-35 · Trabalho em Altura'), ('outro', 'Outro')], max_length=10),
        ),
    ]
