# Generated by Django 5.0.6 on 2026-06-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_treinamento_nr_adiciona_nr1'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosintoma',
            name='exantema_vesicular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='exposicao_carrapato',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='exposicao_triatomideo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='hemoptise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='mancha_anestesia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='perda_peso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosintoma',
            name='ulcera_cutanea',
            field=models.BooleanField(default=False),
        ),
    ]
