# Generated by Django 5.0.6 on 2026-06-25 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_phase2_campos_doencas_tropicais'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaEpidemiologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('fonte', models.CharField(max_length=60)),
                ('url', models.URLField(max_length=900)),
                ('resumo', models.TextField(blank=True, default='')),
                ('doencas_detectadas', models.JSONField(default=list)),
                ('nivel_alerta', models.CharField(choices=[('informativo', 'Informativo'), ('alerta', 'Alerta'), ('critico', 'Crítico')], default='informativo', max_length=20)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('lido', 'Lido'), ('arquivado', 'Arquivado')], default='novo', max_length=20)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias_epidemiologicas', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Notícia Epidemiológica',
                'verbose_name_plural': 'Notícias Epidemiológicas',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_noticia_empresa_58f4d0_idx'), models.Index(fields=['empresa', 'nivel_alerta'], name='api_noticia_empresa_c8fb63_idx'), models.Index(fields=['criado_em'], name='api_noticia_criado__2b9263_idx')],
                'unique_together': {('empresa', 'url')},
            },
        ),
    ]
