# Generated by Django 5.0.6 on 2026-06-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_monitorar_noticias_epidemiologicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiaepidemiologica',
            name='alerta_disparado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noticiaepidemiologica',
            name='ia_acoes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='noticiaepidemiologica',
            name='ia_analisado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noticiaepidemiologica',
            name='ia_casos_estimados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticiaepidemiologica',
            name='ia_cid10',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='noticiaepidemiologica',
            name='ia_confianca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticiaepidemiologica',
            name='ia_justificativa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='noticiaepidemiologica',
            name='ia_modelo_usado',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='noticiaepidemiologica',
            name='ia_municipio',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='noticiaepidemiologica',
            name='ia_regiao_uf',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='noticiaepidemiologica',
            name='ia_score_risco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticiaepidemiologica',
            name='ia_tendencia',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='noticiaepidemiologica',
            index=models.Index(fields=['empresa', 'ia_analisado'], name='api_noticia_empresa_68a88f_idx'),
        ),
        migrations.AddIndex(
            model_name='noticiaepidemiologica',
            index=models.Index(fields=['empresa', 'ia_score_risco'], name='api_noticia_empresa_6bd947_idx'),
        ),
    ]
