# Generated by Django 5.0.6 on 2026-06-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_ia_analise_campos_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diopsdeclaracao',
            name='trimestre',
            field=models.CharField(max_length=20),
        ),
    ]
