# Generated by Django 5.0.6 on 2026-06-27 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_diops_trimestre_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioComunicadoLido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lido_em', models.DateTimeField(auto_now_add=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='api.conteudosstpublicado')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_lidos', to='api.funcionariosst')),
            ],
            options={
                'indexes': [models.Index(fields=['funcionario', 'comunicado'], name='api_funcion_funcion_76d03c_idx')],
                'unique_together': {('funcionario', 'comunicado')},
            },
        ),
    ]
