# Generated by Django 5.0.6 on 2026-06-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_regsintoma_indexes_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturadocumentosst',
            name='finalidade_assinatura',
            field=models.CharField(blank=True, choices=[('ciencia_trabalhador', 'Ciência do trabalhador'), ('validacao_tecnica', 'Validação técnica'), ('validacao_empresa', 'Validação da empresa'), ('aceite_documento', 'Aceite eletrônico do documento'), ('entrega_documento', 'Entrega de documento')], default='', max_length=40),
        ),
    ]
