# Generated by Django 5.0.6 on 2026-07-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_alter_assinaturadocumentosst_finalidade_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='sisreg_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='sisreg_cnes',
            field=models.CharField(blank=True, default='', help_text='CNES da unidade reguladora', max_length=7),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='sisreg_login',
            field=models.CharField(blank=True, default='', help_text='Login de acesso ao portal SISREG', max_length=120),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='sisreg_senha_cripto',
            field=models.TextField(blank=True, default='', help_text='Senha SISREG criptografada (Fernet)'),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='tiss_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='tiss_cnpj',
            field=models.CharField(blank=True, default='', help_text='CNPJ do prestador ou operadora', max_length=14),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='tiss_codigo',
            field=models.CharField(blank=True, default='', help_text='Código ANS do prestador/operadora', max_length=10),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='tiss_senha_cripto',
            field=models.TextField(blank=True, default='', help_text='Senha TISS criptografada (Fernet)'),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='tiss_usuario',
            field=models.CharField(blank=True, default='', help_text='Usuário no portal TISS ANS', max_length=120),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='tiss_versao',
            field=models.CharField(blank=True, default='3.05.00', max_length=10),
        ),
    ]
