# Generated by Django 5.0.6 on 2026-07-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_credenciais_sisreg_tiss'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='surtoepidemiologico',
            index=models.Index(fields=['empresa', 'status'], name='surto_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='surtoepidemiologico',
            index=models.Index(fields=['empresa', 'nivel_alerta'], name='surto_emp_nivel_idx'),
        ),
        migrations.AddIndex(
            model_name='surtoepidemiologico',
            index=models.Index(fields=['empresa', 'status', 'nivel_alerta'], name='surto_emp_status_nivel_idx'),
        ),
        migrations.AddIndex(
            model_name='surtoepidemiologico',
            index=models.Index(fields=['empresa', 'data_inicio'], name='surto_emp_data_idx'),
        ),
    ]
