# Generated by Django 5.0.6 on 2026-07-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_empresa_email_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaepidemiologica',
            name='ia_casos_estimados',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
