# Generated by Django 5.0.6 on 2026-07-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_bigint_ia_casos_estimados'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometriafuncionario',
            name='consentimento_confirmado_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que o consentimento do titular para coleta de dado biométrico foi confirmado (LGPD Art. 11)', null=True),
        ),
        migrations.AddField(
            model_name='biometriafuncionario',
            name='consentimento_confirmado_por',
            field=models.CharField(blank=True, default='', help_text='Quem confirmou o consentimento (e-mail do gestor/empresa que registrou a coleta)', max_length=150),
        ),
    ]
