# Generated by Django 5.2.16 on 2026-07-13 01:20

import api.crypto_cpf
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_encrypt_cpf_funcionariossst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariosst',
            name='cpf',
            field=api.crypto_cpf.EncryptedCPFField(blank=True, default=''),
        ),
    ]
