# Generated by Django 5.2.16 on 2026-07-16 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_documento_clinico_gov'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaepi',
            name='numero_serie_item',
            field=models.CharField(blank=True, default='', help_text='Nº de série/identificação do item físico, para EPIs com inspeção periódica', max_length=60),
        ),
        migrations.AddField(
            model_name='epiitem',
            name='exige_inspecao_periodica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epiitem',
            name='norma_inspecao',
            field=models.CharField(blank=True, default='', help_text='Ex: NR-10, NR-35', max_length=20),
        ),
        migrations.AddField(
            model_name='epiitem',
            name='periodicidade_inspecao_dias',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TipoTreinamentoNR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(choices=[('NR-1', 'NR-1 · Riscos do PGR (inclui psicossociais)'), ('NR-5', 'NR-5 · CIPA'), ('NR-6', 'NR-6 · EPI'), ('NR-10', 'NR-10 · Segurança em Eletricidade'), ('NR-11', 'NR-11 · Transporte de Cargas'), ('NR-12', 'NR-12 · Segurança em Máquinas'), ('NR-18', 'NR-18 · Construção Civil'), ('NR-20', 'NR-20 · Inflamáveis e Combustíveis'), ('NR-23', 'NR-23 · Proteção Contra Incêndios'), ('NR-33', 'NR-33 · Espaços Confinados'), ('NR-34', 'NR-34 · Construção Naval'), ('NR-35', 'NR-35 · Trabalho em Altura'), ('outro', 'Outro')], max_length=10)),
                ('nome', models.CharField(help_text='Ex: NR-35 Básico, NR-10 SEP Reciclagem', max_length=200)),
                ('carga_horaria_padrao', models.PositiveSmallIntegerField(help_text='Horas — editável conforme grade interna')),
                ('periodicidade_dias', models.PositiveSmallIntegerField(blank=True, help_text='Intervalo de reciclagem, em dias', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_treinamento_nr', to='api.empresa')),
            ],
            options={
                'ordering': ['nr', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='treinamentonr',
            name='tipo_treinamento',
            field=models.ForeignKey(blank=True, help_text='Tipo de treinamento do catálogo (opcional) — pré-preenche a carga horária padrão', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treinamentos_registrados', to='api.tipotreinamentonr'),
        ),
        migrations.CreateModel(
            name='InspecaoEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao', models.DateField()),
                ('resultado', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado — EPI recolhido'), ('condicional', 'Aprovado com ressalva')], max_length=20)),
                ('responsavel_tecnico', models.CharField(blank=True, default='', max_length=120)),
                ('numero_laudo', models.CharField(blank=True, default='', max_length=60)),
                ('proxima_inspecao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes_epi', to='api.empresa')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes', to='api.entregaepi')),
            ],
            options={
                'ordering': ['-data_inspecao'],
                'indexes': [models.Index(fields=['empresa', 'entrega'], name='api_inspeca_empresa_dc74a8_idx'), models.Index(fields=['empresa', 'proxima_inspecao'], name='api_inspeca_empresa_0621ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstrumentoMedicaoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('decibelimetro', 'Decibelímetro'), ('luximetro', 'Luxímetro'), ('medidor_campo_eletrico', 'Medidor de Campo Elétrico/Magnético'), ('termohigrometro', 'Termo-higrômetro'), ('dosimetro', 'Dosímetro de Ruído'), ('bomba_amostragem', 'Bomba de Amostragem de Ar'), ('outro', 'Outro')], max_length=30)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=60)),
                ('fabricante', models.CharField(blank=True, default='', max_length=120)),
                ('norma_referencia', models.CharField(blank=True, default='', help_text='Ex: NR-15, NR-09', max_length=20)),
                ('laboratorio_calibracao', models.CharField(blank=True, default='', max_length=150)),
                ('numero_certificado', models.CharField(blank=True, default='', max_length=60)),
                ('data_ultima_calibracao', models.DateField(blank=True, null=True)),
                ('data_proxima_calibracao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('calibrado', 'Calibrado'), ('vencido', 'Calibração Vencida'), ('em_calibracao', 'Em Calibração')], default='calibrado', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos_medicao', to='api.empresa')),
            ],
            options={
                'ordering': ['tipo', 'nome'],
                'indexes': [models.Index(fields=['empresa', 'tipo'], name='api_instrum_empresa_5219f0_idx'), models.Index(fields=['empresa', 'data_proxima_calibracao'], name='api_instrum_empresa_81bc44_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tipotreinamentonr',
            index=models.Index(fields=['empresa', 'nr'], name='api_tipotre_empresa_b9cdf5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tipotreinamentonr',
            unique_together={('empresa', 'nr', 'nome')},
        ),
    ]
