# Generated by Django 5.2.16 on 2026-07-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_entregaepi_numero_serie_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipotreinamentonr',
            options={'ordering': ['nr', 'categoria', 'nome']},
        ),
        migrations.AlterUniqueTogether(
            name='tipotreinamentonr',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tipotreinamentonr',
            name='categoria',
            field=models.CharField(blank=True, default='', help_text='Ex: Onboarding, Produto, Liderança — usado quando não é uma NR', max_length=80),
        ),
        migrations.AddField(
            model_name='treinamentonr',
            name='categoria',
            field=models.CharField(blank=True, default='', help_text='Categoria livre quando não é uma NR — ex: Onboarding, Produto, Liderança', max_length=80),
        ),
        migrations.AlterField(
            model_name='tipotreinamentonr',
            name='nome',
            field=models.CharField(help_text='Ex: NR-35 Básico, Integração de Novos Funcionários', max_length=200),
        ),
        migrations.AlterField(
            model_name='tipotreinamentonr',
            name='nr',
            field=models.CharField(blank=True, choices=[('NR-1', 'NR-1 · Riscos do PGR (inclui psicossociais)'), ('NR-5', 'NR-5 · CIPA'), ('NR-6', 'NR-6 · EPI'), ('NR-10', 'NR-10 · Segurança em Eletricidade'), ('NR-11', 'NR-11 · Transporte de Cargas'), ('NR-12', 'NR-12 · Segurança em Máquinas'), ('NR-18', 'NR-18 · Construção Civil'), ('NR-20', 'NR-20 · Inflamáveis e Combustíveis'), ('NR-23', 'NR-23 · Proteção Contra Incêndios'), ('NR-33', 'NR-33 · Espaços Confinados'), ('NR-34', 'NR-34 · Construção Naval'), ('NR-35', 'NR-35 · Trabalho em Altura'), ('outro', 'Outro')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='treinamentonr',
            name='nr',
            field=models.CharField(blank=True, choices=[('NR-1', 'NR-1 · Riscos do PGR (inclui psicossociais)'), ('NR-5', 'NR-5 · CIPA'), ('NR-6', 'NR-6 · EPI'), ('NR-10', 'NR-10 · Segurança em Eletricidade'), ('NR-11', 'NR-11 · Transporte de Cargas'), ('NR-12', 'NR-12 · Segurança em Máquinas'), ('NR-18', 'NR-18 · Construção Civil'), ('NR-20', 'NR-20 · Inflamáveis e Combustíveis'), ('NR-23', 'NR-23 · Proteção Contra Incêndios'), ('NR-33', 'NR-33 · Espaços Confinados'), ('NR-34', 'NR-34 · Construção Naval'), ('NR-35', 'NR-35 · Trabalho em Altura'), ('outro', 'Outro')], default='', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='tipotreinamentonr',
            unique_together={('empresa', 'nr', 'categoria', 'nome')},
        ),
    ]
