# Generated by Django 5.2.16 on 2026-07-17 03:22

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_alter_tipotreinamentonr_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaTreinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, default='', help_text='Ex: Técnico em Segurança do Trabalho, Engenheiro de Segurança', max_length=120)),
                ('registro_profissional', models.CharField(blank=True, default='', help_text='Ex: CREA 123456, Registro MTE 78910', max_length=60)),
                ('imagem_assinatura', models.FileField(blank=True, help_text='Imagem da assinatura (PNG/JPG)', null=True, upload_to='assinaturas_treinador/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_treinador', to='api.empresa')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ModeloCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Modelo Padrão NR, Certificado Onboarding', max_length=120)),
                ('estilo', models.CharField(choices=[('classico', 'Clássico — moldura formal, tons neutros'), ('moderno', 'Moderno — geométrico, cor de destaque'), ('compacto', 'Compacto — direto ao ponto, uma página enxuta')], default='classico', max_length=20)),
                ('cor_destaque', models.CharField(blank=True, default='', help_text='Hex opcional — se vazio, usa a cor da marca da empresa', max_length=7)),
                ('texto_rodape', models.CharField(blank=True, default='', help_text='Texto adicional no rodapé do certificado, ex: base legal ou observação', max_length=300)),
                ('padrao', models.BooleanField(default=False, help_text='Usado quando o curso não tiver modelo específico definido')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_certificado', to='api.empresa')),
            ],
            options={
                'ordering': ['-padrao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CursoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, default='', help_text='Link do vídeo já hospedado (YouTube não-listado, Vimeo, Google Drive etc.)')),
                ('material_texto', models.TextField(blank=True, default='', help_text='Conteúdo de apoio em texto — apostila, roteiro, instruções')),
                ('material_arquivo', models.FileField(blank=True, help_text='Apostila em PDF ou similar, opcional', null=True, upload_to='material_curso_interno/')),
                ('carga_horaria', models.PositiveSmallIntegerField(default=1, help_text='Horas — usada no certificado e no relatório de homem-hora')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assinatura_treinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_internos', to='api.assinaturatreinador')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_internos', to='api.empresa')),
                ('tipo_treinamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_internos', to='api.tipotreinamentonr')),
                ('modelo_certificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_internos', to='api.modelocertificado')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MatriculaCursoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('matriculado', 'Matriculado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='matriculado', max_length=20)),
                ('token_acesso', models.CharField(default=api.models._codigo_acesso, help_text='Token público para o funcionário acessar o curso sem login', max_length=40, unique=True)),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('numero_certificado', models.CharField(blank=True, default='', max_length=40)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='api.cursointerno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_curso_interno', to='api.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_curso_interno', to='api.funcionariosst')),
                ('treinamento_nr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matricula_curso_interno', to='api.treinamentonr')),
            ],
            options={
                'ordering': ['-data_matricula'],
                'unique_together': {('curso', 'funcionario')},
            },
        ),
    ]
