# Generated by Django 5.2.16 on 2026-07-18 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_assinaturatreinador_modelocertificado_cursointerno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaautorizacao',
            name='score_confianca_ia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guiaautorizacao',
            name='sugestao_ia',
            field=models.CharField(blank=True, choices=[('aprovar', 'IA sugere aprovar'), ('revisar', 'IA sugere revisão manual')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='guiaautorizacao',
            name='sugestao_motivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='guiaautorizacao',
            name='sugestao_seguida',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegraAutorizacaoAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos_elegiveis', models.JSONField(blank=True, default=list, help_text='Lista de GuiaAutorizacao.TIPO_CHOICES elegíveis pra sugestão')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('score_minimo', models.FloatField(default=85)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regra_autorizacao_automatica', to='api.empresa')),
            ],
        ),
    ]
