# Generated by Django 5.2.16 on 2026-07-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_guiaautorizacao_score_confianca_ia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfarmacia',
            name='categoria',
            field=models.CharField(choices=[('material', 'Material'), ('insumo', 'Insumo'), ('outro', 'Outro')], default='material', max_length=20),
        ),
    ]
