from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_agendamentoubs_data_solicitacao'),
    ]

    operations = [
        # UnidadeCRAS
        migrations.CreateModel(
            name='UnidadeCRAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_cras', models.CharField(blank=True, max_length=20)),
                ('cnes', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
            options={'ordering': ['nome']},
        ),
        # FamiliaCRAS
        migrations.CreateModel(
            name='FamiliaCRAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_prontuario', models.CharField(blank=True, max_length=50)),
                ('responsavel_nome', models.CharField(max_length=200)),
                ('responsavel_cpf', models.CharField(blank=True, max_length=14)),
                ('responsavel_nis', models.CharField(blank=True, max_length=20)),
                ('responsavel_cns', models.CharField(blank=True, max_length=20)),
                ('responsavel_data_nascimento', models.DateField(blank=True, null=True)),
                ('responsavel_telefone', models.CharField(blank=True, max_length=20)),
                ('num_integrantes', models.PositiveSmallIntegerField(default=1)),
                ('renda_familiar_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cadUnico_numero_seq', models.CharField(blank=True, max_length=30)),
                ('marcador_pbf', models.BooleanField(default=False)),
                ('marcador_bpc', models.BooleanField(default=False)),
                ('situacao', models.CharField(
                    choices=[
                        ('em_acompanhamento', 'Em Acompanhamento'),
                        ('ativa', 'Ativa'),
                        ('encerrada', 'Encerrada'),
                        ('suspensa', 'Suspensa'),
                    ],
                    default='em_acompanhamento',
                    max_length=20,
                )),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('unidade_cras', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='familias',
                    to='api.unidadecras',
                )),
            ],
            options={'ordering': ['responsavel_nome']},
        ),
        # AtendimentoCRAS
        migrations.CreateModel(
            name='AtendimentoCRAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico_nome', models.CharField(blank=True, max_length=200)),
                ('tecnico_cargo', models.CharField(blank=True, max_length=100)),
                ('data_atendimento', models.DateField()),
                ('tipo', models.CharField(
                    choices=[
                        ('individual', 'Individual'),
                        ('familiar', 'Familiar'),
                        ('grupo', 'Grupo'),
                        ('visita', 'Visita Domiciliar'),
                        ('encaminhamento', 'Encaminhamento'),
                        ('acompanhamento', 'Acompanhamento'),
                    ],
                    default='individual',
                    max_length=20,
                )),
                ('objetivo', models.CharField(blank=True, max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('encaminhamento', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('familia', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='atendimentos',
                    to='api.familiacras',
                )),
                ('unidade_cras', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='api.unidadecras',
                )),
            ],
            options={'ordering': ['-data_atendimento']},
        ),
        # VisitaDomiciliarSocial
        migrations.CreateModel(
            name='VisitaDomiciliarSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico_nome', models.CharField(blank=True, max_length=200)),
                ('data_visita', models.DateField()),
                ('objetivo', models.CharField(blank=True, max_length=300)),
                ('relato', models.TextField(blank=True)),
                ('resultado', models.TextField(blank=True)),
                ('vulnerabilidade_identificada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('familia', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='visitas',
                    to='api.familiacras',
                )),
            ],
            options={'ordering': ['-data_visita']},
        ),
        # UnidadeCREAS
        migrations.CreateModel(
            name='UnidadeCREAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_creas', models.CharField(blank=True, max_length=20)),
                ('cnes', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
            options={'ordering': ['nome']},
        ),
        # AtendimentoCREAS
        migrations.CreateModel(
            name='AtendimentoCREAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(max_length=200)),
                ('usuario_cpf', models.CharField(blank=True, max_length=14)),
                ('usuario_cns', models.CharField(blank=True, max_length=20)),
                ('usuario_data_nascimento', models.DateField(blank=True, null=True)),
                ('usuario_telefone', models.CharField(blank=True, max_length=20)),
                ('tecnico_nome', models.CharField(blank=True, max_length=200)),
                ('tecnico_cargo', models.CharField(blank=True, max_length=100)),
                ('data_atendimento', models.DateField()),
                ('tipo_violacao', models.CharField(
                    choices=[
                        ('violencia_domestica', 'Violência Doméstica'),
                        ('sexual', 'Violência Sexual'),
                        ('exploracao_sexual', 'Exploração Sexual'),
                        ('trabalho_infantil', 'Trabalho Infantil'),
                        ('negligencia', 'Negligência/Abandono'),
                        ('trafico_pessoas', 'Tráfico de Pessoas'),
                        ('cumprimento_medida', 'Cumprimento de Medida Socioeducativa'),
                        ('populacao_rua', 'População em Situação de Rua'),
                        ('abuso_substancias', 'Abuso de Substâncias'),
                        ('outros', 'Outros'),
                    ],
                    default='outros',
                    max_length=30,
                )),
                ('situacao', models.CharField(
                    choices=[
                        ('em_acompanhamento', 'Em Acompanhamento'),
                        ('encerrado', 'Encerrado'),
                        ('referenciado', 'Referenciado'),
                        ('aguardando', 'Aguardando'),
                    ],
                    default='em_acompanhamento',
                    max_length=20,
                )),
                ('descricao', models.TextField(blank=True)),
                ('plano_atendimento', models.TextField(blank=True)),
                ('encaminhamento', models.TextField(blank=True)),
                ('numero_prontuario', models.CharField(blank=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('unidade_creas', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='atendimentos',
                    to='api.unidadecreas',
                )),
            ],
            options={'ordering': ['-data_atendimento']},
        ),
        # CadUnicoFamilia
        migrations.CreateModel(
            name='CadUnicoFamilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_seq', models.CharField(blank=True, max_length=30)),
                ('cod_familiar_fam', models.CharField(blank=True, max_length=30)),
                ('responsavel_nome', models.CharField(max_length=200)),
                ('responsavel_cpf', models.CharField(blank=True, max_length=14)),
                ('responsavel_nis', models.CharField(blank=True, max_length=20)),
                ('qtd_pessoas', models.PositiveSmallIntegerField(default=1)),
                ('renda_per_capita', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_cadastramento', models.DateField(blank=True, null=True)),
                ('data_ultima_atualizacao', models.DateField(blank=True, null=True)),
                ('marcador_pbf', models.BooleanField(default=False)),
                ('marcador_bpc', models.BooleanField(default=False)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('importado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
            options={'ordering': ['responsavel_nome']},
        ),
        # BeneficiarioBPC
        migrations.CreateModel(
            name='BeneficiarioBPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiario_nome', models.CharField(max_length=200)),
                ('beneficiario_cpf', models.CharField(blank=True, max_length=14)),
                ('beneficiario_nis', models.CharField(blank=True, max_length=20)),
                ('tipo_bpc', models.CharField(
                    choices=[
                        ('pessoa_deficiencia', 'Pessoa com Deficiência'),
                        ('idoso_65', 'Idoso (65+)'),
                    ],
                    max_length=20,
                )),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('valor_beneficio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
            options={'ordering': ['beneficiario_nome']},
        ),
        # CondicionalidadeSICON
        migrations.CreateModel(
            name='CondicionalidadeSICON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular_nome', models.CharField(max_length=200)),
                ('titular_cpf', models.CharField(blank=True, max_length=14)),
                ('titular_nis', models.CharField(blank=True, max_length=20)),
                ('area', models.CharField(
                    choices=[
                        ('saude', 'Saúde'),
                        ('educacao', 'Educação'),
                        ('social', 'Assistência Social'),
                    ],
                    max_length=10,
                )),
                ('periodo_referencia', models.CharField(max_length=7)),
                ('status', models.CharField(
                    choices=[
                        ('cumprida', 'Cumprida'),
                        ('descumprida', 'Descumprida'),
                        ('sem_informacao', 'Sem Informação'),
                        ('em_acompanhamento', 'Em Acompanhamento'),
                    ],
                    default='sem_informacao',
                    max_length=20,
                )),
                ('motivo_descumprimento', models.TextField(blank=True)),
                ('acompanhamento_tecnico', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
            options={'ordering': ['-periodo_referencia', 'titular_nome']},
        ),
        # BeneficioEventual
        migrations.CreateModel(
            name='BeneficioEventual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiario_nome', models.CharField(max_length=200)),
                ('beneficiario_cpf', models.CharField(blank=True, max_length=14)),
                ('beneficiario_nis', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(
                    choices=[
                        ('cesta_basica', 'Cesta Básica'),
                        ('auxilio_aluguel', 'Auxílio Aluguel'),
                        ('passagem', 'Passagem'),
                        ('material_escolar', 'Material Escolar'),
                        ('material_construcao', 'Material de Construção'),
                        ('medicamento', 'Medicamento'),
                        ('enxoval_bebe', 'Enxoval de Bebê'),
                        ('auxilio_funeral', 'Auxílio Funeral'),
                        ('outros', 'Outros'),
                    ],
                    max_length=20,
                )),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_concessao', models.DateField()),
                ('tecnico_responsavel', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('unidade_cras', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='api.unidadecras',
                )),
            ],
            options={'ordering': ['-data_concessao']},
        ),
    ]
