# Generated by Django 5.2.16 on 2026-07-21 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_suas_assistencia_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimentocras',
            options={'ordering': ['-data_atendimento'], 'verbose_name': 'Atendimento CRAS', 'verbose_name_plural': 'Atendimentos CRAS'},
        ),
        migrations.AlterModelOptions(
            name='atendimentocreas',
            options={'ordering': ['-data_atendimento'], 'verbose_name': 'Atendimento CREAS', 'verbose_name_plural': 'Atendimentos CREAS'},
        ),
        migrations.AlterModelOptions(
            name='beneficiariobpc',
            options={'ordering': ['beneficiario_nome'], 'verbose_name': 'Beneficiário BPC', 'verbose_name_plural': 'Beneficiários BPC'},
        ),
        migrations.AlterModelOptions(
            name='beneficioeventual',
            options={'ordering': ['-data_concessao'], 'verbose_name': 'Benefício Eventual', 'verbose_name_plural': 'Benefícios Eventuais'},
        ),
        migrations.AlterModelOptions(
            name='cadunicofamilia',
            options={'ordering': ['responsavel_nome'], 'verbose_name': 'Família CadÚnico', 'verbose_name_plural': 'Famílias CadÚnico'},
        ),
        migrations.AlterModelOptions(
            name='condicionalidadesicon',
            options={'ordering': ['-periodo_referencia', 'titular_nome'], 'verbose_name': 'Condicionalidade SICON', 'verbose_name_plural': 'Condicionalidades SICON'},
        ),
        migrations.AlterModelOptions(
            name='familiacras',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Família CRAS', 'verbose_name_plural': 'Famílias CRAS'},
        ),
        migrations.AlterModelOptions(
            name='unidadecras',
            options={'ordering': ['nome'], 'verbose_name': 'Unidade CRAS', 'verbose_name_plural': 'Unidades CRAS'},
        ),
        migrations.AlterModelOptions(
            name='unidadecreas',
            options={'ordering': ['nome'], 'verbose_name': 'Unidade CREAS', 'verbose_name_plural': 'Unidades CREAS'},
        ),
        migrations.AlterModelOptions(
            name='visitadomiciliarsocial',
            options={'ordering': ['-data_visita'], 'verbose_name': 'Visita Domiciliar Social', 'verbose_name_plural': 'Visitas Domiciliares Sociais'},
        ),
        migrations.RemoveField(
            model_name='atendimentocras',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='beneficioeventual',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='visitadomiciliarsocial',
            name='atualizado_em',
        ),
        migrations.AddField(
            model_name='beneficiariobpc',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='beneficioeventual',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='familiacras',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='familiacras',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='familiacras',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='atendimentocras',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='atendimentocras',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cras_atendimentos', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='atendimentocras',
            name='encaminhamento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='atendimentocras',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='atendimentocras',
            name='objetivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='atendimentocras',
            name='tecnico_cargo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='atendimentocras',
            name='tecnico_nome',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='atendimentocras',
            name='tipo',
            field=models.CharField(choices=[('individual', 'Atendimento Individual'), ('familiar', 'Atendimento Familiar'), ('grupo', 'Atendimento em Grupo'), ('visita', 'Visita Domiciliar'), ('encaminhamento', 'Encaminhamento'), ('acompanhamento', 'Acompanhamento PAIF')], default='individual', max_length=30),
        ),
        migrations.AlterField(
            model_name='atendimentocras',
            name='unidade_cras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='api.unidadecras'),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creas_atendimentos', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='encaminhamento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='numero_prontuario',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='plano_atendimento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='situacao',
            field=models.CharField(choices=[('em_acompanhamento', 'Em Acompanhamento'), ('encerrado', 'Encerrado'), ('referenciado', 'Referenciado para Outro Serviço'), ('aguardando', 'Aguardando Atendimento')], default='em_acompanhamento', max_length=30),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='tecnico_cargo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='tecnico_nome',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='tipo_violacao',
            field=models.CharField(choices=[('violencia_domestica', 'Violência Doméstica / Familiar'), ('violencia_sexual', 'Violência Sexual'), ('exploracao_sexual', 'Exploração Sexual'), ('trabalho_infantil', 'Trabalho Infantil'), ('negligencia', 'Negligência / Abandono'), ('trafico_pessoas', 'Tráfico de Pessoas'), ('cumprimento_medida', 'Cumprimento de Medida Socioeducativa'), ('populacao_rua', 'Situação de Rua'), ('abuso_substancias', 'Dependência Química / Abuso de Substâncias'), ('outros', 'Outros')], default='outros', max_length=40),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='usuario_cns',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='usuario_cpf',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='usuario_telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiariobpc',
            name='beneficiario_cpf',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='beneficiariobpc',
            name='beneficiario_nis',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='beneficiariobpc',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpc_beneficiarios', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='beneficiariobpc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='beneficiariobpc',
            name='tipo_bpc',
            field=models.CharField(choices=[('pessoa_deficiencia', 'Pessoa com Deficiência'), ('idoso_65', 'Idoso (65 anos ou mais)')], default='pessoa_deficiencia', max_length=30),
        ),
        migrations.AlterField(
            model_name='beneficiariobpc',
            name='valor_beneficio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='beneficioeventual',
            name='beneficiario_cpf',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='beneficioeventual',
            name='beneficiario_nis',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='beneficioeventual',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficioeventual',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios_eventuais', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='beneficioeventual',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='beneficioeventual',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='beneficioeventual',
            name='tecnico_responsavel',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='beneficioeventual',
            name='tipo',
            field=models.CharField(choices=[('cesta_basica', 'Cesta Básica'), ('auxilio_aluguel', 'Auxílio Aluguel'), ('passagem', 'Passagem / Transporte'), ('material_escolar', 'Material Escolar'), ('material_construcao', 'Material de Construção / Reforma'), ('medicamento', 'Medicamento / Insumo de Saúde'), ('enxoval_bebe', 'Enxoval de Bebê / Auxílio Natalidade'), ('auxilio_funeral', 'Auxílio Funeral'), ('outros', 'Outros')], default='cesta_basica', max_length=30),
        ),
        migrations.AlterField(
            model_name='beneficioeventual',
            name='unidade_cras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios_eventuais', to='api.unidadecras'),
        ),
        migrations.AlterField(
            model_name='beneficioeventual',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cadunicofamilia',
            name='cod_familiar_fam',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Código Familiar CadÚnico'),
        ),
        migrations.AlterField(
            model_name='cadunicofamilia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadUnico_familias', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='cadunicofamilia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cadunicofamilia',
            name='marcador_bpc',
            field=models.BooleanField(default=False, verbose_name='Possui BPC'),
        ),
        migrations.AlterField(
            model_name='cadunicofamilia',
            name='marcador_pbf',
            field=models.BooleanField(default=False, verbose_name='Titular Bolsa Família/PBF'),
        ),
        migrations.AlterField(
            model_name='cadunicofamilia',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cadunicofamilia',
            name='numero_seq',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Número Sequencial CadÚnico'),
        ),
        migrations.AlterField(
            model_name='cadunicofamilia',
            name='renda_per_capita',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cadunicofamilia',
            name='responsavel_cpf',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='cadunicofamilia',
            name='responsavel_nis',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='cadunicofamilia',
            name='uf',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='condicionalidadesicon',
            name='acompanhamento_tecnico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='condicionalidadesicon',
            name='area',
            field=models.CharField(choices=[('saude', 'Saúde (vacinas, pré-natal, nutrição)'), ('educacao', 'Educação (frequência escolar)'), ('social', 'Assistência Social (acompanhamento familiar)')], default='social', max_length=20),
        ),
        migrations.AlterField(
            model_name='condicionalidadesicon',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sicon_condicionalidades', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='condicionalidadesicon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='condicionalidadesicon',
            name='motivo_descumprimento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='condicionalidadesicon',
            name='periodo_referencia',
            field=models.CharField(blank=True, default='', help_text='AAAA/MM', max_length=7),
        ),
        migrations.AlterField(
            model_name='condicionalidadesicon',
            name='status',
            field=models.CharField(choices=[('cumprida', 'Cumprida'), ('descumprida', 'Descumprida'), ('sem_informacao', 'Sem Informação'), ('em_acompanhamento', 'Em Acompanhamento')], default='sem_informacao', max_length=30),
        ),
        migrations.AlterField(
            model_name='condicionalidadesicon',
            name='titular_cpf',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='condicionalidadesicon',
            name='titular_nis',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='familiacras',
            name='cadUnico_numero_seq',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Número Seq. CadÚnico'),
        ),
        migrations.AlterField(
            model_name='familiacras',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cras_familias', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='familiacras',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='familiacras',
            name='marcador_bpc',
            field=models.BooleanField(default=False, verbose_name='Possui BPC'),
        ),
        migrations.AlterField(
            model_name='familiacras',
            name='marcador_pbf',
            field=models.BooleanField(default=False, verbose_name='Recebe Bolsa Família / CadÚnico PBF'),
        ),
        migrations.AlterField(
            model_name='familiacras',
            name='numero_prontuario',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='familiacras',
            name='renda_familiar_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='familiacras',
            name='responsavel_cns',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='familiacras',
            name='responsavel_cpf',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='familiacras',
            name='responsavel_nis',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='familiacras',
            name='responsavel_telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='familiacras',
            name='situacao',
            field=models.CharField(choices=[('em_acompanhamento', 'Em Acompanhamento'), ('ativa', 'Ativa — Sem Acompanhamento Ativo'), ('encerrada', 'Encerrada'), ('suspensa', 'Suspensa')], default='em_acompanhamento', max_length=30),
        ),
        migrations.AlterField(
            model_name='unidadecras',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='unidadecras',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='unidadecras',
            name='cnes',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='unidadecras',
            name='codigo_cras',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadecras',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='unidadecras',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cras_unidades', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='unidadecras',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='unidadecras',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unidadecras',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='unidadecras',
            name='nome',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='unidadecras',
            name='responsavel_tecnico',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='unidadecras',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadecras',
            name='uf',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='unidadecreas',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='unidadecreas',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='unidadecreas',
            name='cnes',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='unidadecreas',
            name='codigo_creas',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadecreas',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creas_unidades', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='unidadecreas',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='unidadecreas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unidadecreas',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='unidadecreas',
            name='nome',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='unidadecreas',
            name='responsavel_tecnico',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='unidadecreas',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadecreas',
            name='uf',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='visitadomiciliarsocial',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_sociais', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='visitadomiciliarsocial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visitadomiciliarsocial',
            name='objetivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitadomiciliarsocial',
            name='relato',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visitadomiciliarsocial',
            name='resultado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visitadomiciliarsocial',
            name='tecnico_nome',
            field=models.CharField(max_length=160),
        ),
        migrations.AddIndex(
            model_name='atendimentocras',
            index=models.Index(fields=['empresa', 'data_atendimento'], name='api_atendim_empresa_8054c8_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimentocras',
            index=models.Index(fields=['empresa', 'familia'], name='api_atendim_empresa_aaafa9_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimentocreas',
            index=models.Index(fields=['empresa', 'situacao'], name='api_atendim_empresa_956dba_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimentocreas',
            index=models.Index(fields=['empresa', 'data_atendimento'], name='api_atendim_empresa_75fe8c_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimentocreas',
            index=models.Index(fields=['empresa', 'usuario_cpf'], name='api_atendim_empresa_e9d54b_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiariobpc',
            index=models.Index(fields=['empresa', 'ativo'], name='api_benefic_empresa_816ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiariobpc',
            index=models.Index(fields=['empresa', 'tipo_bpc'], name='api_benefic_empresa_5f937f_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficioeventual',
            index=models.Index(fields=['empresa', 'tipo'], name='api_benefic_empresa_509327_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficioeventual',
            index=models.Index(fields=['empresa', 'data_concessao'], name='api_benefic_empresa_f7cf61_idx'),
        ),
        migrations.AddIndex(
            model_name='cadunicofamilia',
            index=models.Index(fields=['empresa', 'responsavel_cpf'], name='api_cadunic_empresa_2e1002_idx'),
        ),
        migrations.AddIndex(
            model_name='cadunicofamilia',
            index=models.Index(fields=['empresa', 'marcador_pbf'], name='api_cadunic_empresa_3bd5e6_idx'),
        ),
        migrations.AddIndex(
            model_name='condicionalidadesicon',
            index=models.Index(fields=['empresa', 'status'], name='api_condici_empresa_ba9866_idx'),
        ),
        migrations.AddIndex(
            model_name='condicionalidadesicon',
            index=models.Index(fields=['empresa', 'periodo_referencia'], name='api_condici_empresa_405c17_idx'),
        ),
        migrations.AddIndex(
            model_name='familiacras',
            index=models.Index(fields=['empresa', 'situacao'], name='api_familia_empresa_5b1732_idx'),
        ),
        migrations.AddIndex(
            model_name='familiacras',
            index=models.Index(fields=['empresa', 'unidade_cras'], name='api_familia_empresa_5d3f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='familiacras',
            index=models.Index(fields=['empresa', 'responsavel_cpf'], name='api_familia_empresa_2fd4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadecras',
            index=models.Index(fields=['empresa', 'ativo'], name='api_unidade_empresa_6fbca5_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadecreas',
            index=models.Index(fields=['empresa', 'ativo'], name='api_unidade_empresa_81173b_idx'),
        ),
        migrations.AddIndex(
            model_name='visitadomiciliarsocial',
            index=models.Index(fields=['empresa', 'data_visita'], name='api_visitad_empresa_4e1a81_idx'),
        ),
    ]
