# Generated by Django 5.2.16 on 2026-07-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_atendimentoubs_assinatura'),
        ('api', '0154_suas_correcao'),
    ]

    operations = [
    ]
