# Generated by Django 5.2.16 on 2026-07-24 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_rename_api_inconsistencia_empresa_status_idx_api_inconsi_empresa_17db43_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iaautorizacaoclinica',
            name='modelo_versao',
            field=models.CharField(blank=True, default='Ensemble RF+GB SoloCRT v2', max_length=80),
        ),
        migrations.AlterField(
            model_name='iaautorizacaoguia',
            name='modelo_versao',
            field=models.CharField(blank=True, default='Ensemble RF+GB SoloCRT v2', max_length=80),
        ),
        migrations.AlterField(
            model_name='vinculoclinicaempresa',
            name='empresa_contratante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_como_empresa', to='api.empresa', verbose_name='Empresa contratante (conta SoloCRT)'),
        ),
    ]
