# Generated by Django 5.2.16 on 2026-07-29 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_mobilidade_dispersao'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarioplano',
            name='grau_parentesco',
            field=models.CharField(blank=True, choices=[('conjuge', 'Cônjuge / Companheiro(a)'), ('filho', 'Filho(a)'), ('pai_mae', 'Pai / Mãe'), ('enteado', 'Enteado(a)'), ('tutelado', 'Tutelado(a) / Menor sob guarda'), ('agregado', 'Agregado(a)'), ('outro', 'Outro')], default='', help_text='Grau de parentesco do dependente em relação ao titular', max_length=12),
        ),
        migrations.AddField(
            model_name='beneficiarioplano',
            name='tipo_vinculo',
            field=models.CharField(choices=[('titular', 'Titular'), ('dependente', 'Dependente')], default='titular', max_length=12),
        ),
        migrations.AddField(
            model_name='beneficiarioplano',
            name='titular',
            field=models.ForeignKey(blank=True, help_text='Titular do núcleo familiar (vazio quando o próprio é titular)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependentes', to='api.beneficiarioplano'),
        ),
    ]
