# Generated by Django 5.2.16 on 2026-07-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_nucleo_familiar_beneficiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoNPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(help_text='Nota NPS de 0 a 10')),
                ('comentario', models.TextField(blank=True, default='')),
                ('canal', models.CharField(choices=[('app', 'App'), ('portal', 'Portal Web'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('presencial', 'Presencial')], default='app', max_length=12)),
                ('competencia', models.CharField(blank=True, default='', help_text='YYYY-MM', max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_nps', to='api.beneficiarioplano')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_nps', to='api.empresa')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_nps', to='api.planosaude')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RessarcimentoSUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_abi', models.CharField(blank=True, default='', help_text='Nº do Aviso de Beneficiário Identificado (ANS)', max_length=40)),
                ('competencia', models.CharField(blank=True, default='', help_text='YYYY-MM do lote ABI', max_length=7)),
                ('beneficiario_nome', models.CharField(blank=True, default='', max_length=200)),
                ('beneficiario_cpf', models.CharField(blank=True, default='', max_length=14)),
                ('tipo_atendimento', models.CharField(choices=[('ambulatorial', 'Ambulatorial'), ('internacao', 'Internação'), ('urgencia', 'Urgência / Emergência'), ('alta_complexidade', 'Alta Complexidade')], default='ambulatorial', max_length=20)),
                ('procedimento', models.CharField(blank=True, default='', max_length=255)),
                ('estabelecimento_sus', models.CharField(blank=True, default='', help_text='Unidade SUS onde ocorreu o atendimento', max_length=200)),
                ('data_atendimento', models.DateField(blank=True, null=True)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, default=0, help_text='Valor cobrado pela ANS (VRR)', max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('recebido', 'ABI recebido'), ('em_analise', 'Em análise'), ('impugnado', 'Impugnado'), ('deferido', 'Impugnação deferida'), ('indeferido', 'Impugnação indeferida'), ('gru_emitida', 'GRU emitida'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='recebido', max_length=15)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('prazo_impugnacao', models.DateField(blank=True, help_text='Prazo final para impugnar o ABI', null=True)),
                ('justificativa_impugnacao', models.TextField(blank=True, default='')),
                ('numero_gru', models.CharField(blank=True, default='', max_length=60)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.ForeignKey(blank=True, help_text='Beneficiário casado no cadastro (pode não haver match com o ABI da ANS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressarcimentos_sus', to='api.beneficiarioplano')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressarcimentos_sus', to='api.empresa')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressarcimentos_sus', to='api.planosaude')),
            ],
            options={
                'ordering': ['-data_recebimento', '-criado_em'],
            },
        ),
    ]
