# Generated by Django 5.2.16 on 2026-07-30 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_ressarcimento_sus_e_nps'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaIntercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('emitida', 'Emitida (a receber)'), ('recebida', 'Recebida (a pagar)')], default='emitida', max_length=10)),
                ('numero_gto', models.CharField(blank=True, default='', max_length=40)),
                ('operadora_correspondente', models.CharField(blank=True, default='', help_text='Operadora da outra praça', max_length=200)),
                ('registro_ans_correspondente', models.CharField(blank=True, default='', max_length=20)),
                ('beneficiario_nome', models.CharField(blank=True, default='', max_length=200)),
                ('beneficiario_carteirinha', models.CharField(blank=True, default='', max_length=50)),
                ('tipo_atendimento', models.CharField(choices=[('consulta', 'Consulta'), ('exame', 'Exame / Diagnóstico'), ('internacao', 'Internação'), ('urgencia', 'Urgência / Emergência'), ('terapia', 'Terapia / Procedimento')], default='consulta', max_length=20)),
                ('procedimento', models.CharField(blank=True, default='', max_length=255)),
                ('praca_atendimento', models.CharField(blank=True, default='', help_text='Cidade/UF onde ocorreu o atendimento', max_length=120)),
                ('data_atendimento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('faturada', 'Faturada'), ('paga', 'Paga'), ('glosada', 'Glosada'), ('cancelada', 'Cancelada')], default='aberta', max_length=12)),
                ('data_faturamento', models.DateField(blank=True, null=True)),
                ('data_liquidacao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.ForeignKey(blank=True, help_text='Preenchido quando o beneficiário é da própria operadora (tipo=recebida)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercambios', to='api.beneficiarioplano')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_intercambio', to='api.empresa')),
            ],
            options={
                'ordering': ['-data_atendimento', '-criado_em'],
            },
        ),
    ]
