# Generated by Django 5.2.16 on 2026-07-30 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_guia_intercambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarioplano',
            name='contrato_grupo',
            field=models.ForeignKey(blank=True, help_text='Contrato corporativo (empresa-contratante) a que esta vida pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vidas', to='api.contratogrupo'),
        ),
        migrations.CreateModel(
            name='PortalRHToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateField(blank=True, null=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_rh_token', to='api.contratogrupo')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoVidaRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inclusao', 'Inclusão de vida'), ('exclusao', 'Exclusão de vida')], default='inclusao', max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, default='', max_length=14)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('grau_parentesco', models.CharField(blank=True, default='', max_length=12)),
                ('observacao', models.TextField(blank=True, default='')),
                ('resposta', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('beneficiario', models.ForeignKey(blank=True, help_text='Vida-alvo (exclusão) ou vida criada (inclusão aprovada)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_rh', to='api.beneficiarioplano')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_vida', to='api.contratogrupo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_vida_rh', to='api.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
