# Generated by Django 5.2.16 on 2026-07-30 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_portal_rh_b2b'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeApoioSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=10)),
                ('categoria', models.CharField(choices=[('psicologico', 'Apoio Psicológico'), ('psiquiatrico', 'Psiquiátrico'), ('juridico', 'Jurídico'), ('social', 'Assistência Social'), ('saude', 'Saúde / Médico'), ('financeiro', 'Orientação Financeira'), ('dependencia', 'Dependência Química'), ('outro', 'Outro')], default='psicologico', max_length=15)),
                ('contato', models.CharField(blank=True, default='', max_length=200)),
                ('telefone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('descricao', models.TextField(blank=True, default='')),
                ('disponibilidade', models.CharField(blank=True, default='', help_text='Ex: 24h, seg-sex 8-18h', max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rede_apoio_sst', to='api.empresa')),
            ],
            options={
                'ordering': ['categoria', 'nome'],
                'indexes': [models.Index(fields=['empresa', 'categoria'], name='api_redeapo_empresa_3ce358_idx')],
            },
        ),
    ]
