# Generated by Django 5.2.16 on 2026-07-30 19:02

import hashlib

from django.db import migrations, models


def _hashear_chaves_existentes(apps, schema_editor):
    """Popula chave_hash + chave_prefixo das chaves já existentes (a partir do
    valor cru) e APAGA o valor cru do banco — para nunca mais existir chave em
    texto puro armazenada. As chaves continuam válidas: a verificação passa a
    comparar por hash."""
    ApiKeyEmpresa = apps.get_model("api", "ApiKeyEmpresa")
    for k in ApiKeyEmpresa.objects.exclude(chave__isnull=True).exclude(chave=""):
        crua = k.chave
        k.chave_hash = hashlib.sha256(crua.encode()).hexdigest()
        k.chave_prefixo = crua[:8]
        k.chave = None  # remove a chave crua do banco
        k.save(update_fields=["chave_hash", "chave_prefixo", "chave"])


def _noop_reverse(apps, schema_editor):
    # Irreversível por design: não recriamos a chave crua a partir do hash.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_rede_apoio_sst'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeyempresa',
            name='chave_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='apikeyempresa',
            name='chave_prefixo',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='apikeyempresa',
            name='chave',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.RunPython(_hashear_chaves_existentes, _noop_reverse),
    ]
