# Generated by Django 5.2.16 on 2026-07-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_twofactor_totp'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactortotp',
            name='bloqueado_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twofactortotp',
            name='falhas_2fa',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
