# Generated by Django 5.2.16 on 2026-08-01 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_twofactor_stepup_throttle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReuniaoConselhoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reuniao', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('ordinaria', 'Ordinária'), ('extraordinaria', 'Extraordinária')], default='ordinaria', max_length=15)),
                ('pauta', models.TextField(blank=True, default='')),
                ('ata_texto', models.TextField(blank=True, default='')),
                ('presentes_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes_conselho_saude', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Reunião do Conselho de Saúde',
                'verbose_name_plural': 'Reuniões do Conselho de Saúde',
                'ordering': ['-data_reuniao'],
            },
        ),
        migrations.CreateModel(
            name='DeliberacaoConselhoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, default='', max_length=30)),
                ('tipo', models.CharField(choices=[('resolucao', 'Resolução'), ('recomendacao', 'Recomendação'), ('mocao', 'Moção')], default='resolucao', max_length=15)),
                ('texto', models.TextField()),
                ('votos_favor', models.PositiveSmallIntegerField(default=0)),
                ('votos_contra', models.PositiveSmallIntegerField(default=0)),
                ('votos_abstencao', models.PositiveSmallIntegerField(default=0)),
                ('aprovada', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberacoes_conselho_saude', to='api.empresa')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberacoes', to='api.reuniaoconselhosaude')),
            ],
            options={
                'verbose_name': 'Deliberação do Conselho de Saúde',
                'verbose_name_plural': 'Deliberações do Conselho de Saúde',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConselheiroSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('segmento', models.CharField(choices=[('usuarios', 'Usuários'), ('trabalhadores', 'Trabalhadores de Saúde'), ('gestores_prestadores', 'Gestores / Prestadores')], max_length=25)),
                ('titular', models.BooleanField(default=True, help_text='False = suplente')),
                ('entidade_representada', models.CharField(blank=True, default='', max_length=200)),
                ('mandato_inicio', models.DateField()),
                ('mandato_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conselheiros_saude', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Conselheiro de Saúde',
                'verbose_name_plural': 'Conselheiros de Saúde',
                'ordering': ['segmento', 'nome'],
                'indexes': [models.Index(fields=['empresa', 'ativo'], name='api_conselh_empresa_6336a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='EscalaProfissionalRede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissional_nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('medico', 'Médico'), ('enfermeiro', 'Enfermeiro'), ('tecnico_enfermagem', 'Técnico de Enfermagem'), ('odontologo', 'Odontólogo'), ('farmaceutico', 'Farmacêutico'), ('fisioterapeuta', 'Fisioterapeuta'), ('acs', 'Agente Comunitário de Saúde'), ('administrativo', 'Administrativo'), ('outro', 'Outro')], max_length=25)),
                ('cbo', models.CharField(blank=True, default='', max_length=10, verbose_name='CBO')),
                ('conselho_registro', models.CharField(blank=True, default='', help_text='Ex: CRM 12345, COREN 6789', max_length=30)),
                ('vinculo', models.CharField(choices=[('estatutario', 'Estatutário'), ('clt', 'CLT'), ('temporario', 'Temporário'), ('rt', 'Responsável Técnico'), ('cooperado', 'Cooperado')], default='estatutario', max_length=15)),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('plantao_12x36', 'Plantão 12x36'), ('plantao_24x72', 'Plantão 24x72')], default='manha', max_length=15)),
                ('dias_semana', models.JSONField(blank=True, default=list, help_text='Ex: ["seg","ter","qua","qui","sex"]')),
                ('carga_horaria_semanal', models.PositiveSmallIntegerField(default=40)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('afastado', 'Afastado'), ('desligado', 'Desligado')], default='ativo', max_length=15)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_rede', to='api.empresa')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_profissionais', to='api.unidadesaude')),
            ],
            options={
                'verbose_name': 'Escala de Profissional da Rede',
                'verbose_name_plural': 'Escalas de Profissionais da Rede',
                'ordering': ['profissional_nome'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_escalap_empresa_40c128_idx'), models.Index(fields=['empresa', 'unidade'], name='api_escalap_empresa_1941dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ManifestacaoOuvidoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(db_index=True, max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('reclamacao', 'Reclamação'), ('denuncia', 'Denúncia'), ('sugestao', 'Sugestão'), ('elogio', 'Elogio'), ('solicitacao', 'Solicitação de Informação')], max_length=15)),
                ('canal', models.CharField(choices=[('presencial', 'Presencial'), ('telefone', 'Telefone / 156'), ('app', 'App do Cidadão'), ('site', 'Site / Portal'), ('carta', 'Carta / Ofício')], default='app', max_length=15)),
                ('anonima', models.BooleanField(default=False)),
                ('manifestante_nome', models.CharField(blank=True, default='', max_length=150)),
                ('manifestante_cpf', models.CharField(blank=True, default='', max_length=14)),
                ('manifestante_telefone', models.CharField(blank=True, default='', max_length=20)),
                ('manifestante_email', models.EmailField(blank=True, default='', max_length=254)),
                ('descricao', models.TextField()),
                ('sigiloso', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em Análise'), ('respondida', 'Respondida'), ('encerrada', 'Encerrada')], default='aberta', max_length=15)),
                ('resposta', models.TextField(blank=True, default='')),
                ('respondido_por', models.CharField(blank=True, default='', max_length=150)),
                ('prazo_resposta', models.DateField(blank=True, help_text='LAI: 20 dias úteis, prorrogável por +10', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestacoes_ouvidoria', to='api.empresa')),
                ('unidade_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestacoes_ouvidoria', to='api.unidadesaude')),
            ],
            options={
                'verbose_name': 'Manifestação de Ouvidoria',
                'verbose_name_plural': 'Manifestações de Ouvidoria',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_manifes_empresa_47d508_idx'), models.Index(fields=['empresa', 'tipo'], name='api_manifes_empresa_c51467_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reuniaoconselhosaude',
            index=models.Index(fields=['empresa', 'status'], name='api_reuniao_empresa_f3216a_idx'),
        ),
    ]
