# Generated by Django 5.2.16 on 2026-08-01 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_governo_ouvidoria_conselho_escala'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoEticoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(db_index=True, max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('denuncia', 'Denúncia'), ('consulta_etica', 'Consulta Ética'), ('sindicancia', 'Sindicância')], max_length=20)),
                ('descricao', models.TextField()),
                ('medico_envolvido_nome', models.CharField(blank=True, default='', max_length=150)),
                ('medico_envolvido_crm', models.CharField(blank=True, default='', max_length=20)),
                ('sigiloso', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_analise', 'Em Análise'), ('parecer_emitido', 'Parecer Emitido'), ('arquivado', 'Arquivado')], default='aberto', max_length=20)),
                ('relator', models.CharField(blank=True, default='', max_length=150)),
                ('parecer_texto', models.TextField(blank=True, default='')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_parecer', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_eticos_medicos', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Caso Ético Médico',
                'verbose_name_plural': 'Casos Éticos Médicos',
                'ordering': ['-data_abertura'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_casoeti_empresa_a6809b_idx'), models.Index(fields=['empresa', 'tipo'], name='api_casoeti_empresa_8bf008_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogMensagemWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('internacao', 'Internação'), ('cirurgia', 'Cirurgia')], default='consulta', max_length=15)),
                ('enviado', models.BooleanField(default=False)),
                ('simulado', models.BooleanField(default=False)),
                ('acao', models.CharField(blank=True, choices=[('', 'Aguardando resposta'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('ignorado', 'Ignorado')], default='', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_whatsapp_agendamento', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Log de Mensagem WhatsApp',
                'verbose_name_plural': 'Logs de Mensagens WhatsApp',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'criado_em'], name='api_logmens_empresa_d378b4_idx'), models.Index(fields=['empresa', 'telefone'], name='api_logmens_empresa_583532_idx')],
            },
        ),
        migrations.CreateModel(
            name='MembroComissaoEtica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('crm', models.CharField(max_length=20)),
                ('cargo', models.CharField(choices=[('presidente', 'Presidente'), ('vice_presidente', 'Vice-Presidente'), ('secretario', 'Secretário'), ('membro', 'Membro')], default='membro', max_length=20)),
                ('mandato_inicio', models.DateField()),
                ('mandato_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_comissao_etica', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Membro da Comissão de Ética Médica',
                'verbose_name_plural': 'Membros da Comissão de Ética Médica',
                'ordering': ['cargo', 'nome'],
                'indexes': [models.Index(fields=['empresa', 'ativo'], name='api_membroc_empresa_927b88_idx')],
            },
        ),
    ]
