# Generated by Django 5.2.16 on 2026-08-01 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0179_hospital_whatsapp_e_comissao_etica'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('pontos_saldo', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_fidelidade', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Cliente Fidelidade',
                'verbose_name_plural': 'Clientes Fidelidade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acumulo', 'Acúmulo'), ('resgate', 'Resgate'), ('ajuste', 'Ajuste Manual')], max_length=10)),
                ('pontos', models.IntegerField(help_text='Positivo para acúmulo, negativo para resgate/ajuste de débito')),
                ('valor_referencia', models.DecimalField(decimal_places=2, default=0, help_text='Valor da venda (acúmulo) ou do desconto concedido (resgate)', max_digits=12)),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='api.clientefidelidade')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_fidelidade', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Transação de Fidelidade',
                'verbose_name_plural': 'Transações de Fidelidade',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='clientefidelidade',
            index=models.Index(fields=['empresa', 'cpf'], name='api_cliente_empresa_12b786_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientefidelidade',
            unique_together={('empresa', 'cpf')},
        ),
        migrations.AddIndex(
            model_name='transacaofidelidade',
            index=models.Index(fields=['empresa', 'cliente'], name='api_transac_empresa_65320d_idx'),
        ),
    ]
