# Generated by Django 5.2.16 on 2026-08-01 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_farmacia_fidelidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaComunicacaoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('publico_alvo', models.CharField(choices=[('todos', 'Todos os Beneficiários'), ('titulares', 'Apenas Titulares'), ('dependentes', 'Apenas Dependentes')], default='todos', max_length=15)),
                ('mensagem', models.TextField()),
                ('total_enviado', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas_comunicacao', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Campanha de Comunicação',
                'verbose_name_plural': 'Campanhas de Comunicação',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'criado_em'], name='api_campanh_empresa_8115e8_idx')],
            },
        ),
    ]
