# Generated by Django 5.2.16 on 2026-08-01 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_plano_campanha_comunicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuscaAtivaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_referencia', models.CharField(help_text='Nome de referência quando a família ainda não está cadastrada', max_length=150)),
                ('endereco_referencia', models.CharField(blank=True, default='', max_length=255)),
                ('motivo', models.CharField(choices=[('cadastro_desatualizado', 'CadÚnico Desatualizado'), ('descumprimento_condicionalidade', 'Descumprimento de Condicionalidade'), ('evasao_servico', 'Evasão de Serviço'), ('denuncia_conselho_tutelar', 'Denúncia / Conselho Tutelar'), ('criterio_territorial', 'Critério Territorial'), ('outro', 'Outro')], max_length=35)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_busca', 'Em Busca'), ('localizada', 'Localizada'), ('nao_localizada', 'Não Localizada')], default='pendente', max_length=15)),
                ('tecnico_responsavel', models.CharField(blank=True, default='', max_length=150)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_localizacao', models.DateField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, default='')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buscas_ativas_sociais', to='api.empresa')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buscas_ativas', to='api.familiacras')),
            ],
            options={
                'verbose_name': 'Busca Ativa',
                'verbose_name_plural': 'Buscas Ativas',
                'ordering': ['-data_inicio'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_buscaat_empresa_cc8efa_idx'), models.Index(fields=['empresa', 'motivo'], name='api_buscaat_empresa_4c56f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='EncaminhamentoConselhoTutelar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(db_index=True, max_length=30, unique=True)),
                ('crianca_nome', models.CharField(max_length=150)),
                ('crianca_data_nascimento', models.DateField(blank=True, null=True)),
                ('responsavel_nome', models.CharField(blank=True, default='', max_length=150)),
                ('tipo_violacao', models.CharField(choices=[('negligencia', 'Negligência'), ('violencia_fisica', 'Violência Física'), ('violencia_psicologica', 'Violência Psicológica'), ('violencia_sexual', 'Violência Sexual'), ('trabalho_infantil', 'Trabalho Infantil'), ('evasao_escolar', 'Evasão Escolar'), ('outro', 'Outro')], max_length=25)),
                ('descricao', models.TextField()),
                ('conselheiro_responsavel', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('encaminhado', 'Encaminhado'), ('em_acompanhamento', 'Em Acompanhamento'), ('concluido', 'Concluído')], default='encaminhado', max_length=20)),
                ('data_encaminhamento', models.DateTimeField(auto_now_add=True)),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('parecer_retorno', models.TextField(blank=True, default='')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaminhamentos_conselho_tutelar', to='api.empresa')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaminhamentos_conselho_tutelar', to='api.familiacras')),
            ],
            options={
                'verbose_name': 'Encaminhamento ao Conselho Tutelar',
                'verbose_name_plural': 'Encaminhamentos ao Conselho Tutelar',
                'ordering': ['-data_encaminhamento'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_encamin_empresa_8d7ee7_idx'), models.Index(fields=['empresa', 'tipo_violacao'], name='api_encamin_empresa_4b7247_idx')],
            },
        ),
        migrations.CreateModel(
            name='TerritorioVigilanciaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=150)),
                ('populacao_estimada', models.PositiveIntegerField(blank=True, null=True)),
                ('familias_cadunico', models.PositiveIntegerField(default=0)),
                ('familias_extrema_pobreza', models.PositiveIntegerField(default=0)),
                ('cobertura_cras', models.BooleanField(default=False, verbose_name='Possui CRAS de referência')),
                ('cobertura_creas', models.BooleanField(default=False, verbose_name='Possui CREAS de referência')),
                ('indice_vulnerabilidade', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('muito_alto', 'Muito Alto')], default='medio', max_length=12)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territorios_vigilancia_social', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Território de Vigilância Socioassistencial',
                'verbose_name_plural': 'Territórios de Vigilância Socioassistencial',
                'ordering': ['bairro'],
                'indexes': [models.Index(fields=['empresa', 'indice_vulnerabilidade'], name='api_territo_empresa_24b070_idx')],
                'unique_together': {('empresa', 'bairro')},
            },
        ),
    ]
