# Generated by Django 5.2.16 on 2026-08-01 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_assistencia_protecao_especial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroObitoMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falecido_nome', models.CharField(max_length=150)),
                ('falecido_cpf', models.CharField(blank=True, default='', max_length=14)),
                ('falecido_data_nascimento', models.DateField(blank=True, null=True)),
                ('data_obito', models.DateTimeField()),
                ('tipo_morte', models.CharField(choices=[('natural', 'Morte Natural'), ('nao_natural', 'Morte Não Natural (causas externas)')], default='natural', max_length=15)),
                ('causa_basica_cid', models.CharField(max_length=10)),
                ('causa_basica_descricao', models.TextField(blank=True, default='')),
                ('medico_atestante', models.CharField(blank=True, default='', max_length=150)),
                ('medico_crm', models.CharField(blank=True, default='', max_length=20)),
                ('numero_do', models.CharField(blank=True, default='', max_length=30, verbose_name='Número da DO')),
                ('status_transmissao', models.CharField(choices=[('pendente', 'Pendente'), ('transmitido', 'Transmitido ao SIM'), ('erro', 'Erro na Transmissão')], default='pendente', max_length=15)),
                ('transmitido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obitos_municipais', to='api.empresa')),
                ('unidade_saude', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obitos_municipais', to='api.unidadesaude')),
            ],
            options={
                'verbose_name': 'Registro de Óbito Municipal (SIM)',
                'verbose_name_plural': 'Registros de Óbito Municipal (SIM)',
                'ordering': ['-data_obito'],
                'indexes': [models.Index(fields=['empresa', 'status_transmissao'], name='api_registr_empresa_c1d125_idx'), models.Index(fields=['empresa', 'data_obito'], name='api_registr_empresa_5360dc_idx')],
            },
        ),
    ]
