# Generated by Django 5.2.16 on 2026-08-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_governo_sim_mortalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarioodonto',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Mensalidade odontológica por vida (R$). Base real do cálculo de MLR/receita.', max_digits=10),
        ),
    ]
