# Generated by Django 5.2.16 on 2026-08-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_beneficiarioodonto_valor_mensalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacaoopme',
            name='respondido_por',
            field=models.CharField(blank=True, default='', help_text='Operador que aprovou/negou (trilha de auditoria)', max_length=160),
        ),
    ]
