# Generated by Django 5.2.16 on 2026-08-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0185_autorizacaoopme_respondido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloquimioterapia',
            name='bilirrubina_mg_dl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cicloquimioterapia',
            name='clearance_creatinina',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Clearance de creatinina (mL/min)'),
        ),
        migrations.AddField(
            model_name='cicloquimioterapia',
            name='creatinina_mg_dl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cicloquimioterapia',
            name='data_prevista',
            field=models.DateField(blank=True, help_text='data_inicio + intervalo do protocolo — base do alerta de atraso', null=True, verbose_name='Data prevista do próximo ciclo'),
        ),
        migrations.AddField(
            model_name='cicloquimioterapia',
            name='doses_calculadas',
            field=models.JSONField(blank=True, default=list, verbose_name='Doses calculadas (mg) por droga, com caps'),
        ),
        migrations.AddField(
            model_name='cicloquimioterapia',
            name='motivo_adiamento',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Motivo de adiamento (clínico/administrativo/logístico)'),
        ),
        migrations.AddField(
            model_name='cicloquimioterapia',
            name='neutrofilos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Neutrófilos (/mm³)'),
        ),
        migrations.AddField(
            model_name='cicloquimioterapia',
            name='plaquetas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Plaquetas (/mm³)'),
        ),
        migrations.AlterField(
            model_name='cicloquimioterapia',
            name='altura_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
