# Generated by Django 5.2.16 on 2026-08-13 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_cicloquimioterapia_bilirrubina_mg_dl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohospitalarcancer',
            name='cns_paciente',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AddField(
            model_name='registrohospitalarcancer',
            name='cpf_paciente',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='registrohospitalarcancer',
            name='identidade',
            field=models.ForeignKey(blank=True, help_text='Identidade única do paciente (MPI) — liga RHC à quimio/radio/APAC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rhc_mpi', to='api.identidadepaciente'),
        ),
        migrations.AddField(
            model_name='sessaoradioterapia',
            name='cns_paciente',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AddField(
            model_name='sessaoradioterapia',
            name='cpf_paciente',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='sessaoradioterapia',
            name='identidade',
            field=models.ForeignKey(blank=True, help_text='Identidade única do paciente (MPI) — liga radio à quimio/RHC/APAC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radioterapia_mpi', to='api.identidadepaciente'),
        ),
    ]
