# Generated by Django 5.2.16 on 2026-08-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0187_registrohospitalarcancer_cns_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apaconcologia',
            name='autorizador_nome',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='apaconcologia',
            name='carater_atendimento',
            field=models.CharField(choices=[('1', 'Eletivo'), ('2', 'Urgência')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='apaconcologia',
            name='cnes_executante',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='CNES do estabelecimento executante'),
        ),
        migrations.AddField(
            model_name='apaconcologia',
            name='cnes_solicitante',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='CNES do estabelecimento solicitante'),
        ),
        migrations.AddField(
            model_name='apaconcologia',
            name='competencia_final',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Competência final de validade (APAC vale até 3)'),
        ),
        migrations.AddField(
            model_name='apaconcologia',
            name='data_autorizacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apaconcologia',
            name='data_solicitacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apaconcologia',
            name='competencia',
            field=models.CharField(max_length=6, verbose_name='Competência inicial AAAAMM'),
        ),
    ]
