# Generated by Django 5.2.16 on 2026-08-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_apaconcologia_autorizador_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacaoopme',
            name='alertas_triagem',
            field=models.JSONField(blank=True, default=list, verbose_name='Alertas da triagem automática'),
        ),
        migrations.AddField(
            model_name='autorizacaoopme',
            name='ia_decisao',
            field=models.CharField(blank=True, default='', help_text='Recomendação do motor de IA: aprovada/negada/revisao', max_length=12),
        ),
        migrations.AddField(
            model_name='autorizacaoopme',
            name='ia_justificativa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='autorizacaoopme',
            name='ia_score',
            field=models.FloatField(blank=True, help_text='Confiança da recomendação de IA (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='autorizacaoopme',
            name='procedimento_tuss',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Procedimento TUSS/SIGTAP vinculado'),
        ),
        migrations.AddField(
            model_name='catalogoopme',
            name='homologado',
            field=models.BooleanField(default=True, verbose_name='Homologado pela operadora/comissão'),
        ),
        migrations.AddField(
            model_name='catalogoopme',
            name='preferencial',
            field=models.BooleanField(default=False, verbose_name='Material preferencial (padrão de menor custo)'),
        ),
        migrations.AddField(
            model_name='itemautorizacaoopme',
            name='alerta_triagem',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='itemautorizacaoopme',
            name='fora_padrao',
            field=models.BooleanField(default=False, verbose_name='Sinalizado fora do padrão pela triagem'),
        ),
        migrations.AddField(
            model_name='itemautorizacaoopme',
            name='preco_solicitado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço solicitado (para comparar com o teto)'),
        ),
        migrations.AlterField(
            model_name='cicloquimioterapia',
            name='motivo_adiamento',
            field=models.CharField(blank=True, choices=[('clinico', 'Clínico (toxicidade/condição do paciente)'), ('administrativo', 'Administrativo (guia/autorização)'), ('logistico', 'Logístico (falta de droga/agenda)')], default='', max_length=20, verbose_name='Motivo de adiamento'),
        ),
        migrations.CreateModel(
            name='GuiaOncologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(max_length=160)),
                ('cpf_paciente', models.CharField(blank=True, default='', max_length=11)),
                ('cns_paciente', models.CharField(blank=True, default='', max_length=18)),
                ('numero_guia', models.CharField(max_length=40, verbose_name='Número da guia/autorização')),
                ('tipo', models.CharField(choices=[('quimioterapia', 'Quimioterapia'), ('radioterapia', 'Radioterapia'), ('geral', 'Tratamento oncológico')], default='quimioterapia', max_length=15)),
                ('operadora', models.CharField(blank=True, default='', max_length=120)),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField(verbose_name='Válida até')),
                ('ciclos_autorizados', models.PositiveSmallIntegerField(default=0, help_text='0 = sem limite de ciclos')),
                ('ciclos_utilizados', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('vencida', 'Vencida'), ('esgotada', 'Esgotada (ciclos consumidos)'), ('cancelada', 'Cancelada')], default='vigente', max_length=12)),
                ('obs', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_oncologicas', to='api.empresa')),
                ('identidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_oncologicas_mpi', to='api.identidadepaciente')),
            ],
            options={
                'verbose_name': 'Guia Oncológica',
                'verbose_name_plural': 'Guias Oncológicas',
                'ordering': ['data_validade'],
            },
        ),
        migrations.AddField(
            model_name='cicloquimioterapia',
            name='guia',
            field=models.ForeignKey(blank=True, help_text='Guia/autorização que cobre este ciclo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos', to='api.guiaoncologica'),
        ),
        migrations.CreateModel(
            name='OPMEProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tuss', models.CharField(max_length=10, verbose_name='Código TUSS/SIGTAP')),
                ('descricao', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opme_procedimentos', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Procedimento OPME',
                'verbose_name_plural': 'Procedimentos OPME',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='OPMEProcedimentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_maxima', models.PositiveIntegerField(default=1)),
                ('preferencial', models.BooleanField(default=False, verbose_name='Material preferencial para este procedimento')),
                ('opme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos_permitidos', to='api.catalogoopme')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_permitidos', to='api.opmeprocedimento')),
            ],
            options={
                'verbose_name': 'Item permitido por procedimento',
                'verbose_name_plural': 'Itens permitidos por procedimento',
            },
        ),
        migrations.AddIndex(
            model_name='guiaoncologica',
            index=models.Index(fields=['empresa', 'status'], name='api_guiaonc_empresa_1bcbb0_idx'),
        ),
        migrations.AddIndex(
            model_name='guiaoncologica',
            index=models.Index(fields=['empresa', 'data_validade'], name='api_guiaonc_empresa_a3ea6d_idx'),
        ),
        migrations.AddIndex(
            model_name='guiaoncologica',
            index=models.Index(fields=['cpf_paciente'], name='api_guiaonc_cpf_pac_f28fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='opmeprocedimento',
            index=models.Index(fields=['empresa', 'codigo_tuss'], name='api_opmepro_empresa_1485c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opmeprocedimento',
            unique_together={('empresa', 'codigo_tuss')},
        ),
        migrations.AlterUniqueTogether(
            name='opmeprocedimentoitem',
            unique_together={('procedimento', 'opme')},
        ),
    ]
