# Generated by Django 5.2.16 on 2026-08-14 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0189_autorizacaoopme_alertas_triagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuntaMedicaOPME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_divergencia', models.TextField(help_text='Por que a operadora diverge da marca/material indicado pelo médico assistente.', verbose_name='Motivo da divergência técnica')),
                ('marcas_alternativas_oferecidas', models.JSONField(blank=True, default=list, verbose_name='Marcas alternativas oferecidas')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em Análise'), ('resolvida_medico', 'Resolvida — Mantida Indicação do Médico'), ('resolvida_operadora', 'Resolvida — Acatada Alternativa da Operadora'), ('cancelada', 'Cancelada')], default='aberta', max_length=25)),
                ('parecer', models.TextField(blank=True, default='', verbose_name='Parecer da junta')),
                ('aberta_por', models.CharField(blank=True, default='', max_length=160)),
                ('resolvida_por', models.CharField(blank=True, default='', max_length=160)),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Junta Médica OPME (RN 424/ANS)',
                'verbose_name_plural': 'Juntas Médicas OPME (RN 424/ANS)',
                'ordering': ['-aberta_em'],
            },
        ),
        migrations.AddField(
            model_name='autorizacaoopme',
            name='alertas_fraude',
            field=models.JSONField(blank=True, default=list, verbose_name='Alertas de padrão atípico/fraude'),
        ),
        migrations.AddField(
            model_name='autorizacaoopme',
            name='tem_alerta_fraude',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='catalogoopme',
            name='codigo_operadora',
            field=models.CharField(blank=True, default='', help_text='Codificação própria da operadora (ex.: TNU da Unimed), quando diferente da TUSS/ANVISA/SIGTAP.', max_length=40, verbose_name='Código da Operadora'),
        ),
        migrations.AddField(
            model_name='catalogoopme',
            name='data_validade_registro_anvisa',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do Registro ANVISA'),
        ),
        migrations.AddField(
            model_name='catalogoopme',
            name='grupo_equivalencia',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Itens com o mesmo valor aqui são considerados clinicamente intercambiáveis — usado para oferecer marcas/fabricantes alternativos (RN 424/ANS, Junta Médica).', max_length=60, verbose_name='Grupo de Equivalência Clínica'),
        ),
        migrations.AddIndex(
            model_name='catalogoopme',
            index=models.Index(fields=['empresa', 'grupo_equivalencia'], name='api_catalog_empresa_e26a54_idx'),
        ),
        migrations.AddField(
            model_name='juntamedicaopme',
            name='autorizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juntas_medicas', to='api.autorizacaoopme'),
        ),
        migrations.AddField(
            model_name='juntamedicaopme',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juntas_medicas_opme', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='juntamedicaopme',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juntas_medicas', to='api.itemautorizacaoopme'),
        ),
        migrations.AddIndex(
            model_name='juntamedicaopme',
            index=models.Index(fields=['empresa', 'status'], name='api_juntame_empresa_00c730_idx'),
        ),
    ]
