# Generated by Django 5.2.16 on 2026-08-14 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0190_opme_rn424_tnu_anvisa_fraude'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemautorizacaoopme',
            name='economia_aplicada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Economia obtida na substituição (R$)'),
        ),
        migrations.AddField(
            model_name='itemautorizacaoopme',
            name='substituido_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituicoes', to='api.catalogoopme', verbose_name='Material originalmente escolhido'),
        ),
    ]
