# Generated by Django 5.2.16 on 2026-08-15 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_opme_economia_substituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoopme',
            name='codigo_operadora',
            field=models.CharField(blank=True, default='', help_text='Codificação própria da operadora/plano, quando diferente da TUSS/ANVISA/SIGTAP.', max_length=40, verbose_name='Código da Operadora'),
        ),
        migrations.CreateModel(
            name='EmpresaAfeAnvisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, max_length=14)),
                ('razao_social', models.CharField(blank=True, default='', max_length=250)),
                ('numero_afe', models.CharField(blank=True, default='', max_length=40)),
                ('ativo', models.BooleanField(default=True)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AFE ANVISA (Empresa)',
                'verbose_name_plural': 'AFEs ANVISA (Empresas)',
                'indexes': [models.Index(fields=['cnpj', 'ativo'], name='api_empresa_cnpj_cf2d0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistroAnvisaProdutoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nome_produto', models.CharField(blank=True, default='', max_length=300)),
                ('detentor', models.CharField(blank=True, default='', max_length=250)),
                ('cnpj_detentor', models.CharField(blank=True, default='', max_length=14)),
                ('classe_risco', models.CharField(blank=True, default='', max_length=4)),
                ('situacao', models.CharField(blank=True, default='', help_text='Válido / Inválido / Em validação', max_length=20)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro ANVISA (Produto p/ Saúde)',
                'verbose_name_plural': 'Registros ANVISA (Produtos p/ Saúde)',
                'indexes': [models.Index(fields=['situacao'], name='api_registr_situaca_c170a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='FornecedorHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=200)),
                ('cnpj', models.CharField(blank=True, db_index=True, default='', max_length=14)),
                ('contato', models.CharField(blank=True, default='', max_length=150)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('afe_numero', models.CharField(blank=True, default='', max_length=40, verbose_name='Nº da AFE (ANVISA)')),
                ('afe_situacao', models.CharField(blank=True, default='', help_text='ativa / inativa / não encontrada', max_length=20)),
                ('afe_verificada_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_hospital', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Fornecedor Hospital',
                'verbose_name_plural': 'Fornecedores Hospital',
                'ordering': ['razao_social'],
                'indexes': [models.Index(fields=['empresa', 'cnpj'], name='api_fornece_empresa_05e2d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportacaoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(help_text='Chave do alvo de importação (ex.: catalogo_opme)', max_length=40)),
                ('arquivo_nome', models.CharField(blank=True, default='', max_length=255)),
                ('colunas_arquivo', models.JSONField(blank=True, default=list)),
                ('amostra', models.JSONField(blank=True, default=list)),
                ('linhas_brutas', models.JSONField(blank=True, default=list)),
                ('mapeamento', models.JSONField(blank=True, default=dict, help_text='campo_destino → coluna_arquivo')),
                ('status', models.CharField(choices=[('mapeando', 'Aguardando mapeamento'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='mapeando', max_length=15)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
                ('linhas_ok', models.PositiveIntegerField(default=0)),
                ('linhas_erro', models.PositiveIntegerField(default=0)),
                ('erros', models.JSONField(blank=True, default=list, help_text='[{linha, mensagem}] das que falharam')),
                ('criado_por', models.CharField(blank=True, default='', max_length=160)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importacoes_dados', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Importação de Dados',
                'verbose_name_plural': 'Importações de Dados',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'destino'], name='api_importa_empresa_1bacce_idx')],
            },
        ),
    ]
