# Generated by Django 5.2.16 on 2026-08-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_hospital_anvisa_import_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoopme',
            name='especificacoes',
            field=models.TextField(blank=True, default='', help_text='Fixação, dimensões, revestimento, indicação — o que a comissão considera na equivalência clínica.', verbose_name='Especificações técnicas'),
        ),
        migrations.AddField(
            model_name='catalogoopme',
            name='material',
            field=models.CharField(blank=True, default='', help_text='Ex.: Titânio, Cromo-cobalto, PEEK, Cerâmica…', max_length=150, verbose_name='Material / composição'),
        ),
    ]
