# Generated by Django 5.2.16 on 2026-08-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_opme_atributos_clinicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacaoopme',
            name='ia_parecer_auditoria',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='autorizacaoopme',
            name='ia_recomendacao',
            field=models.JSONField(blank=True, default=dict, help_text='Substituição sugerida (mesma qualidade, menor custo)'),
        ),
        migrations.AddField(
            model_name='autorizacaoopme',
            name='via_rapida',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Pré-aprovado automaticamente (Via Rápida)'),
        ),
    ]
