# Generated by Django 5.2.16 on 2026-08-16 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_opme_via_rapida_ia_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacaoopme',
            name='etapa',
            field=models.CharField(choices=[('solicitacao', 'Solicitação médica'), ('analise_adm', 'Análise administrativa'), ('auditoria', 'Auditoria técnica e médica'), ('junta', 'Junta médica (RN 424)'), ('autorizacao', 'Autorização'), ('cotacao', 'Cotação / Aquisição'), ('dispensacao', 'Recebimento / Dispensação'), ('implante', 'Implante / Utilização'), ('rastreabilidade', 'Rastreabilidade'), ('faturamento', 'Faturamento TISS'), ('concluido', 'Concluído')], db_index=True, default='solicitacao', max_length=20, verbose_name='Etapa atual na esteira'),
        ),
        migrations.CreateModel(
            name='EtapaHistoricoOPME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('solicitacao', 'Solicitação médica'), ('analise_adm', 'Análise administrativa'), ('auditoria', 'Auditoria técnica e médica'), ('junta', 'Junta médica (RN 424)'), ('autorizacao', 'Autorização'), ('cotacao', 'Cotação / Aquisição'), ('dispensacao', 'Recebimento / Dispensação'), ('implante', 'Implante / Utilização'), ('rastreabilidade', 'Rastreabilidade'), ('faturamento', 'Faturamento TISS'), ('concluido', 'Concluído')], max_length=20)),
                ('situacao', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída / Liberada'), ('pendencia', 'Pendência / Diligência'), ('reprovada', 'Reprovada'), ('dispensada', 'Dispensada (Via Rápida)')], default='em_andamento', max_length=15)),
                ('responsavel', models.CharField(blank=True, default='', help_text='Quem atuou (nome)', max_length=160)),
                ('papel', models.CharField(blank=True, default='', help_text='Papel/setor: médico assistente, auditor, suprimentos…', max_length=80)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autorizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_etapas', to='api.autorizacaoopme')),
            ],
            options={
                'verbose_name': 'Histórico de Etapa OPME',
                'verbose_name_plural': 'Histórico de Etapas OPME',
                'ordering': ['criado_em', 'id'],
                'indexes': [models.Index(fields=['autorizacao', 'criado_em'], name='api_etapahi_autoriz_d73b97_idx')],
            },
        ),
    ]
