# Generated by Django 5.2.16 on 2026-08-16 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_opme_esteira_processo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloIAArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(db_index=True, help_text='Chave da área: opme, oncologia, …', max_length=40)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('n_amostras', models.PositiveIntegerField(default=0, verbose_name='Decisões reais usadas no treino')),
                ('acuracia_f1', models.FloatField(blank=True, null=True, verbose_name='F1 (validação cruzada)')),
                ('dataset_sintetico', models.BooleanField(default=True, help_text='True = ainda em bootstrap (poucos dados reais)')),
                ('classes', models.JSONField(blank=True, default=list)),
                ('arquivo', models.CharField(blank=True, default='', max_length=300)),
                ('treinado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_ia_area', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Modelo de IA por Área',
                'verbose_name_plural': 'Modelos de IA por Área',
                'indexes': [models.Index(fields=['empresa', 'area'], name='api_modeloi_empresa_172c4f_idx')],
                'unique_together': {('empresa', 'area')},
            },
        ),
    ]
