# Generated by Django 5.2.16 on 2026-08-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0196_modelo_ia_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminologiaTuss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.CharField(db_index=True, help_text='Código da tabela TUSS, ex.: tuss-19, tuss-22', max_length=12)),
                ('tabela_nome', models.CharField(blank=True, default='', max_length=120)),
                ('codigo', models.CharField(db_index=True, help_text='Código TUSS do item (id do conceito)', max_length=20)),
                ('descricao', models.CharField(blank=True, default='', max_length=400)),
                ('registro_anvisa', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('fabricante', models.CharField(blank=True, default='', help_text='Fabricante (OPME) ou laboratório (medicamento)', max_length=250)),
                ('classe_risco', models.CharField(blank=True, default='', max_length=8)),
                ('apresentacao', models.CharField(blank=True, default='', max_length=250)),
                ('modelo', models.CharField(blank=True, default='', max_length=250)),
                ('inicio_vigencia', models.DateField(blank=True, null=True)),
                ('fim_vigencia', models.DateField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True, help_text='False quando a ANS marcou fim de vigência')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terminologia TUSS (ANS)',
                'verbose_name_plural': 'Terminologias TUSS (ANS)',
                'indexes': [models.Index(fields=['tabela', 'vigente'], name='api_termino_tabela_7fd59c_idx'), models.Index(fields=['tabela', 'registro_anvisa'], name='api_termino_tabela_c18626_idx')],
                'unique_together': {('tabela', 'codigo')},
            },
        ),
    ]
