# Generated by Django 5.2.16 on 2026-08-18 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_terminologiatuss'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecificacaoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(help_text='Código interno do produto (SKU industrial)', max_length=60)),
                ('nome', models.CharField(max_length=200)),
                ('forma_farmaceutica', models.CharField(choices=[('comprimido', 'Comprimido'), ('capsula', 'Cápsula'), ('solucao', 'Solução'), ('suspensao', 'Suspensão'), ('pomada', 'Pomada / Creme'), ('injetavel', 'Injetável'), ('xarope', 'Xarope'), ('granulado', 'Granulado'), ('outro', 'Outra forma farmacêutica')], default='comprimido', max_length=20)),
                ('concentracao', models.CharField(blank=True, default='', help_text='Ex.: 500 mg, 10 mg/mL', max_length=120)),
                ('versao', models.PositiveSmallIntegerField(default=1, help_text='Versão do MBR — troca gera nova versão')),
                ('ativo', models.BooleanField(default=True)),
                ('unidade_rendimento', models.CharField(default='unid', help_text='unid, kg, L, comprimidos', max_length=15)),
                ('tamanho_lote_padrao', models.DecimalField(decimal_places=3, default=1, help_text='Tamanho do lote de referência do MBR', max_digits=14)),
                ('rendimento_teorico', models.DecimalField(decimal_places=3, default=0, help_text='Rendimento teórico para o lote padrão', max_digits=14)),
                ('faixa_rendimento_min', models.DecimalField(decimal_places=2, default=98, help_text='Limite inferior de rendimento aceitável (%)', max_digits=5)),
                ('faixa_rendimento_max', models.DecimalField(decimal_places=2, default=102, help_text='Limite superior de rendimento aceitável (%)', max_digits=5)),
                ('etapas', models.JSONField(default=list, help_text='Etapas ordenadas da linha. Cada uma: {"chave","rotulo","papel_assina"}')),
                ('campos', models.JSONField(default=list, help_text='Campos da ordem com faixa de aceitação (min/max)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificacoes_producao', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Especificação de Produção',
                'verbose_name_plural': 'Especificações de Produção',
                'ordering': ['nome', '-versao'],
            },
        ),
        migrations.CreateModel(
            name='OrdemProducaoIndustrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_op', models.CharField(help_text='Número da ordem de produção', max_length=40)),
                ('numero_lote_fabricacao', models.CharField(blank=True, default='', help_text='Lote de fabricação do produto', max_length=60)),
                ('tamanho_lote', models.DecimalField(decimal_places=3, default=0, help_text='Tamanho do lote desta ordem', max_digits=14)),
                ('unidade', models.CharField(default='unid', max_length=15)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho — em abertura'), ('em_producao', 'Em produção'), ('controle_qualidade', 'Em controle de qualidade'), ('revisao_qualidade', 'Revisão da Garantia da Qualidade'), ('liberado', 'Liberado — lote aprovado'), ('rejeitado', 'Rejeitado — reprovado no CQ/GQ'), ('cancelado', 'Cancelado')], default='rascunho', max_length=25)),
                ('etapa_atual', models.CharField(blank=True, default='', help_text='Chave da etapa corrente da linha', max_length=40)),
                ('rendimento_real', models.DecimalField(blank=True, decimal_places=3, help_text='Rendimento efetivamente obtido', max_digits=14, null=True)),
                ('rendimento_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Rendimento real / teórico (%)', max_digits=6, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, default='', help_text='Responsável pela ordem', max_length=160)),
                ('criado_por', models.CharField(blank=True, default='', max_length=160)),
                ('bloqueada', models.BooleanField(default=False, help_text='Impedida de avançar por desvio não resolvido')),
                ('motivo_bloqueio', models.CharField(blank=True, default='', max_length=300)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_producao_industrial', to='api.empresa')),
                ('especificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='api.especificacaoproducao')),
            ],
            options={
                'verbose_name': 'Ordem de Produção Industrial',
                'verbose_name_plural': 'Ordens de Produção Industrial',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DesvioProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('faixa', 'Valor fora da faixa de aceitação'), ('calculo', 'Erro de cálculo / reconciliação de rendimento'), ('campo_ausente', 'Campo obrigatório não preenchido'), ('sequencia', 'Tentativa de avanço fora de sequência'), ('assinatura', 'Assinatura ausente na etapa'), ('anomalia_ia', 'Anomalia estatística sinalizada pela IA')], max_length=20)),
                ('severidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('etapa', models.CharField(blank=True, default='', max_length=40)),
                ('campo', models.CharField(blank=True, default='', max_length=60)),
                ('valor_encontrado', models.CharField(blank=True, default='', max_length=120)),
                ('valor_esperado', models.CharField(blank=True, default='', max_length=120)),
                ('descricao', models.TextField()),
                ('detectado_por', models.CharField(choices=[('sistema', 'Validação do sistema'), ('ia', 'Motor de IA'), ('usuario', 'Apontado por usuário')], default='sistema', max_length=10)),
                ('resolvido', models.BooleanField(default=False)),
                ('resolucao', models.TextField(blank=True, default='')),
                ('resolvido_por', models.CharField(blank=True, default='', max_length=160)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desvios_producao', to='api.empresa')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desvios', to='api.ordemproducaoindustrial')),
            ],
            options={
                'verbose_name': 'Desvio de Produção',
                'verbose_name_plural': 'Desvios de Produção',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaEtapaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=40)),
                ('papel', models.CharField(choices=[('operador', 'Operador — executou'), ('supervisor', 'Supervisor — conferiu'), ('farmaceutico_qa', 'Farmacêutico / GQ — liberou')], default='operador', max_length=20)),
                ('assinante_nome', models.CharField(max_length=160)),
                ('assinante_registro', models.CharField(blank=True, default='', help_text='CRF / matrícula do assinante', max_length=40)),
                ('conteudo_assinado', models.TextField(blank=True, default='', help_text='Snapshot canônico do que foi assinado')),
                ('assinatura_b64', models.TextField(blank=True, default='')),
                ('hash_documento', models.CharField(blank=True, default='', max_length=80)),
                ('metodo', models.CharField(blank=True, default='', help_text='ICP-Brasil-PKCS7 | SHA256', max_length=30)),
                ('assinado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_producao', to='api.empresa')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='api.ordemproducaoindustrial')),
            ],
            options={
                'verbose_name': 'Assinatura de Etapa de Produção',
                'verbose_name_plural': 'Assinaturas de Etapa de Produção',
                'ordering': ['ordem', 'etapa'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCampoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_campo', models.CharField(max_length=60)),
                ('rotulo', models.CharField(blank=True, default='', max_length=160)),
                ('etapa', models.CharField(blank=True, default='', max_length=40)),
                ('tipo', models.CharField(default='numero', max_length=20)),
                ('valor', models.TextField(blank=True, default='')),
                ('unidade', models.CharField(blank=True, default='', max_length=15)),
                ('status_validacao', models.CharField(choices=[('pendente', 'Pendente'), ('ok', 'OK — dentro da faixa'), ('alerta', 'Alerta — revisar'), ('erro', 'Erro — fora da faixa')], default='pendente', max_length=12)),
                ('fora_faixa', models.BooleanField(default=False)),
                ('mensagem_validacao', models.CharField(blank=True, default='', max_length=300)),
                ('valor_min_esperado', models.CharField(blank=True, default='', max_length=40)),
                ('valor_max_esperado', models.CharField(blank=True, default='', max_length=40)),
                ('preenchido_por', models.CharField(blank=True, default='', max_length=160)),
                ('preenchido_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_campo_producao', to='api.empresa')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='api.ordemproducaoindustrial')),
            ],
            options={
                'verbose_name': 'Registro de Campo de Produção',
                'verbose_name_plural': 'Registros de Campo de Produção',
                'ordering': ['etapa', 'chave_campo'],
            },
        ),
        migrations.AddIndex(
            model_name='especificacaoproducao',
            index=models.Index(fields=['empresa', 'ativo'], name='api_especif_empresa_46ca2e_idx'),
        ),
        migrations.AddIndex(
            model_name='especificacaoproducao',
            index=models.Index(fields=['empresa', 'codigo_produto'], name='api_especif_empresa_7bdf6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='especificacaoproducao',
            unique_together={('empresa', 'codigo_produto', 'versao')},
        ),
        migrations.AddIndex(
            model_name='ordemproducaoindustrial',
            index=models.Index(fields=['empresa', 'status'], name='api_ordempr_empresa_0a7f89_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemproducaoindustrial',
            index=models.Index(fields=['empresa', 'numero_op'], name='api_ordempr_empresa_ffa616_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemproducaoindustrial',
            index=models.Index(fields=['numero_lote_fabricacao'], name='api_ordempr_numero__1e6de4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ordemproducaoindustrial',
            unique_together={('empresa', 'numero_op')},
        ),
        migrations.AddIndex(
            model_name='desvioproducao',
            index=models.Index(fields=['empresa', 'resolvido'], name='api_desviop_empresa_813369_idx'),
        ),
        migrations.AddIndex(
            model_name='desvioproducao',
            index=models.Index(fields=['ordem', 'severidade'], name='api_desviop_ordem_i_0f8013_idx'),
        ),
        migrations.AddIndex(
            model_name='assinaturaetapaproducao',
            index=models.Index(fields=['ordem', 'etapa'], name='api_assinat_ordem_i_bfaaa4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assinaturaetapaproducao',
            unique_together={('ordem', 'etapa', 'papel')},
        ),
        migrations.AddIndex(
            model_name='registrocampoproducao',
            index=models.Index(fields=['ordem', 'etapa'], name='api_registr_ordem_i_15eeca_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocampoproducao',
            index=models.Index(fields=['ordem', 'status_validacao'], name='api_registr_ordem_i_ea3aaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registrocampoproducao',
            unique_together={('ordem', 'chave_campo')},
        ),
    ]
