# Generated by Django 5.2.16 on 2026-08-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_especificacaoproducao_ordemproducaoindustrial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desvioproducao',
            name='acao_corretiva',
            field=models.TextField(blank=True, default='', help_text='O que foi feito para corrigir agora'),
        ),
        migrations.AddField(
            model_name='desvioproducao',
            name='acao_preventiva',
            field=models.TextField(blank=True, default='', help_text='O que evita a recorrência'),
        ),
        migrations.AddField(
            model_name='desvioproducao',
            name='categoria_causa',
            field=models.CharField(blank=True, choices=[('humano', 'Erro humano / operação'), ('processo', 'Processo / procedimento'), ('equipamento', 'Equipamento / instrumento'), ('material', 'Material / insumo'), ('sistema', 'Sistema / digitação'), ('outro', 'Outro')], default='', max_length=15),
        ),
    ]
