# Generated by Django 5.2.16 on 2026-08-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_desvioproducao_acao_corretiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducaoindustrial',
            name='cq_aprovado',
            field=models.BooleanField(blank=True, help_text='Resultado derivado do CQ industrial. None=pendente, True=aprovado, False=reprovado.', null=True),
        ),
        migrations.AddField(
            model_name='ordemproducaoindustrial',
            name='cq_resultado_json',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot das medições e resultado derivado pelo CQ industrial.'),
        ),
    ]
