# Generated by Django 5.2.16 on 2026-08-18 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0200_ordemproducao_cq_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadProspeccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(choices=[('sst', 'SST / Medicina do Trabalho'), ('farmacia', 'Farmácia')], max_length=20)),
                ('tipo', models.CharField(choices=[('medico_trabalho', 'Médico do Trabalho'), ('engenheiro_sst', 'Engenheiro de SST'), ('tecnico_sst', 'Técnico de SST'), ('clinica_ocupacional', 'Clínica de Medicina Ocupacional'), ('empresa_sesmt', 'Empresa com SESMT'), ('farmacia_dispensacao', 'Farmácia de Dispensação'), ('farmacia_manipulacao', 'Farmácia de Manipulação'), ('rede_farmacia', 'Rede de Farmácias')], max_length=30)),
                ('nome', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('website', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('email_enviado', 'Email Enviado'), ('followup_1', 'Follow-up 1'), ('followup_2', 'Follow-up 2'), ('followup_final', 'Follow-up Final'), ('respondeu', 'Respondeu!'), ('demo_agendada', 'Demo Agendada'), ('trial', 'Em Trial'), ('cliente', 'Cliente'), ('descartado', 'Descartado'), ('bounce', 'Email Inválido'), ('unsubscribe', 'Descadastrado')], default='novo', max_length=20)),
                ('score', models.IntegerField(default=50, help_text='0=frio, 100=quente')),
                ('notas', models.TextField(blank=True, default='')),
                ('dados_adicionais', models.JSONField(blank=True, default=dict)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV Importado'), ('google_places', 'Google Places'), ('linkedin', 'LinkedIn Search'), ('indicacao', 'Indicação')], default='manual', max_length=20)),
                ('ultimo_contato_em', models.DateTimeField(blank=True, null=True)),
                ('proximo_followup_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead de Prospecção',
                'verbose_name_plural': 'Leads de Prospecção',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status'], name='api_leadpro_status_68192c_idx'), models.Index(fields=['segmento', 'status'], name='api_leadpro_segment_c71345_idx'), models.Index(fields=['proximo_followup_em'], name='api_leadpro_proximo_9ac646_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailProspeccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sequencia', models.IntegerField(default=1)),
                ('assunto', models.CharField(max_length=300)),
                ('corpo_html', models.TextField()),
                ('corpo_texto', models.TextField(blank=True, default='')),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('aberto_em', models.DateTimeField(blank=True, null=True)),
                ('clicou_em', models.DateTimeField(blank=True, null=True)),
                ('respondeu_em', models.DateTimeField(blank=True, null=True)),
                ('sendgrid_message_id', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('aberto', 'Aberto'), ('clicado', 'Clicado'), ('respondeu', 'Respondeu'), ('bounce', 'Bounce'), ('spam', 'Spam'), ('erro', 'Erro')], default='rascunho', max_length=20)),
                ('erro', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='api.leadprospeccao')),
            ],
            options={
                'verbose_name': 'Email de Prospecção',
                'verbose_name_plural': 'Emails de Prospecção',
                'ordering': ['criado_em'],
            },
        ),
    ]
