# Generated by Django 5.2.16 on 2026-08-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_leadprospeccao_emailprospeccao'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospeccao',
            name='funcionarios_estimados',
            field=models.IntegerField(blank=True, help_text='Nº de colaboradores — dimensiona o plano SST sugerido', null=True),
        ),
        migrations.AddField(
            model_name='leadprospeccao',
            name='unidades_estimadas',
            field=models.IntegerField(blank=True, help_text='Nº de lojas/unidades — dimensiona o plano de Farmácia sugerido', null=True),
        ),
    ]
