# Generated by Django 5.2.16 on 2026-08-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0202_leadprospeccao_funcionarios_estimados_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailprospeccao',
            old_name='sendgrid_message_id',
            new_name='provedor_message_id',
        ),
    ]
