# Generated by Django 5.2.16 on 2026-08-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_rename_sendgrid_message_id_emailprospeccao_provedor_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadprospeccao',
            name='segmento',
            field=models.CharField(choices=[('sst', 'SST / Medicina do Trabalho'), ('farmacia', 'Farmácia'), ('hospital', 'Hospital'), ('plano_saude', 'Plano de Saúde')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leadprospeccao',
            name='tipo',
            field=models.CharField(choices=[('medico_trabalho', 'Médico do Trabalho'), ('engenheiro_sst', 'Engenheiro de SST'), ('tecnico_sst', 'Técnico de SST'), ('clinica_ocupacional', 'Clínica de Medicina Ocupacional'), ('empresa_sesmt', 'Empresa com SESMT'), ('farmacia_dispensacao', 'Farmácia de Dispensação'), ('farmacia_manipulacao', 'Farmácia de Manipulação'), ('rede_farmacia', 'Rede de Farmácias'), ('hospital_geral', 'Hospital Geral'), ('hospital_especializado', 'Hospital Especializado'), ('rede_hospitalar', 'Rede Hospitalar'), ('santa_casa', 'Santa Casa / Filantrópico'), ('operadora_plano', 'Operadora de Plano de Saúde'), ('cooperativa_medica', 'Cooperativa Médica'), ('autogestao', 'Autogestão'), ('seguradora_saude', 'Seguradora de Saúde')], max_length=30),
        ),
        migrations.CreateModel(
            name='LicitacaoOportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_controle_pncp', models.CharField(help_text='ID único da contratação no PNCP', max_length=60, unique=True)),
                ('objeto', models.TextField()),
                ('orgao', models.CharField(blank=True, default='', max_length=300)),
                ('municipio', models.CharField(blank=True, default='', max_length=150)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('modalidade', models.CharField(blank=True, default='', max_length=80)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('data_abertura', models.DateTimeField(blank=True, help_text='Abertura das propostas / fim do prazo', null=True)),
                ('link_origem', models.URLField(blank=True, default='', max_length=600)),
                ('area', models.CharField(choices=[('saude', 'Saúde / Governo'), ('assistencia', 'Assistência Social / SUAS'), ('ambos', 'Saúde + Assistência')], default='saude', max_length=20)),
                ('palavras_match', models.CharField(blank=True, default='', help_text='Termos que casaram no filtro', max_length=300)),
                ('status', models.CharField(choices=[('nova', 'Nova'), ('analisando', 'Analisando'), ('respondendo', 'Preparando proposta'), ('enviada', 'Proposta enviada'), ('ganha', 'Ganhamos!'), ('perdida', 'Perdida'), ('descartada', 'Descartada (fora de escopo)')], default='nova', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('dados_adicionais', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oportunidade de Licitação',
                'verbose_name_plural': 'Oportunidades de Licitação',
                'ordering': ['-data_publicacao', '-criado_em'],
                'indexes': [models.Index(fields=['status'], name='api_licitac_status_e733e7_idx'), models.Index(fields=['area', 'status'], name='api_licitac_area_2e9a59_idx'), models.Index(fields=['data_abertura'], name='api_licitac_data_ab_0c8827_idx')],
            },
        ),
    ]
