# Generated by Django 5.2.16 on 2026-08-21 19:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0204_alter_leadprospeccao_segmento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteTISSRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(blank=True, default='', max_length=40)),
                ('prestador_codigo', models.CharField(blank=True, default='', max_length=40)),
                ('prestador_nome', models.CharField(blank=True, default='', max_length=200)),
                ('prestador_cnes', models.CharField(blank=True, default='', max_length=20)),
                ('beneficiario_carteirinha', models.CharField(blank=True, default='', max_length=40)),
                ('beneficiario_nome', models.CharField(blank=True, default='', max_length=120)),
                ('guia_numero', models.CharField(blank=True, default='', max_length=40)),
                ('cid10', models.CharField(blank=True, default='', max_length=10)),
                ('versao_tiss', models.CharField(default='3.05.00', max_length=12)),
                ('hash_tiss', models.CharField(blank=True, default='', max_length=64)),
                ('hash_confere', models.BooleanField(default=True)),
                ('valor_apresentado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valor_glosado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valor_liberado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('ia_score_glosa', models.PositiveSmallIntegerField(default=0)),
                ('ia_parecer', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('processado', 'Processado'), ('retornado', 'Retornado'), ('erro', 'Erro')], default='recebido', max_length=15)),
                ('xml_original', models.TextField(blank=True, default='')),
                ('xml_retorno', models.TextField(blank=True, default='')),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_tiss_recebidos', to='api.empresa')),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_tiss', to='api.prestadorplanosaude')),
            ],
            options={
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemContaTISS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencial', models.PositiveIntegerField(default=1)),
                ('codigo_tabela', models.CharField(blank=True, default='', max_length=6)),
                ('codigo_procedimento', models.CharField(blank=True, default='', max_length=20)),
                ('descricao', models.CharField(blank=True, default='', max_length=250)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valor_apresentado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valor_glosado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valor_liberado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('glosado', models.BooleanField(default=False)),
                ('codigo_glosa', models.CharField(blank=True, default='', max_length=10)),
                ('motivo_glosa', models.CharField(blank=True, default='', max_length=250)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.lotetissrecebido')),
            ],
            options={
                'ordering': ['lote', 'sequencial'],
            },
        ),
        migrations.AddIndex(
            model_name='lotetissrecebido',
            index=models.Index(fields=['empresa', 'status'], name='api_lotetis_empresa_b89bcc_idx'),
        ),
    ]
