# Generated by Django 5.2.16 on 2026-08-21 19:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_lotetissrecebido_itemcontatiss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotePagamentoPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestador_nome', models.CharField(blank=True, default='', max_length=200)),
                ('competencia', models.CharField(default='', max_length=7)),
                ('qtd_lotes', models.PositiveIntegerField(default=0)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valor_glosa', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('ia_anomalia_score', models.PositiveSmallIntegerField(default=0)),
                ('ia_anomalia_parecer', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('fechado', 'Fechado'), ('aprovado', 'Aprovado'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='fechado', max_length=12)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'PIX'), ('ted', 'TED'), ('boleto', 'Boleto')], default='', max_length=8)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('comprovante', models.CharField(blank=True, default='', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_prestador', to='api.empresa')),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='api.prestadorplanosaude')),
            ],
            options={
                'ordering': ['-competencia', 'prestador_nome'],
            },
        ),
        migrations.AddField(
            model_name='lotetissrecebido',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_incluidos', to='api.lotepagamentoprestador'),
        ),
        migrations.AddIndex(
            model_name='lotepagamentoprestador',
            index=models.Index(fields=['empresa', 'competencia', 'status'], name='api_lotepag_empresa_3fe8b1_idx'),
        ),
    ]
