# Generated by Django 5.2.16 on 2026-08-21 20:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0206_lotepagamentoprestador_lotetissrecebido_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalPrestadorToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateField(blank=True, null=True)),
                ('prestador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_token', to='api.prestadorplanosaude')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RecursoGlosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_glosa', models.CharField(blank=True, default='', max_length=10)),
                ('valor_contestado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valor_deferido', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('ia_merito_score', models.PositiveSmallIntegerField(default=0)),
                ('ia_merito_parecer', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_analise', 'Em análise'), ('deferido', 'Deferido'), ('parcial', 'Deferido parcial'), ('indeferido', 'Indeferido')], default='aberto', max_length=12)),
                ('resposta_operadora', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_glosa', to='api.empresa')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='api.itemcontatiss')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='api.lotetissrecebido')),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_glosa', to='api.prestadorplanosaude')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_recurso_empresa_12cab5_idx')],
            },
        ),
    ]
