# Generated by Django 5.2.16 on 2026-08-21 20:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0207_portalprestadortoken_recursoglosa'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCoparticipacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(default='', max_length=7)),
                ('tipo_atendimento', models.CharField(default='', max_length=20)),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('valor_procedimento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('percentual_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('valor_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('valor_coparticipacao', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('isento', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_coparticipacao', to='api.beneficiarioplano')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_coparticipacao', to='api.empresa')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_coparticipacao', to='api.planosaude')),
                ('regra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='api.coparticipacaoregra')),
            ],
            options={
                'ordering': ['-competencia', 'beneficiario'],
                'indexes': [models.Index(fields=['empresa', 'beneficiario', 'competencia'], name='api_eventoc_empresa_7ffea9_idx')],
            },
        ),
    ]
