# Generated by Django 5.2.16 on 2026-08-21 20:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0208_eventocoparticipacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarioplano',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Mensalidade desta vida (por faixa etária); somada no titular para a fatura', max_digits=10),
        ),
        migrations.AddField(
            model_name='faturamentobeneficiario',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
        migrations.AddField(
            model_name='faturamentobeneficiario',
            name='forma_cobranca',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='faturamentobeneficiario',
            name='linha_digitavel',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='faturamentobeneficiario',
            name='nosso_numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='faturamentobeneficiario',
            name='pix_copia_cola',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='faturamentobeneficiario',
            name='pix_txid',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.CreateModel(
            name='RemessaCNAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('remessa', 'Remessa'), ('retorno', 'Retorno')], default='remessa', max_length=8)),
                ('competencia', models.CharField(default='', max_length=7)),
                ('banco', models.CharField(blank=True, default='', max_length=5)),
                ('qtd_titulos', models.PositiveIntegerField(default=0)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('conciliados', models.PositiveIntegerField(default=0)),
                ('arquivo', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remessas_cnab', to='api.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
