# Generated by Django 5.2.16 on 2026-08-22 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0209_beneficiarioplano_valor_mensalidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialAppPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('fcm_token', models.TextField(blank=True, default='')),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('identidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credencial_portal', to='api.identidadepaciente')),
            ],
            options={
                'verbose_name': 'Credencial do Portal do Paciente',
                'verbose_name_plural': 'Credenciais do Portal do Paciente',
                'ordering': ['-criado_em'],
            },
        ),
    ]
