# Generated by Django 5.2.16 on 2026-08-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0210_credencialapppaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('exame', 'Exame'), ('retorno', 'Retorno'), ('vacina', 'Vacina'), ('procedimento', 'Procedimento')], default='consulta', max_length=20)),
                ('especialidade', models.CharField(blank=True, default='', max_length=120)),
                ('profissional', models.CharField(blank=True, default='', max_length=160)),
                ('local', models.CharField(blank=True, default='', help_text='Unidade/sala', max_length=160)),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_paciente', to='api.empresa')),
                ('identidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='api.identidadepaciente')),
            ],
            options={
                'verbose_name': 'Agendamento do Paciente',
                'verbose_name_plural': 'Agendamentos do Paciente',
                'ordering': ['data_hora'],
                'indexes': [models.Index(fields=['empresa', 'identidade', 'data_hora'], name='api_agendam_empresa_0f180a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MensagemPacientePortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(choices=[('paciente', 'Paciente'), ('equipe', 'Equipe')], max_length=10)),
                ('autor_nome', models.CharField(blank=True, default='', max_length=160)),
                ('texto', models.TextField()),
                ('lida_paciente', models.BooleanField(default=False)),
                ('lida_equipe', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_paciente_portal', to='api.empresa')),
                ('identidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_portal', to='api.identidadepaciente')),
            ],
            options={
                'verbose_name': 'Mensagem do Portal do Paciente',
                'verbose_name_plural': 'Mensagens do Portal do Paciente',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['empresa', 'identidade', 'criado_em'], name='api_mensage_empresa_4a7e46_idx')],
            },
        ),
    ]
