# Generated by Django 5.2.16 on 2026-08-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0212_biometria_totem_hospitalar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotemDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Identificação física — ex: 'Recepção Térreo', 'PS - Box 2'", max_length=120)),
                ('tipo', models.CharField(choices=[('totem', 'Totem de Check-in (recepção)'), ('ps', 'Triagem PS (enfermagem)')], default='totem', max_length=10)),
                ('token', models.CharField(db_index=True, help_text='Segredo de pareamento — vai na URL do kiosk', max_length=64, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispositivo de Totem',
                'verbose_name_plural': 'Dispositivos de Totem',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.RenameIndex(
            model_name='totemcheckinlog',
            new_name='api_totemch_empresa_86f60e_idx',
            old_name='api_totem_checkin_emp_idx',
        ),
        migrations.RenameIndex(
            model_name='triagemmanchesterps',
            new_name='api_triagem_empresa_204e50_idx',
            old_name='api_triagem_manchester_cor_idx',
        ),
        migrations.RenameIndex(
            model_name='triagemmanchesterps',
            new_name='api_triagem_empresa_60cd28_idx',
            old_name='api_triagem_manchester_dt_idx',
        ),
        migrations.AlterField(
            model_name='biometriatotempaciente',
            name='assinatura_base64',
            field=models.TextField(blank=True, default='', help_text='Assinatura digital PNG em base64 — aplicada automaticamente nas guias'),
        ),
        migrations.AlterField(
            model_name='biometriatotempaciente',
            name='consentimento_lgpd',
            field=models.BooleanField(default=False, help_text='Paciente autorizou uso da biometria e da assinatura automática'),
        ),
        migrations.AlterField(
            model_name='biometriatotempaciente',
            name='embedding_json',
            field=models.JSONField(help_text='Vetor ArcFace 512D normalizado — busca por similaridade cosseno'),
        ),
        migrations.AlterField(
            model_name='totemcheckinlog',
            name='id_temporario',
            field=models.CharField(blank=True, default='', help_text='ID temporário para emergências sem cadastro — ex: PS-2026-0847', max_length=30),
        ),
        migrations.AlterField(
            model_name='triagemmanchesterps',
            name='cor_classificacao',
            field=models.CharField(choices=[('vermelho', '🔴 Vermelho — Emergência imediata'), ('laranja', '🟠 Laranja   — Muito urgente (≤ 10 min)'), ('amarelo', '🟡 Amarelo   — Urgente (≤ 30 min)'), ('verde', '🟢 Verde     — Pouco urgente (≤ 120 min)'), ('azul', '🔵 Azul      — Não urgente')], max_length=10),
        ),
        migrations.AddField(
            model_name='totemdispositivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totem_dispositivos', to='api.empresa'),
        ),
        migrations.AddIndex(
            model_name='totemdispositivo',
            index=models.Index(fields=['empresa', 'ativo'], name='api_totemdi_empresa_5c03d9_idx'),
        ),
    ]
