# Generated by Django 5.2.16 on 2026-08-23 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0213_totemdispositivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totemcheckinlog',
            name='senha_atendimento',
            field=models.CharField(blank=True, default='', help_text='Senha de atendimento (fila) gerada no check-in — ex: A042', max_length=12),
        ),
        migrations.CreateModel(
            name='ConvenioPacienteTotem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operadora', models.CharField(blank=True, default='', max_length=150)),
                ('plano_nome', models.CharField(blank=True, default='', max_length=150)),
                ('numero_carteirinha', models.CharField(blank=True, default='', max_length=60)),
                ('validade', models.DateField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('identidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convenio_totem', to='api.identidadepaciente')),
            ],
            options={
                'verbose_name': 'Convênio do Paciente (Totem)',
                'verbose_name_plural': 'Convênios do Paciente (Totem)',
            },
        ),
    ]
