# Generated by Django 5.2.16 on 2026-08-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0214_totemcheckinlog_senha_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometriatotempaciente',
            name='foto_thumb_base64',
            field=models.TextField(blank=True, default='', help_text='Miniatura do rosto (JPEG base64) para identificação visual no painel de operação'),
        ),
    ]
