# Generated by Django 5.2.16 on 2026-08-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0215_biometriatotempaciente_foto_thumb_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometriatotempaciente',
            name='embeddings_extra',
            field=models.JSONField(blank=True, default=list, help_text='Vetores ArcFace adicionais (outras câmeras/ângulos) — melhora o match entre dispositivos'),
        ),
        migrations.AlterField(
            model_name='biometriatotempaciente',
            name='embedding_json',
            field=models.JSONField(help_text='Vetor ArcFace 512D normalizado (principal) — busca por similaridade cosseno'),
        ),
    ]
