# Generated by Django 5.2.16 on 2026-08-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0216_biometriatotempaciente_embeddings_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotetissrecebido',
            name='biometria_score',
            field=models.FloatField(default=0.0, help_text='Similaridade facial no check-in de origem (0-1)'),
        ),
        migrations.AddField(
            model_name='lotetissrecebido',
            name='biometria_verificada',
            field=models.BooleanField(default=False, help_text='Guia veio de hospital SoloCRT com paciente verificado por biometria facial'),
        ),
        migrations.AddField(
            model_name='totemcheckinlog',
            name='biometria_token',
            field=models.CharField(blank=True, default='', help_text='Selo biométrico assinado (prova de reconhecimento facial) para viajar com a guia TISS', max_length=400),
        ),
    ]
