# Generated by Django 5.2.16 on 2026-08-23 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0217_lotetissrecebido_biometria_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoExameVita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('laboratorio', 'Laboratório'), ('imagem', 'Imagem / Radiologia'), ('outro', 'Outro')], default='laboratorio', max_length=15)),
                ('exames', models.JSONField(default=list, help_text='[{"nome":..., "codigo_tuss":...}]')),
                ('estacao', models.CharField(blank=True, default='', help_text='Ex: Laboratório - Coleta 1, Radiologia - Sala 2', max_length=120)),
                ('medico_solicitante', models.CharField(blank=True, default='', max_length=200)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado pelo médico'), ('autorizado', 'Autorizado pelo plano'), ('aguardando', 'Aguardando paciente na estação'), ('em_atendimento', 'Em atendimento'), ('realizado', 'Realizado / Coletado'), ('concluido', 'Concluído (resultado ao médico)'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('autorizacao_solicitada', models.BooleanField(default=False, help_text='Autorização pedida ao plano automaticamente')),
                ('biometria_token', models.CharField(blank=True, default='', help_text='Selo biométrico para a autorização/guia', max_length=400)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_exame_vita', to='api.totemcheckinlog')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_exame_vita', to='api.empresa')),
                ('identidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_exame_vita', to='api.identidadepaciente')),
            ],
            options={
                'verbose_name': 'Pedido de Exame (VITA)',
                'verbose_name_plural': 'Pedidos de Exame (VITA)',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_pedidoe_empresa_ce6f5d_idx'), models.Index(fields=['identidade', 'status'], name='api_pedidoe_identid_96c58d_idx')],
            },
        ),
    ]
