# Generated by Django 5.2.16 on 2026-08-23 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0218_pedidoexamevita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChegadaPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('atendido', models.BooleanField(default=False)),
                ('detectado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chegadas_ps', to='api.empresa')),
                ('identidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chegadas_ps', to='api.identidadepaciente')),
            ],
            options={
                'verbose_name': 'Chegada no PS (câmera passiva)',
                'verbose_name_plural': 'Chegadas no PS (câmera passiva)',
                'ordering': ['-detectado_em'],
                'indexes': [models.Index(fields=['empresa', 'detectado_em'], name='api_chegada_empresa_7f1420_idx')],
            },
        ),
    ]
