# Generated by Django 5.2.16 on 2026-08-23 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0219_chegadaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarioplano',
            name='face_embedding',
            field=models.JSONField(blank=True, help_text='Vetor ArcFace 512D do beneficiário — login por rosto', null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioplano',
            name='face_thumb_base64',
            field=models.TextField(blank=True, default='', help_text='Miniatura do rosto para exibição'),
        ),
        migrations.CreateModel(
            name='PortalFacialOperadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_facial', to='api.empresa')),
            ],
        ),
    ]
