# Generated by Django 5.2.16 on 2026-08-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0220_beneficiarioplano_face_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoexamevita',
            name='resultado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoexamevita',
            name='resultado_interpretacao',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('alterado', 'Alterado'), ('critico', 'Crítico'), ('inconclusivo', 'Inconclusivo')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='pedidoexamevita',
            name='resultado_laudo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pedidoexamevita',
            name='resultado_por',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pedidoexamevita',
            name='resultado_visto',
            field=models.BooleanField(default=False, help_text='Médico já visualizou o resultado'),
        ),
    ]
