# Generated by Django 5.2.16 on 2026-08-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0221_pedidoexamevita_resultado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='betha_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='betha_token_cripto',
            field=models.TextField(blank=True, default='', help_text='Token de API Betha criptografado (Fernet)'),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='betha_url',
            field=models.URLField(blank=True, default='', help_text='URL base da API Betha do município'),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='drg_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='drg_token_cripto',
            field=models.TextField(blank=True, default='', help_text='Token Sigquali criptografado (Fernet)'),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='drg_url',
            field=models.URLField(blank=True, default='', help_text='URL da API Sigquali/DRG Brasil'),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='epimed_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='epimed_token_cripto',
            field=models.TextField(blank=True, default='', help_text='Token Epimed criptografado (Fernet)'),
        ),
        migrations.AddField(
            model_name='credenciaisintegracoes',
            name='epimed_url',
            field=models.URLField(blank=True, default='', help_text='URL da API Epimed Monitor'),
        ),
    ]
