# Generated by Django 5.2.16 on 2026-08-30 01:38
# + migração de dados: cifra em repouso os certificados PKCS#12 que estavam em claro.

import api.crypto_fields
from django.db import migrations


# (tabela, coluna) dos certificados que passam a ser cifrados
_ALVOS = [
    ("api_configuracaosst", "certificado_pfx_b64"),
    ("api_credenciaisintegracoes", "nfe_certificado_pfx_b64"),
    ("api_credenciaisintegracoes", "rnds_certificado_pfx_b64"),
]


def _cifra_existentes(apps, schema_editor):
    from api.crypto_fields import encrypt_text, _is_encrypted
    conn = schema_editor.connection
    with conn.cursor() as cur:
        for tabela, coluna in _ALVOS:
            cur.execute(f"SELECT id, {coluna} FROM {tabela} WHERE {coluna} IS NOT NULL AND {coluna} <> ''")
            linhas = cur.fetchall()
            for pk, valor in linhas:
                if valor and not _is_encrypted(valor):
                    cur.execute(
                        f"UPDATE {tabela} SET {coluna} = %s WHERE id = %s",
                        [encrypt_text(valor), pk],
                    )


def _decifra_existentes(apps, schema_editor):
    from api.crypto_fields import decrypt_text, _is_encrypted
    conn = schema_editor.connection
    with conn.cursor() as cur:
        for tabela, coluna in _ALVOS:
            cur.execute(f"SELECT id, {coluna} FROM {tabela} WHERE {coluna} IS NOT NULL AND {coluna} <> ''")
            linhas = cur.fetchall()
            for pk, valor in linhas:
                if valor and _is_encrypted(valor):
                    cur.execute(
                        f"UPDATE {tabela} SET {coluna} = %s WHERE id = %s",
                        [decrypt_text(valor), pk],
                    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0222_credenciaisintegracoes_betha_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosst',
            name='certificado_pfx_b64',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='credenciaisintegracoes',
            name='nfe_certificado_pfx_b64',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='credenciaisintegracoes',
            name='rnds_certificado_pfx_b64',
            field=api.crypto_fields.EncryptedTextField(blank=True, default='', help_text='Certificado ICP-Brasil A1/A3 (PKCS#12 base64) — cifrado em repouso'),
        ),
        migrations.RunPython(_cifra_existentes, _decifra_existentes),
    ]
