# Generated by Django 5.2.16 on 2026-08-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0224_rls_cobertura_completa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='rbac_estrito',
            field=models.BooleanField(default=False),
        ),
    ]
