# Generated by Django 5.2.16 on 2026-08-30 01:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0225_empresa_rbac_estrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_tipo', models.CharField(default='sistema', max_length=40)),
                ('principal_id', models.CharField(blank=True, default='', max_length=80)),
                ('principal_nome', models.CharField(blank=True, default='', max_length=160)),
                ('acao', models.CharField(choices=[('visualizar', 'Visualização'), ('criar', 'Criação'), ('alterar', 'Alteração'), ('assinar', 'Assinatura'), ('exportar', 'Exportação')], max_length=20)),
                ('recurso', models.CharField(help_text='Tipo do dado clínico (prontuario, evolucao, exame...)', max_length=60)),
                ('recurso_id', models.CharField(blank=True, default='', max_length=80)),
                ('paciente_ref', models.CharField(blank=True, default='', help_text='Identificador do paciente cujo dado foi acessado', max_length=120)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hash_anterior', models.CharField(blank=True, default='', max_length=64)),
                ('hash_registro', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_clinicas', to='api.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'criado_em'], name='api_auditor_empresa_62c9bf_idx'), models.Index(fields=['empresa', 'recurso', 'recurso_id'], name='api_auditor_empresa_f8627d_idx'), models.Index(fields=['empresa', 'paciente_ref'], name='api_auditor_empresa_e172d2_idx')],
            },
        ),
    ]
