# Generated by Django 5.2.16 on 2026-08-30 03:28
# + migração de dados: cifra em repouso o texto clínico que estava em claro.

import api.crypto_fields
from django.db import migrations


_ALVOS = [
    ("api_evolucaoprontuario", "texto"),
    ("api_prontuariohospitalar", "alergias"),
    ("api_prontuariohospitalar", "comorbidades"),
    ("api_prontuariohospitalar", "observacoes"),
]


def _cifra(apps, schema_editor):
    from api.crypto_fields import encrypt_text, _is_encrypted
    conn = schema_editor.connection
    with conn.cursor() as cur:
        for tabela, coluna in _ALVOS:
            cur.execute(f"SELECT id, {coluna} FROM {tabela} WHERE {coluna} IS NOT NULL AND {coluna} <> ''")
            for pk, valor in cur.fetchall():
                if valor and not _is_encrypted(valor):
                    cur.execute(f"UPDATE {tabela} SET {coluna} = %s WHERE id = %s", [encrypt_text(valor), pk])


def _decifra(apps, schema_editor):
    from api.crypto_fields import decrypt_text, _is_encrypted
    conn = schema_editor.connection
    with conn.cursor() as cur:
        for tabela, coluna in _ALVOS:
            cur.execute(f"SELECT id, {coluna} FROM {tabela} WHERE {coluna} IS NOT NULL AND {coluna} <> ''")
            for pk, valor in cur.fetchall():
                if valor and _is_encrypted(valor):
                    cur.execute(f"UPDATE {tabela} SET {coluna} = %s WHERE id = %s", [decrypt_text(valor), pk])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0226_auditoria_clinica_imutavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucaoprontuario',
            name='texto',
            field=api.crypto_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='prontuariohospitalar',
            name='alergias',
            field=api.crypto_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prontuariohospitalar',
            name='comorbidades',
            field=api.crypto_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prontuariohospitalar',
            name='observacoes',
            field=api.crypto_fields.EncryptedTextField(blank=True),
        ),
        migrations.RunPython(_cifra, _decifra),
    ]
