# Generated by Django 5.2.16 on 2026-08-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0227_cifra_texto_clinico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoclinicogov',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita Médica'), ('atestado', 'Atestado Médico'), ('exame', 'Solicitação de Exame'), ('evolucao', 'Evolução Clínica')], max_length=20),
        ),
    ]
