# Generated by Django 5.2.16 on 2026-08-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0228_alter_documentoclinicogov_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaoceo',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em aberto'), ('fechado', 'Fechado'), ('aguardando_transmissao', 'Aguardando transmissão (SCNS)'), ('transmitido', 'Transmitido'), ('erro', 'Erro na transmissão')], default='aberto', max_length=24),
        ),
        migrations.AlterField(
            model_name='registroobitomunicipal',
            name='status_transmissao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_transmissao', 'Aguardando transmissão (SCNS)'), ('transmitido', 'Transmitido ao SIM'), ('erro', 'Erro na Transmissão')], default='pendente', max_length=24),
        ),
    ]
