# Generated by Django 5.2.16 on 2026-08-31 15:52
# + migração de dados: cifra em repouso o texto sensível de SUAS (violência/ECA)
# e do prontuário do cidadão (Governo) que estava em claro. Molde da 0227.

import api.crypto_fields
from django.db import migrations


_ALVOS = [
    ("api_atendimentocreas", "descricao"),
    ("api_atendimentocreas", "encaminhamento"),
    ("api_atendimentocreas", "plano_atendimento"),
    ("api_encaminhamentoconselhotutelar", "descricao"),
    ("api_encaminhamentoconselhotutelar", "parecer_retorno"),
    ("api_prontuariocidadao", "alergias"),
    ("api_prontuariocidadao", "condicoes_cronicas"),
    ("api_prontuariosocialpaif", "encaminhamentos"),
    ("api_prontuariosocialpaif", "evolucao"),
    ("api_prontuariosocialpaif", "objetivos"),
    ("api_prontuariosocialpaif", "plano_acao_familiar"),
]


def _cifra(apps, schema_editor):
    from api.crypto_fields import encrypt_text, _is_encrypted
    conn = schema_editor.connection
    with conn.cursor() as cur:
        for tabela, coluna in _ALVOS:
            cur.execute(f"SELECT id, {coluna} FROM {tabela} WHERE {coluna} IS NOT NULL AND {coluna} <> ''")
            for pk, valor in cur.fetchall():
                if valor and not _is_encrypted(valor):
                    cur.execute(f"UPDATE {tabela} SET {coluna} = %s WHERE id = %s", [encrypt_text(valor), pk])


def _decifra(apps, schema_editor):
    from api.crypto_fields import decrypt_text, _is_encrypted
    conn = schema_editor.connection
    with conn.cursor() as cur:
        for tabela, coluna in _ALVOS:
            cur.execute(f"SELECT id, {coluna} FROM {tabela} WHERE {coluna} IS NOT NULL AND {coluna} <> ''")
            for pk, valor in cur.fetchall():
                if valor and _is_encrypted(valor):
                    cur.execute(f"UPDATE {tabela} SET {coluna} = %s WHERE id = %s", [decrypt_text(valor), pk])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0229_alter_producaoceo_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentocreas',
            name='descricao',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='encaminhamento',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='atendimentocreas',
            name='plano_atendimento',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='encaminhamentoconselhotutelar',
            name='descricao',
            field=api.crypto_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='encaminhamentoconselhotutelar',
            name='parecer_retorno',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prontuariocidadao',
            name='alergias',
            field=api.crypto_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prontuariocidadao',
            name='condicoes_cronicas',
            field=api.crypto_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prontuariosocialpaif',
            name='encaminhamentos',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prontuariosocialpaif',
            name='evolucao',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prontuariosocialpaif',
            name='objetivos',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prontuariosocialpaif',
            name='plano_acao_familiar',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.RunPython(_cifra, _decifra),
    ]
