# Generated by Django 5.2.16 on 2026-08-31 16:42
# + data migration: cifra em repouso texto clínico livre de Plano e SST que
# estava em claro. Molde da 0227/0230. Só campos NÃO usados em query.

import api.crypto_fields
from django.db import migrations


_ALVOS = [
    ("api_exameocupacional", "resultado"),
    ("api_exameocupacional", "observacoes"),
    ("api_asoocupacional", "restricoes"),
    ("api_asoocupacional", "observacoes"),
    ("api_afastamentosst", "observacoes"),
    ("api_guiaautorizacao", "descricao_procedimento"),
    ("api_guiaautorizacao", "observacao_auditoria"),
    ("api_guiaautorizacao", "justificativa_negativa"),
    ("api_sinistro", "descricao_procedimento"),
    ("api_sinistro", "observacao"),
    ("api_reembolso", "descricao"),
    ("api_reembolso", "observacao"),
]


def _cifra(apps, schema_editor):
    from api.crypto_fields import encrypt_text, _is_encrypted
    conn = schema_editor.connection
    with conn.cursor() as cur:
        for tabela, coluna in _ALVOS:
            cur.execute(f"SELECT id, {coluna} FROM {tabela} WHERE {coluna} IS NOT NULL AND {coluna} <> ''")
            for pk, valor in cur.fetchall():
                if valor and not _is_encrypted(valor):
                    cur.execute(f"UPDATE {tabela} SET {coluna} = %s WHERE id = %s", [encrypt_text(valor), pk])


def _decifra(apps, schema_editor):
    from api.crypto_fields import decrypt_text, _is_encrypted
    conn = schema_editor.connection
    with conn.cursor() as cur:
        for tabela, coluna in _ALVOS:
            cur.execute(f"SELECT id, {coluna} FROM {tabela} WHERE {coluna} IS NOT NULL AND {coluna} <> ''")
            for pk, valor in cur.fetchall():
                if valor and _is_encrypted(valor):
                    cur.execute(f"UPDATE {tabela} SET {coluna} = %s WHERE id = %s", [decrypt_text(valor), pk])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0230_cifra_dados_sensiveis_suas_governo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afastamentosst',
            name='observacoes',
            field=api.crypto_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asoocupacional',
            name='observacoes',
            field=api.crypto_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asoocupacional',
            name='restricoes',
            field=api.crypto_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exameocupacional',
            name='observacoes',
            field=api.crypto_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exameocupacional',
            name='resultado',
            field=api.crypto_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guiaautorizacao',
            name='descricao_procedimento',
            field=api.crypto_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='guiaautorizacao',
            name='justificativa_negativa',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='guiaautorizacao',
            name='observacao_auditoria',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='descricao',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='observacao',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='descricao_procedimento',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sinistro',
            name='observacao',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.RunPython(_cifra, _decifra),
    ]
