# Generated by Django 5.2.16 on 2026-08-31 17:49

import api.crypto_fields
from django.db import migrations


_ALVOS = [
    ("api_pacientefarmacia", "alergias"),
    ("api_pacientefarmacia", "condicoes_cronicas"),
    ("api_pacientefarmacia", "medicamentos_uso_continuo"),
    ("api_dispensacaomedicamento", "observacoes"),
    ("api_dispensacao", "observacoes"),
]


def _cifra(apps, schema_editor):
    from api.crypto_fields import encrypt_text, _is_encrypted
    with schema_editor.connection.cursor() as cur:
        for tabela, coluna in _ALVOS:
            cur.execute(f"SELECT id, {coluna} FROM {tabela} WHERE {coluna} IS NOT NULL AND {coluna} <> ''")
            for pk, valor in cur.fetchall():
                if valor and not _is_encrypted(valor):
                    cur.execute(f"UPDATE {tabela} SET {coluna} = %s WHERE id = %s", [encrypt_text(valor), pk])


def _decifra(apps, schema_editor):
    from api.crypto_fields import decrypt_text, _is_encrypted
    with schema_editor.connection.cursor() as cur:
        for tabela, coluna in _ALVOS:
            cur.execute(f"SELECT id, {coluna} FROM {tabela} WHERE {coluna} IS NOT NULL AND {coluna} <> ''")
            for pk, valor in cur.fetchall():
                if valor and _is_encrypted(valor):
                    cur.execute(f"UPDATE {tabela} SET {coluna} = %s WHERE id = %s", [decrypt_text(valor), pk])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0231_cifra_dados_sensiveis_plano_sst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensacao',
            name='observacoes',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dispensacaomedicamento',
            name='observacoes',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pacientefarmacia',
            name='alergias',
            field=api.crypto_fields.EncryptedTextField(blank=True, default='', help_text='Alergias e contraindicações conhecidas'),
        ),
        migrations.AlterField(
            model_name='pacientefarmacia',
            name='condicoes_cronicas',
            field=api.crypto_fields.EncryptedTextField(blank=True, default='', help_text='CIDs ou condições crônicas em acompanhamento'),
        ),
        migrations.AlterField(
            model_name='pacientefarmacia',
            name='medicamentos_uso_continuo',
            field=api.crypto_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.RunPython(_cifra, _decifra),
    ]
