# Generated by Django 5.2.16 on 2026-09-01 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0232_cifra_dados_sensiveis_farmacia'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlosaRecebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo_operadora', models.CharField(blank=True, default='', max_length=60)),
                ('data_glosa', models.DateField(blank=True, null=True)),
                ('origem', models.CharField(choices=[('manual', 'Registro manual'), ('xml_retorno', 'XML de retorno TISS'), ('demonstrativo', 'Demonstrativo de pagamento')], default='manual', max_length=20)),
                ('valor_glosado_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('itens', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('em_recurso', 'Em recurso'), ('encerrada', 'Encerrada')], default='recebida', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosas_recebidas', to='api.empresa')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosas_recebidas', to='api.guiatiss')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RecursoGlosaPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_glosa', models.CharField(blank=True, default='', max_length=10)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('ia_merito_score', models.PositiveSmallIntegerField(default=0)),
                ('ia_parecer', models.TextField(blank=True, default='')),
                ('valor_recorrido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_recuperado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('protocolo', models.CharField(blank=True, default='', max_length=60)),
                ('resposta_operadora', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('enviado', 'Enviado à operadora'), ('deferido', 'Deferido'), ('parcial', 'Deferido parcial'), ('indeferido', 'Indeferido')], default='aberto', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_glosa_prestador', to='api.empresa')),
                ('glosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='api.glosarecebida')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='glosarecebida',
            index=models.Index(fields=['empresa', 'status'], name='api_glosare_empresa_2b3a71_idx'),
        ),
        migrations.AddIndex(
            model_name='recursoglosaprestador',
            index=models.Index(fields=['empresa', 'status'], name='api_recurso_empresa_ad387a_idx'),
        ),
    ]
