# Generated by Django 5.2.16 on 2026-09-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0233_glosarecebida_recursoglosaprestador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dpo_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail do DPO'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='dpo_nome',
            field=models.CharField(blank=True, default='', help_text='Art. 41 LGPD — encarregado de dados indicado pela empresa.', max_length=150, verbose_name='Nome do DPO (Encarregado)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='lgpd_politica_aceita_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de aceite da política de privacidade'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='lgpd_politica_versao',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Versão da política de privacidade aceita'),
        ),
    ]
