# Generated by Django 5.2.16 on 2026-09-08 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0234_empresa_dpo_lgpd_campos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoFornecedorOPME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('marca_ofertada', models.CharField(blank=True, default='', max_length=150)),
                ('registro_anvisa', models.CharField(blank=True, default='', max_length=20)),
                ('prazo_entrega_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('afe_ativa', models.BooleanField(default=False, help_text='Fornecedor tinha AFE ANVISA ativa no lance')),
                ('anvisa_valido', models.BooleanField(default=True, help_text='Registro do produto válido (ou não informado)')),
                ('valida', models.BooleanField(db_index=True, default=False, help_text='Elegível a vencer (AFE ativa + ANVISA ok)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lances_opme', to='api.fornecedorhospital')),
            ],
            options={
                'verbose_name': 'Lance de Cotação OPME',
                'verbose_name_plural': 'Lances de Cotação OPME',
                'ordering': ['preco_unitario', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CotacaoOPME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço de referência (teto)')),
                ('status', models.CharField(choices=[('aberta', 'Aberta para lances'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], db_index=True, default='aberta', max_length=12)),
                ('prazo_ate', models.DateField(blank=True, null=True, verbose_name='Prazo para receber lances')),
                ('economia_obtida', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('criado_por', models.CharField(blank=True, default='', max_length=160)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('autorizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacoes', to='api.autorizacaoopme')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes_opme', to='api.empresa')),
                ('opme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes', to='api.catalogoopme')),
                ('vencedora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venceu_cotacao', to='api.cotacaofornecedoropme')),
            ],
            options={
                'verbose_name': 'Cotação OPME',
                'verbose_name_plural': 'Cotações OPME',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='cotacaofornecedoropme',
            name='cotacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances', to='api.cotacaoopme'),
        ),
        migrations.AddIndex(
            model_name='cotacaoopme',
            index=models.Index(fields=['empresa', 'status'], name='api_cotacao_empresa_d13931_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacaoopme',
            index=models.Index(fields=['empresa', 'opme'], name='api_cotacao_empresa_b8421a_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacaofornecedoropme',
            index=models.Index(fields=['cotacao', 'valida'], name='api_cotacao_cotacao_33f410_idx'),
        ),
    ]
