# Generated by Django 5.2.16 on 2026-09-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0235_cotacaofornecedoropme_cotacaoopme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opmeprocedimento',
            name='especialidade',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Especialidade'),
        ),
    ]
