# Generated by Django 5.2.16 on 2026-09-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0236_opmeprocedimento_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemautorizacaoopme',
            name='acima_mediana',
            field=models.BooleanField(default=False, verbose_name='Preço pedido acima da mediana'),
        ),
        migrations.AddField(
            model_name='itemautorizacaoopme',
            name='economia_sobrepreco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Economia por alinhar à mediana (R$)'),
        ),
        migrations.AddField(
            model_name='itemautorizacaoopme',
            name='mediana_referencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Mediana do preço praticado (histórico)'),
        ),
    ]
