# Generated by Django 5.2.16 on 2026-09-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0237_itemautorizacaoopme_acima_mediana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacaoopme',
            name='urgente',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Pedido urgente/emergencial'),
        ),
    ]
