# Generated by Django 5.2.16 on 2026-09-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0238_autorizacaoopme_urgente'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemautorizacaoopme',
            name='preco_negociado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço negociado na cotação (R$)'),
        ),
    ]
