# Generated by Django 5.2.16 on 2026-09-09 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0239_itemautorizacaoopme_preco_negociado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoOPME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_recebida', models.PositiveIntegerField(default=1)),
                ('lote', models.CharField(blank=True, default='', max_length=100)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=100)),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade do lote recebido')),
                ('nota_fiscal', models.CharField(blank=True, default='', max_length=60)),
                ('anvisa_situacao', models.CharField(blank=True, default='', max_length=40)),
                ('anvisa_ok', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('liberado', 'Liberado para cirurgia'), ('bloqueado', 'Bloqueado — falha na validação'), ('consumido', 'Consumido (implantado)')], db_index=True, default='liberado', max_length=12)),
                ('motivo_bloqueio', models.TextField(blank=True, default='')),
                ('recebido_por', models.CharField(blank=True, default='', max_length=160)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('liberado_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('autorizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='api.autorizacaoopme')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos_opme', to='api.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos_opme', to='api.fornecedorhospital')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos', to='api.itemautorizacaoopme')),
                ('opme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='api.catalogoopme')),
            ],
            options={
                'verbose_name': 'Recebimento OPME',
                'verbose_name_plural': 'Recebimentos OPME',
                'ordering': ['-recebido_em'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='api_recebim_empresa_13e2ba_idx'), models.Index(fields=['autorizacao', 'status'], name='api_recebim_autoriz_b49608_idx')],
            },
        ),
    ]
