# Generated by Django 5.2.16 on 2026-09-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0240_recebimentoopme'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacaoopme',
            name='solicitado_por_usuario_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Usuário autenticado que criou a solicitação'),
        ),
    ]
