# Generated by Django 5.2.16 on 2026-09-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0241_autorizacaoopme_solicitado_por_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacaofornecedoropme',
            name='registrado_por',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Registrado por (operador)'),
        ),
    ]
