# Generated by Django 5.2.16 on 2026-09-12 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0242_cotacaofornecedoropme_registrado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimentoopme',
            name='consignado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='recebimentoopme',
            name='autorizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='api.autorizacaoopme'),
        ),
        migrations.AlterField(
            model_name='recebimentoopme',
            name='status',
            field=models.CharField(choices=[('consignado', 'Em consignação (estoque do fornecedor)'), ('liberado', 'Liberado para cirurgia'), ('bloqueado', 'Bloqueado — falha na validação'), ('consumido', 'Consumido (implantado)'), ('devolvido', 'Devolvido ao fornecedor')], db_index=True, default='liberado', max_length=12),
        ),
    ]
