# Generated by Django 5.2.16 on 2026-09-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0243_recebimentoopme_consignacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacaoopme',
            name='adequacao_confirmada',
            field=models.BooleanField(default=False, help_text='Médico confirmou a indicação clínica'),
        ),
        migrations.AddField(
            model_name='autorizacaoopme',
            name='adequacao_confirmada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autorizacaoopme',
            name='adequacao_confirmada_por',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='autorizacaoopme',
            name='adequacao_evidencia',
            field=models.TextField(blank=True, default='', help_text='Diretriz/critério que embasa o veredito de indicação'),
        ),
        migrations.AddField(
            model_name='autorizacaoopme',
            name='adequacao_status',
            field=models.CharField(choices=[('verde', 'Indicação clara'), ('amarelo', 'Revisar indicação'), ('vermelho', 'Indicação frágil'), ('nao_avaliado', 'Sem base de indicação')], db_index=True, default='nao_avaliado', max_length=12, verbose_name='Adequação clínica (Camada 1)'),
        ),
        migrations.CreateModel(
            name='IndicacaoClinicaOPME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento_tuss', models.CharField(db_index=True, max_length=10, verbose_name='Procedimento TUSS/SIGTAP')),
                ('procedimento_descricao', models.CharField(blank=True, default='', max_length=200)),
                ('especialidade', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('cid10_prefixo', models.CharField(db_index=True, max_length=6, verbose_name='CID-10 (código ou prefixo, ex.: M16)')),
                ('nivel', models.CharField(choices=[('indicado', 'Indicado'), ('condicional', 'Condicional (exige critério)'), ('nao_indicado', 'Não indicado')], default='indicado', max_length=14)),
                ('criterio', models.TextField(blank=True, default='', help_text='Critério da diretriz (para nível condicional)')),
                ('fonte', models.CharField(blank=True, default='', help_text='Diretriz/evidência de referência', max_length=160)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indicação clínica OPME',
                'verbose_name_plural': 'Indicações clínicas OPME',
                'ordering': ['procedimento_tuss', 'cid10_prefixo'],
                'indexes': [models.Index(fields=['procedimento_tuss', 'cid10_prefixo'], name='api_indicac_procedi_5355b4_idx')],
                'unique_together': {('procedimento_tuss', 'cid10_prefixo')},
            },
        ),
    ]
