# Generated by Django 5.2.16 on 2026-09-19 19:08

import api.crypto_fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0244_autorizacaoopme_adequacao_confirmada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaConservacaoAuditiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano-base')),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('medidas_engenharia', models.TextField(blank=True, verbose_name='Medidas de engenharia (controle de ruído na fonte)')),
                ('medidas_administrativas', models.TextField(blank=True, verbose_name='Medidas administrativas (rodízio, pausas)')),
                ('medidas_epi', models.TextField(blank=True, verbose_name='Proteção auditiva (EPI) adotada')),
                ('responsavel', models.CharField(blank=True, max_length=200)),
                ('conselho', models.CharField(blank=True, max_length=40, verbose_name='Registro do responsável (CRM/CRFa)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('revisao', 'Em Revisão'), ('encerrado', 'Encerrado')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcas', to='api.empresa')),
            ],
            options={
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Audiometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('referencia', 'Referência (base)'), ('sequencial', 'Sequencial (periódica)'), ('retorno', 'Retorno ao Trabalho'), ('demissional', 'Demissional')], default='sequencial', max_length=20)),
                ('data_exame', models.DateField()),
                ('limiares', models.JSONField(blank=True, default=dict)),
                ('anamnese_auricular', api.crypto_fields.EncryptedTextField(blank=True)),
                ('repouso_acustico_horas', models.PositiveIntegerField(default=14, verbose_name='Repouso acústico (horas)')),
                ('responsavel', models.CharField(blank=True, max_length=200, verbose_name='Fonoaudiólogo/Médico responsável')),
                ('conselho', models.CharField(blank=True, max_length=40, verbose_name='Registro (CRFa/CRM)')),
                ('classificacao', models.CharField(choices=[('normal', 'Normal'), ('sugestivo_pair', 'Sugestivo de PAIR'), ('alterada_nao_pair', 'Alterada (não-PAIR)'), ('indeterminado', 'Indeterminado')], default='indeterminado', max_length=20)),
                ('classificacao_sequencial', models.CharField(choices=[('referencia', 'Referência'), ('estavel', 'Estável'), ('desencadeamento', 'Desencadeamento'), ('agravamento', 'Agravamento'), ('melhora', 'Melhora')], default='referencia', max_length=20)),
                ('sugestivo_pair', models.BooleanField(default=False)),
                ('reteste_indicado', models.BooleanField(default=False)),
                ('interpretacao', models.JSONField(blank=True, default=dict)),
                ('resultado_resumo', models.TextField(blank=True)),
                ('observacoes', api.crypto_fields.EncryptedTextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiometrias', to='api.asoocupacional')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiometrias', to='api.empresa')),
                ('exame_ocupacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiometrias', to='api.exameocupacional')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiometrias', to='api.funcionariosst')),
                ('pca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiometrias', to='api.programaconservacaoauditiva')),
            ],
            options={
                'ordering': ['-data_exame'],
            },
        ),
        migrations.AddIndex(
            model_name='programaconservacaoauditiva',
            index=models.Index(fields=['empresa', 'ano'], name='api_program_empresa_5cf04b_idx'),
        ),
        migrations.AddIndex(
            model_name='audiometria',
            index=models.Index(fields=['empresa', 'funcionario', 'data_exame'], name='api_audiome_empresa_532129_idx'),
        ),
        migrations.AddIndex(
            model_name='audiometria',
            index=models.Index(fields=['empresa', 'classificacao'], name='api_audiome_empresa_8dabc8_idx'),
        ),
        migrations.AddIndex(
            model_name='audiometria',
            index=models.Index(fields=['empresa', 'reteste_indicado'], name='api_audiome_empresa_4a0a8d_idx'),
        ),
    ]
