# Generated by Django 5.2.16 on 2026-09-19 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0245_programaconservacaoauditiva_audiometria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteConsultoriaSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200)),
                ('cnpj_cliente', models.CharField(blank=True, max_length=18)),
                ('email_contato', models.EmailField(blank=True, max_length=254)),
                ('token_acesso', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pode_baixar', models.BooleanField(default=True, verbose_name='Pode baixar documentos')),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_consultoria', to='api.empresa')),
            ],
            options={
                'ordering': ['nome_cliente'],
            },
        ),
        migrations.CreateModel(
            name='AcessoSECLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('acao', models.CharField(blank=True, max_length=60)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='api.clienteconsultoriasst')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CompartilhamentoSEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('compartilhado_em', models.DateTimeField(auto_now_add=True)),
                ('visualizado_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.clienteconsultoriasst')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos_sec', to='api.documentosst')),
                ('laudo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos_sec', to='api.laudotecnicosst')),
            ],
            options={
                'ordering': ['-compartilhado_em'],
            },
        ),
        migrations.CreateModel(
            name='EleicaoCIPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('num_vagas', models.PositiveSmallIntegerField(default=1, verbose_name='Vagas de titulares')),
                ('inscricao_inicio', models.DateField(blank=True, null=True)),
                ('inscricao_fim', models.DateField(blank=True, null=True)),
                ('votacao_inicio', models.DateTimeField(blank=True, null=True)),
                ('votacao_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('inscricoes', 'Inscrições Abertas'), ('votacao', 'Votação Aberta'), ('apurada', 'Apurada'), ('encerrada', 'Encerrada')], default='inscricoes', max_length=20)),
                ('apurada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('comissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleicoes', to='api.comissaocipa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleicoes_cipa', to='api.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CandidatoCIPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=0, verbose_name='Número na urna')),
                ('proposta', models.TextField(blank=True)),
                ('deferido', models.BooleanField(default=True, verbose_name='Inscrição deferida')),
                ('votos', models.PositiveIntegerField(default=0, verbose_name='Votos apurados (cache)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas_cipa', to='api.funcionariosst')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='api.eleicaocipa')),
            ],
            options={
                'ordering': ['numero', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GrupoFocalPsicossocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateField(blank=True, null=True)),
                ('facilitador', models.CharField(blank=True, max_length=200)),
                ('setor_alvo', models.CharField(blank=True, max_length=120)),
                ('num_participantes', models.PositiveSmallIntegerField(default=0)),
                ('roteiro', models.TextField(blank=True, verbose_name='Roteiro / perguntas norteadoras')),
                ('achados', models.TextField(blank=True, verbose_name='Achados consolidados')),
                ('plano_acao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('realizado', 'Realizado'), ('consolidado', 'Consolidado')], default='planejado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('avaliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_focais', to='api.avaliacaopsicossocial')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_focais', to='api.empresa')),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FatorPsicossocialGrupoFocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('organizacao', 'Organização do trabalho'), ('sobrecarga', 'Sobrecarga / ritmo'), ('relacoes', 'Relações interpessoais'), ('assedio', 'Assédio moral/sexual'), ('autonomia', 'Falta de autonomia'), ('reconhecimento', 'Falta de reconhecimento'), ('jornada', 'Jornada / turnos'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField()),
                ('gravidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('medida_recomendada', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatores', to='api.grupofocalpsicossocial')),
            ],
            options={
                'ordering': ['-gravidade', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SincronizacaoEPIOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_cliente', models.CharField(db_index=True, max_length=64, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processado', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_epi_offline', to='api.empresa')),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem_offline', to='api.entregaepi')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TokenIntegracaoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome/descrição da integração')),
                ('token_hash', models.CharField(db_index=True, max_length=128)),
                ('prefixo', models.CharField(blank=True, help_text='Primeiros caracteres, para identificação', max_length=12)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_integracao', to='api.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LogIntegracaoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=120)),
                ('metodo', models.CharField(blank=True, max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('registros', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.tokenintegracaosst')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VersaoDocumentoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(default=1)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='sst_doc_versoes/%Y/%m/')),
                ('nome_arquivo_original', models.CharField(blank=True, default='', max_length=255)),
                ('hash_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('tamanho_bytes', models.PositiveIntegerField(default=0)),
                ('autor', models.CharField(blank=True, default='', max_length=160)),
                ('nota', models.CharField(blank=True, default='', max_length=255, verbose_name='Nota da versão')),
                ('assinado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes_sst', to='api.assinaturadocumentosst')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='api.documentosst')),
            ],
            options={
                'ordering': ['-versao'],
            },
        ),
        migrations.CreateModel(
            name='VotanteCIPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votou', models.BooleanField(default=False)),
                ('votou_em', models.DateTimeField(blank=True, null=True)),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votantes', to='api.eleicaocipa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_cipa', to='api.funcionariosst')),
            ],
        ),
        migrations.CreateModel(
            name='VotoCIPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_recebidos', to='api.candidatocipa')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='api.eleicaocipa')),
            ],
        ),
        migrations.AddIndex(
            model_name='clienteconsultoriasst',
            index=models.Index(fields=['empresa', 'ativo'], name='api_cliente_empresa_538127_idx'),
        ),
        migrations.AddIndex(
            model_name='compartilhamentosec',
            index=models.Index(fields=['cliente'], name='api_compart_cliente_868092_idx'),
        ),
        migrations.AddIndex(
            model_name='eleicaocipa',
            index=models.Index(fields=['empresa', 'status'], name='api_eleicao_empresa_750efb_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidatocipa',
            constraint=models.UniqueConstraint(fields=('eleicao', 'funcionario'), name='uniq_candidato_eleicao'),
        ),
        migrations.AddIndex(
            model_name='grupofocalpsicossocial',
            index=models.Index(fields=['empresa', 'status'], name='api_grupofo_empresa_9a814c_idx'),
        ),
        migrations.AddIndex(
            model_name='sincronizacaoepioffline',
            index=models.Index(fields=['empresa', 'processado'], name='api_sincron_empresa_dbd66f_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenintegracaosst',
            index=models.Index(fields=['empresa', 'ativo'], name='api_tokenin_empresa_37b1ab_idx'),
        ),
        migrations.AddIndex(
            model_name='logintegracaosst',
            index=models.Index(fields=['token', 'criado_em'], name='api_loginte_token_i_f8d573_idx'),
        ),
        migrations.AddConstraint(
            model_name='versaodocumentosst',
            constraint=models.UniqueConstraint(fields=('documento', 'versao'), name='uniq_versao_doc_sst'),
        ),
        migrations.AddConstraint(
            model_name='votantecipa',
            constraint=models.UniqueConstraint(fields=('eleicao', 'funcionario'), name='uniq_votante_eleicao'),
        ),
        migrations.AddIndex(
            model_name='votocipa',
            index=models.Index(fields=['eleicao', 'candidato'], name='api_votocip_eleicao_fd389c_idx'),
        ),
    ]
