# Generated by Django 5.2.16 on 2026-09-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0246_clienteconsultoriasst_acessoseclog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votantecipa',
            name='token',
            field=models.CharField(blank=True, db_index=True, help_text='Token do link individual de votação', max_length=64),
        ),
    ]
