# Generated by Django 5.2.16 on 2026-09-19 19:53

import api.crypto_fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0247_votantecipa_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espirometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('referencia', 'Referência (base)'), ('sequencial', 'Sequencial (periódica)'), ('retorno', 'Retorno ao Trabalho'), ('demissional', 'Demissional')], default='sequencial', max_length=20)),
                ('data_exame', models.DateField()),
                ('cvf', models.FloatField(blank=True, null=True, verbose_name='CVF (litros)')),
                ('vef1', models.FloatField(blank=True, null=True, verbose_name='VEF1 (litros)')),
                ('vef1_cvf', models.FloatField(blank=True, null=True, verbose_name='VEF1/CVF (fração)')),
                ('cvf_prev', models.FloatField(blank=True, null=True, verbose_name='CVF (% do previsto)')),
                ('vef1_prev', models.FloatField(blank=True, null=True, verbose_name='VEF1 (% do previsto)')),
                ('responsavel', models.CharField(blank=True, max_length=200)),
                ('conselho', models.CharField(blank=True, max_length=40)),
                ('padrao', models.CharField(choices=[('normal', 'Normal'), ('obstrutivo', 'Obstrutivo'), ('restritivo', 'Restritivo (sugestivo)'), ('misto', 'Misto'), ('indeterminado', 'Indeterminado')], default='indeterminado', max_length=20)),
                ('grau', models.CharField(blank=True, max_length=30)),
                ('classificacao_sequencial', models.CharField(choices=[('referencia', 'Referência'), ('estavel', 'Estável'), ('declinio', 'Declínio funcional'), ('melhora', 'Melhora')], default='referencia', max_length=20)),
                ('declinio_indicado', models.BooleanField(default=False)),
                ('interpretacao', models.JSONField(blank=True, default=dict)),
                ('resultado_resumo', models.TextField(blank=True)),
                ('observacoes', api.crypto_fields.EncryptedTextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espirometrias', to='api.asoocupacional')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espirometrias', to='api.empresa')),
                ('exame_ocupacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espirometrias', to='api.exameocupacional')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espirometrias', to='api.funcionariosst')),
            ],
            options={
                'ordering': ['-data_exame'],
                'indexes': [models.Index(fields=['empresa', 'funcionario', 'data_exame'], name='api_espirom_empresa_a25724_idx'), models.Index(fields=['empresa', 'padrao'], name='api_espirom_empresa_ab7ef8_idx')],
            },
        ),
    ]
