# Generated by Django 5.2.16 on 2026-09-19 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0248_espirometria'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('funcao', models.CharField(max_length=160, verbose_name='Função / cargo')),
                ('setor', models.CharField(blank=True, max_length=120)),
                ('descricao_atividade', models.TextField(blank=True, verbose_name='Descrição das atividades')),
                ('riscos', models.TextField(blank=True, verbose_name='Riscos ocupacionais')),
                ('medidas_preventivas', models.TextField(blank=True, verbose_name='Medidas de prevenção')),
                ('epis_obrigatorios', models.TextField(blank=True, verbose_name='EPIs obrigatórios')),
                ('procedimentos_seguranca', models.TextField(blank=True, verbose_name='Procedimentos seguros de trabalho')),
                ('condutas_proibidas', models.TextField(blank=True, verbose_name='Condutas proibidas')),
                ('responsavel', models.CharField(blank=True, max_length=200)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('revisao', 'Em Revisão'), ('arquivada', 'Arquivada')], default='vigente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico_sst', to='api.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoCiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('assinado', models.BooleanField(default=False)),
                ('assinatura_base64', models.TextField(blank=True, default='')),
                ('data_ciencia', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciencias_os', to='api.funcionariosst')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciencias', to='api.ordemservicosst')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='ordemservicosst',
            index=models.Index(fields=['empresa', 'status'], name='api_ordemse_empresa_ed76e8_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservicosst',
            index=models.Index(fields=['empresa', 'funcao'], name='api_ordemse_empresa_d11e26_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordemservicociencia',
            constraint=models.UniqueConstraint(fields=('ordem', 'funcionario'), name='uniq_ciencia_os'),
        ),
    ]
