# Generated by Django 5.2.16 on 2026-09-19 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0249_ordemservicosst_ordemservicociencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigacaoAcidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_ocorrencia', models.DateField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do evento')),
                ('metodo', models.CharField(choices=[('ishikawa', 'Ishikawa (6M)'), ('cinco_porques', '5 Porquês'), ('ambos', 'Ambos')], default='ishikawa', max_length=20)),
                ('ishikawa', models.JSONField(blank=True, default=dict)),
                ('cinco_porques', models.JSONField(blank=True, default=list)),
                ('causa_raiz', models.TextField(blank=True)),
                ('responsavel', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em Análise'), ('concluida', 'Concluída')], default='aberta', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigacoes', to='api.catocupacional')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigacoes_acidente', to='api.empresa')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigacoes_acidente', to='api.funcionariosst')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AcaoCorretivaAcidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('corretiva', 'Corretiva'), ('preventiva', 'Preventiva')], default='corretiva', max_length=12)),
                ('responsavel', models.CharField(blank=True, max_length=200)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='pendente', max_length=15)),
                ('concluida_em', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('investigacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='api.investigacaoacidente')),
            ],
            options={
                'ordering': ['prazo', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='investigacaoacidente',
            index=models.Index(fields=['empresa', 'status'], name='api_investi_empresa_9e6ef0_idx'),
        ),
    ]
