# Generated by Django 5.2.16 on 2026-09-19 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0250_investigacaoacidente_acaocorretivaacidente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspecaoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('area', models.CharField(blank=True, max_length=120, verbose_name='Área / tipo de inspeção')),
                ('local', models.CharField(blank=True, max_length=200)),
                ('data_inspecao', models.DateField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('realizada', 'Realizada'), ('concluida', 'Concluída')], default='planejada', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes_seguranca', to='api.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemInspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('conforme', models.CharField(choices=[('conforme', 'Conforme'), ('nao_conforme', 'Não Conforme'), ('na', 'Não Aplicável')], default='conforme', max_length=15)),
                ('criticidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('acao_corretiva', models.TextField(blank=True)),
                ('responsavel_acao', models.CharField(blank=True, max_length=200)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('status_acao', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='pendente', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.inspecaoseguranca')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='inspecaoseguranca',
            index=models.Index(fields=['empresa', 'status'], name='api_inspeca_empresa_367833_idx'),
        ),
    ]
